import { getScripts } from "./scripts";
import { getStyles } from "./styles";
import { FundInfo } from '../fundModel';

export function getHTML(
  fund: FundInfo,
  isDark: boolean,
  holdingAmount: number,
  costAmount: number,
  holdingGain: number,
  holdingGainRate: number,
  dailyGain: number,
  activeTab: string
): string[] {
  return [
    '<!doctype html>',
    '<html lang="zh-CN">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${fund.name} - 基金详情</title>`,
    '    <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>',
    '    <style>',
    ...getStyles(),
    '    </style>',
    '  </head>',
    '  <body>',
    '    <div class="header">',
    '      <div>',
    `        <h2>${fund.name} (${fund.code})</h2>`,
    '        <div',
    '          style="font-size: 0.9em; color: var(--vscode-descriptionForeground)"',
    '        >',
    '          数据呈现与走势对比估算',
    '        </div>',
    '      </div>',
    '      <button id="refreshDetailBtn" class="refresh-btn" type="button">刷新</button>',
    '    </div>',
    '',
    '    <div class="tabs" role="tablist" aria-label="基金详情分区">',
    `      <button class="tab-btn ${activeTab === 'holding' ? 'active' : ''}" type="button" data-tab="holding">持仓信息</button>`,
    `      <button class="tab-btn ${activeTab === 'overview' ? 'active' : ''}" type="button" data-tab="overview">基金概况</button>`,
    `      <button class="tab-btn ${activeTab === 'manager' ? 'active' : ''}" type="button" data-tab="manager">基金经理</button>`,
    `      <button class="tab-btn ${activeTab === 'theme' ? 'active' : ''}" type="button" data-tab="theme">关联板块</button>`,
    `      <button class="tab-btn ${activeTab === 'historyNet' ? 'active' : ''}" type="button" data-tab="historyNet">历史净值</button>`,
    `      <button class="tab-btn ${activeTab === 'historyYield' ? 'active' : ''}" type="button" data-tab="historyYield">累计收益</button>`,
    '    </div>',
    '',
    '    <!-- 持仓信息 -->',
    `    <section class="tab-panel card ${activeTab === 'holding' ? 'active' : ''}" data-tab-panel="holding">`,
    '      <h3>持仓信息</h3>',
    '      <div class="info-grid">',
    '        <div class="info-item">',
    '          <div class="info-label">持仓份额</div>',
    `          <div class="info-value">${fund.shares.toFixed(2)}</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">持仓成本</div>',
    `          <div class="info-value">${fund.cost.toFixed(4)}</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">当前金额</div>',
    `          <div class="info-value">${holdingAmount.toFixed(2)}</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">最新净值</div>',
    `          <div class="info-value">${fund.netValue.toFixed(4)}</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">估算净值</div>',
    `          <div class="info-value ${fund.changePercent > 0 ? 'up' : fund.changePercent < 0 ? 'down' : ''}">${fund.estimatedValue !== null ? fund.estimatedValue.toFixed(4) : '--'}</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">估算涨跌幅</div>',
    `          <div class="info-value ${fund.changePercent > 0 ? 'up' : fund.changePercent < 0 ? 'down' : ''}">${fund.changePercent > 0 ? '+' : ''}${fund.changePercent.toFixed(2)}%</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">持有收益</div>',
    `          <div class="info-value ${holdingGain > 0 ? 'up' : holdingGain < 0 ? 'down' : ''}">${holdingGain > 0 ? '+' : ''}${holdingGain.toFixed(2)}</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">持有收益率</div>',
    `          <div class="info-value ${holdingGainRate > 0 ? 'up' : holdingGainRate < 0 ? 'down' : ''}">${holdingGainRate > 0 ? '+' : ''}${holdingGainRate.toFixed(2)}%</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">日收益（估）</div>',
    `          <div class="info-value ${dailyGain > 0 ? 'up' : dailyGain < 0 ? 'down' : ''}">${dailyGain > 0 ? '+' : ''}${dailyGain.toFixed(2)}</div>`,
    '        </div>',
    '        <div class="info-item">',
    '          <div class="info-label">更新时间</div>',
    `          <div class="info-value">${fund.updateTime}</div>`,
    '        </div>',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 基金概况 -->',
    `    <section class="tab-panel card ${activeTab === 'overview' ? 'active' : ''}" data-tab-panel="overview">`,
    '      <h3>基金概况</h3>',
    '      <div id="loadingInfo" class="loading">加载中...</div>',
    '      <div id="infoGrid" class="info-grid" style="display: none">',
    '        <!-- Rendered by JS -->',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 基金经理 -->',
    `    <section class="tab-panel card ${activeTab === 'manager' ? 'active' : ''}" data-tab-panel="manager">`,
    '      <h3>基金经理</h3>',
    '      <div id="loadingManager" class="loading">加载中...</div>',
    '      <div id="managerInfo" class="manager-info" style="display: none">',
    '        <!-- Rendered by JS -->',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 关联板块 -->',
    `    <section class="tab-panel card ${activeTab === 'theme' ? 'active' : ''}" data-tab-panel="theme">`,
    '      <h3>关联板块</h3>',
    '      <div id="loadingTheme" class="loading">加载中...</div>',
    '      <div id="themeInfo" class="theme-info" style="display: none">',
    '        <!-- Rendered by JS -->',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 历史净值 -->',
    `    <section class="tab-panel card ${activeTab === 'historyNet' ? 'active' : ''}" data-tab-panel="historyNet">`,
    '      <h3>历史净值</h3>',
    '      <div class="controls">',
    '        <div class="btn-group" id="rangeBtns2">',
    '          <button data-value="1w">近1周</button>',
    '          <button data-value="y" class="active">近1月</button>',
    '          <button data-value="3y">近3月</button>',
    '          <button data-value="6y">近6月</button>',
    '          <button data-value="n">近1年</button>',
    '          <button data-value="3n">近3年</button>',
    '          <button data-value="5n">近5年</button>',
    '        </div>',
    '      </div>',
    '      <div id="loading2" class="loading">加载中...</div>',
    '      <div id="chart2" class="chart-container"></div>',
    '    </section>',
    '',
    '    <!-- 累计收益率 -->',
    `    <section class="tab-panel card ${activeTab === 'historyYield' ? 'active' : ''}" data-tab-panel="historyYield">`,
    '      <h3>累计收益</h3>',
    '      <div class="controls">',
    '        <div class="btn-group" id="rangeBtns3">',
    '          <button data-value="1w">近1周</button>',
    '          <button data-value="y" class="active">近1月</button>',
    '          <button data-value="3y">近3月</button>',
    '          <button data-value="6y">近6月</button>',
    '          <button data-value="n">近1年</button>',
    '          <button data-value="3n">近3年</button>',
    '          <button data-value="5n">近5年</button>',
    '        </div>',
    '      </div>',
    '      <div id="loading3" class="loading">加载中...</div>',
    '      <div id="chart3" class="chart-container"></div>',
    '    </section>',
    '',
    '    <script>',
    ...getScripts(fund, isDark, activeTab),
    '    </script>',
    '  </body>',
    '</html>',
    '',
  ]
}