import { getScripts } from "./scripts";
import { getStyles } from "./styles";
import { FundInfo } from '../fundModel';

export function getHTML(
  fund: FundInfo,
  isDark: boolean,
  holdingAmount: number,
  costAmount: number,
  holdingGain: number,
  holdingGainRate: number,
  dailyGain: number,
  activeTab: string,
  grayscaleMode: boolean = false,
  allFundCodes: string[] = [],
  currentIndex: number = -1
): string[] {
  return [
    '<!doctype html>',
    '<html lang="zh-CN">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${fund.name} - 基金详情</title>`,
    '    <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>',
    '    <style>',
    ...getStyles(),
    '    </style>',
    '  </head>',
    `  <body${grayscaleMode ? ' style="filter: grayscale(1);"' : ''}>`,
    '    <div class="header">',
    '      <div class="header-title">',
    `        <h2>${fund.name} (${fund.code})</h2>`,
    '        <div class="header-subtitle">',
    '          <span>数据呈现与走势对比估算</span>',
    ...(allFundCodes.length > 1 ? [
    '          <div class="fund-nav-btns">',
    `            <button id="prevFundBtn" class="nav-btn" ${currentIndex <= 0 ? 'disabled' : ''} title="${currentIndex > 0 ? `上一个：${allFundCodes[currentIndex - 1]}` : '已是第一个'}" data-code="${currentIndex > 0 ? allFundCodes[currentIndex - 1] : ''}">‹</button>`,
    `            <span class="fund-nav-pos">${currentIndex + 1} / ${allFundCodes.length}</span>`,
    `            <button id="nextFundBtn" class="nav-btn" ${currentIndex >= allFundCodes.length - 1 ? 'disabled' : ''} title="${currentIndex < allFundCodes.length - 1 ? `下一个：${allFundCodes[currentIndex + 1]}` : '已是最后一个'}" data-code="${currentIndex < allFundCodes.length - 1 ? allFundCodes[currentIndex + 1] : ''}">›</button>`,
    '          </div>',
    ] : []),
    '        </div>',
    '      </div>',
    '      <button id="refreshDetailBtn" class="refresh-btn" type="button">刷新</button>',
    '    </div>',
    '',
    '    <div class="tabs" role="tablist" aria-label="基金详情分区">',
    `      <button class="tab-btn ${activeTab === 'holding' ? 'active' : ''}" type="button" data-tab="holding">持仓概况</button>`,
    `      <button class="tab-btn ${activeTab === 'overview' ? 'active' : ''}" type="button" data-tab="overview">基金信息</button>`,
    `      <button class="tab-btn ${activeTab === 'position' ? 'active' : ''}" type="button" data-tab="position">基金持仓</button>`,
    `      <button class="tab-btn ${activeTab === 'manager' ? 'active' : ''}" type="button" data-tab="manager">基金经理</button>`,
    `      <button class="tab-btn ${activeTab === 'theme' ? 'active' : ''}" type="button" data-tab="theme">关联板块</button>`,
    `      <button class="tab-btn ${activeTab === 'feature' ? 'active' : ''}" type="button" data-tab="feature">特色数据</button>`,
    `      <button class="tab-btn ${activeTab === 'deep' ? 'active' : ''}" type="button" data-tab="deep">深度数据</button>`,
    `      <button class="tab-btn ${activeTab === 'historyNet' ? 'active' : ''}" type="button" data-tab="historyNet">历史净值</button>`,
    `      <button class="tab-btn ${activeTab === 'historyYield' ? 'active' : ''}" type="button" data-tab="historyYield">累计收益</button>`,
    '    </div>',
    '',
    '    <!-- 持仓概况 -->',
    `    <section class="tab-panel card ${activeTab === 'holding' ? 'active' : ''}" data-tab-panel="holding">`,
    '      <h3>持仓概况</h3>',
    '      <div class="holding-sections">',
    '        <div class="holding-section">',
    '          <div class="section-title">估算数据</div>',
    '          <div class="info-grid">',
    '            <div class="info-item">',
    `              <div class="info-label">估算涨幅 (${fund.updateTime.split(' ')[0] || '--'})</div>`,
    `              <div class="info-value ${fund.changePercent > 0 ? 'up' : fund.changePercent < 0 ? 'down' : ''}">${fund.changePercent > 0 ? '+' : ''}${fund.changePercent.toFixed(2)}%</div>`,
    '            </div>',
    '            <div class="info-item">',
    `              <div class="info-label">估算收益 (${fund.updateTime.split(' ')[0] || '--'})</div>`,
    `              <div class="info-value ${fund.estimatedValue !== null && (fund.estimatedValue - fund.netValue) * fund.shares > 0 ? 'up' : fund.estimatedValue !== null && (fund.estimatedValue - fund.netValue) * fund.shares < 0 ? 'down' : ''}">¥${fund.estimatedValue !== null ? ((fund.estimatedValue - fund.netValue) * fund.shares).toFixed(2) : '--'}</div>`,
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div class="holding-section">',
    '          <div class="section-title">当日数据</div>',
    '          <div class="info-grid">',
    '            <div class="info-item">',
    `              <div class="info-label">当日涨幅 (${fund.netValueDate || '--'})</div>`,
    `              <div class="info-value ${fund.navChgRt > 0 ? 'up' : fund.navChgRt < 0 ? 'down' : ''}">${fund.navChgRt > 0 ? '+' : ''}${fund.navChgRt.toFixed(2)}%</div>`,
    '            </div>',
    '            <div class="info-item">',
    `              <div class="info-label">当日收益 (${fund.netValueDate || '--'})</div>`,
    `              <div class="info-value ${dailyGain > 0 ? 'up' : dailyGain < 0 ? 'down' : ''}">${dailyGain > 0 ? '+¥' : '¥'}${dailyGain.toFixed(2)}</div>`,
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div class="holding-section">',
    '          <div class="section-title">持有收益</div>',
    '          <div class="info-grid">',
    '            <div class="info-item">',
    '              <div class="info-label">持有收益</div>',
    `              <div class="info-value ${holdingGain > 0 ? 'up' : holdingGain < 0 ? 'down' : ''}">¥${holdingGain.toFixed(2)}</div>`,
    '            </div>',
    '            <div class="info-item">',
    '              <div class="info-label">总收益率</div>',
    `              <div class="info-value ${holdingGainRate > 0 ? 'up' : holdingGainRate < 0 ? 'down' : ''}">${holdingGainRate > 0 ? '+' : ''}${holdingGainRate.toFixed(2)}%</div>`,
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div class="holding-section">',
    '          <div class="section-title">持仓信息</div>',
    '          <div class="info-grid">',
    '            <div class="info-item">',
    '              <div class="info-label">持有成本</div>',
    `              <div class="info-value">¥${costAmount.toFixed(2)}</div>`,
    '            </div>',
    '            <div class="info-item">',
    '              <div class="info-label">持有市值</div>',
    `              <div class="info-value">¥${holdingAmount.toFixed(2)}</div>`,
    '            </div>',
    '            <div class="info-item">',
    '              <div class="info-label">持有份额</div>',
    `              <div class="info-value">${fund.shares.toFixed(2)}</div>`,
    '            </div>',
    '            <div class="info-item">',
    '              <div class="info-label">成本价</div>',
    `              <div class="info-value">${fund.cost.toFixed(4)}</div>`,
    '            </div>',
    '            <div class="info-item">',
    '              <div class="info-label">估算净值</div>',
    `              <div class="info-value">${fund.estimatedValue !== null ? fund.estimatedValue.toFixed(4) : '--'}</div>`,
    '            </div>',
    '            <div class="info-item">',
    '              <div class="info-label">单位净值</div>',
    `              <div class="info-value">${fund.netValue.toFixed(4)}</div>`,
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div class="holding-section">',
    '          <div class="section-title">其他信息</div>',
    '          <div class="info-grid">',
    '            <div class="info-item">',
    '              <div class="info-label">关联板块</div>',
    '              <div class="info-value" id="relateThemeValue">--</div>',
    '            </div>',
    '            <div class="info-item">',
    '              <div class="info-label">更新时间</div>',
    `              <div class="info-value">${fund.updateTime.split(' ')[1] || fund.updateTime}</div>`,
    '            </div>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 基金持仓 -->',
    `    <section class="tab-panel card ${activeTab === 'position' ? 'active' : ''}" data-tab-panel="position">`,
    '      <h3>基金持仓</h3>',
    '      <div id="loadingPosition" class="loading">加载中...</div>',
    '      <div id="positionContent" style="display: none;">',
    '        <div id="positionDate" style="font-size: 12px; color: var(--vscode-descriptionForeground); margin-bottom: 12px;"></div>',
    '        <!-- 股票持仓 -->',
    '        <div id="stockSection" style="display: none;">',
    '          <div style="font-size: 13px; font-weight: 600; margin-bottom: 8px; padding-bottom: 6px; border-bottom: 1px solid var(--vscode-panel-border);">股票持仓</div>',
    '          <div id="stockTable"></div>',
    '        </div>',
    '        <!-- 债券持仓 -->',
    '        <div id="bondSection" style="display: none; margin-top: 16px;">',
    '          <div style="font-size: 13px; font-weight: 600; margin-bottom: 8px; padding-bottom: 6px; border-bottom: 1px solid var(--vscode-panel-border);">债券持仓</div>',
    '          <div id="bondTable"></div>',
    '        </div>',
    '        <div id="positionEmpty" style="display: none; text-align: center; color: var(--vscode-descriptionForeground); padding: 20px;">暂无持仓数据</div>',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 基金信息 -->',
    `    <section class="tab-panel card ${activeTab === 'overview' ? 'active' : ''}" data-tab-panel="overview">`,
    '      <h3>基金信息</h3>',
    '      <div id="loadingInfo" class="loading">加载中...</div>',
    '      <div id="infoGrid" class="info-grid" style="display: none">',
    '        <!-- Rendered by JS -->',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 基金经理 -->',
    `    <section class="tab-panel card ${activeTab === 'manager' ? 'active' : ''}" data-tab-panel="manager">`,
    '      <h3>基金经理</h3>',
    '      <div id="loadingManager" class="loading">加载中...</div>',
    '      <div id="managerInfo" class="manager-info" style="display: none">',
    '        <!-- Rendered by JS -->',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 关联板块 -->',
    `    <section class="tab-panel card ${activeTab === 'theme' ? 'active' : ''}" data-tab-panel="theme">`,
    '      <h3>关联板块</h3>',
    '      <div id="loadingTheme" class="loading">加载中...</div>',
    '      <div id="themeInfo" class="theme-info" style="display: none">',
    '        <!-- Rendered by JS -->',
    '      </div>',
    '    </section>',
    '',
    '    <!-- 特色数据 -->',
    `    <section class="tab-panel card ${activeTab === 'feature' ? 'active' : ''}" data-tab-panel="feature">`,
    '      <h3>特色数据</h3>',
    '      <div id="loadingFeature" class="loading">加载中...</div>',
    '      <div id="featureContent" style="display: none;">',
    '        <div class="controls">',
    '          <div class="btn-group" id="featureRangeBtns">',
    '            <button data-value="1n" class="active">近1年</button>',
    '            <button data-value="3n">近3年</button>',
    '            <button data-value="5n">近5年</button>',
    '          </div>',
    '        </div>',
    '        <div id="featureCards" class="feature-cards">',
    '          <!-- Rendered by JS -->',
    '        </div>',
    '      </div>',
    '      <div id="featureEmpty" style="display: none; text-align: center; color: var(--vscode-descriptionForeground); padding: 20px;">暂无特色数据</div>',
    '    </section>',
    '',
    '    <!-- 深度数据 -->',
    `    <section class="tab-panel card ${activeTab === 'deep' ? 'active' : ''}" data-tab-panel="deep">`,
    '      <h3>深度数据</h3>',
    '      <div id="loadingDeep" class="loading">加载中...</div>',
    '      <div id="deepContent" style="display: none;">',
    '        <!-- 基本信息和阶段收益率（由JS动态生成） -->',
    '        <div id="deepBasicInfo"></div>',
    '        ',
    '        <!-- 累计收益走势 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">累计收益走势</div>',
    '          <div id="grandTotalChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 同类排行走势 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">同类排行走势</div>',
    '          <div id="rankChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 规模变动 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">规模变动</div>',
    '          <div id="fluctuationChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 持有人结构 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">持有人结构</div>',
    '          <div id="holderChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 资产配置 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">资产配置</div>',
    '          <div id="assetChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 业绩评价 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">业绩评价</div>',
    '          <div id="performanceChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 申购赎回 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">申购赎回</div>',
    '          <div id="buySellChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 股票仓位测算 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">股票仓位测算</div>',
    '          <div id="sharePositionChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 单位净值走势 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">单位净值走势</div>',
    '          <div id="netWorthTrendChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 累计净值走势 -->',
    '        <div class="deep-chart-section">',
    '          <div class="deep-section-title">累计净值走势</div>',
    '          <div id="acWorthTrendChart" class="deep-chart-container"></div>',
    '        </div>',
    '        ',
    '        <!-- 基金经理 -->',
    '        <div id="deepManagersSection" style="display: none;" class="deep-chart-section">',
    '          <div class="deep-section-title">基金经理</div>',
    '          <div id="deepManagers" class="deep-manager-list"></div>',
    '        </div>',
    '        ',
    '        <!-- 同类涨幅榜 -->',
    '        <div id="deepSameTypeSection" style="display: none;" class="deep-chart-section">',
    '          <div class="deep-section-title">同类涨幅榜</div>',
    '          <div id="deepSameType" class="deep-same-type-grid"></div>',
    '        </div>',
    '        ',
    '        <!-- 持仓代码 -->',
    '        <div id="deepCodesSection" style="display: none;" class="deep-codes-section">',
    '          <div id="deepStockCodes" class="deep-codes-group" style="display: none;">',
    '            <div class="deep-codes-label">持仓股票代码</div>',
    '            <div id="deepStockCodesList" class="deep-codes-list"></div>',
    '          </div>',
    '          <div id="deepStockCodesNew" class="deep-codes-group" style="display: none;">',
    '            <div class="deep-codes-label">持仓股票代码（新市场号）</div>',
    '            <div id="deepStockCodesNewList" class="deep-codes-list"></div>',
    '          </div>',
    '          <div id="deepBondCodes" class="deep-codes-group" style="display: none;">',
    '            <div class="deep-codes-label">债券代码</div>',
    '            <div id="deepBondCodesList" class="deep-codes-list"></div>',
    '          </div>',
    '          <div id="deepBondCodesNew" class="deep-codes-group" style="display: none;">',
    '            <div class="deep-codes-label">债券代码（新市场号）</div>',
    '            <div id="deepBondCodesNewList" class="deep-codes-list"></div>',
    '          </div>',
    '        </div>',
    '      </div>',
    '      <div id="deepEmpty" style="display: none; text-align: center; color: var(--vscode-descriptionForeground); padding: 20px;">暂无深度数据</div>',
    '    </section>',
    '',
    '    <!-- 历史净值 -->',
    `    <section class="tab-panel card ${activeTab === 'historyNet' ? 'active' : ''}" data-tab-panel="historyNet">`,
    '      <h3>历史净值</h3>',
    '      <div class="controls">',
    '        <div class="btn-group" id="rangeBtns2">',
    '          <button data-value="1w">近1周</button>',
    '          <button data-value="y" class="active">近1月</button>',
    '          <button data-value="3y">近3月</button>',
    '          <button data-value="6y">近6月</button>',
    '          <button data-value="n">近1年</button>',
    '          <button data-value="3n">近3年</button>',
    '          <button data-value="5n">近5年</button>',
    '          <button data-value="ln">成立以来</button>',
    '        </div>',
    '      </div>',
    '      <div id="loading2" class="loading">加载中...</div>',
    '      <div id="chart2" class="chart-container"></div>',
    '    </section>',
    '',
    '    <!-- 累计收益率 -->',
    `    <section class="tab-panel card ${activeTab === 'historyYield' ? 'active' : ''}" data-tab-panel="historyYield">`,
    '      <h3>累计收益</h3>',
    '      <div class="controls">',
    '        <div class="btn-group" id="rangeBtns3">',
    '          <button data-value="1w">近1周</button>',
    '          <button data-value="y" class="active">近1月</button>',
    '          <button data-value="3y">近3月</button>',
    '          <button data-value="6y">近6月</button>',
    '          <button data-value="n">近1年</button>',
    '          <button data-value="3n">近3年</button>',
    '          <button data-value="5n">近5年</button>',
    '          <button data-value="ln">成立以来</button>',
    '        </div>',
    '      </div>',
    '      <div id="loading3" class="loading">加载中...</div>',
    '      <div id="chart3" class="chart-container"></div>',
    '    </section>',
    '',
    '    <script>',
    ...getScripts(fund, isDark, activeTab, allFundCodes, currentIndex),
    '    </script>',
    '  </body>',
    '</html>',
    '',
  ]
}