import { FundInfo } from '../fundModel';


export function getScripts(fund: FundInfo, isDark: boolean, activeTab: string, allFundCodes: string[] = [], currentIndex: number = -1): string[] {
  return [
    `      const fundCode = "${fund.code}";`,
    `      const isDark = ${isDark ? 'true' : 'false'};`,
    `      const initialActiveTab = "${activeTab}";`,
    `      const allFundCodes = ${JSON.stringify(allFundCodes)};`,
    `      const currentIndex = ${currentIndex};`,
    '      let deepDataLoaded = false;',
    '      let deepCharts = {};',
    '      const vscode = acquireVsCodeApi();',
    '      let activeTab = vscode.getState()?.activeTab || initialActiveTab;',
    '      let defaultTextColor = isDark ? "#cccccc" : "#333333";',
    '      let defaultGridColor = isDark ? "#444444" : "#dddddd";',
    '',
    '      // Utility: JSONP loader',
    '      function loadJSONP(url, callbackName) {',
    '        return new Promise((resolve, reject) => {',
    '          const script = document.createElement("script");',
    '          const fullUrl =',
    '            url + (url.includes("?") ? "&" : "?") + "callback=" + callbackName;',
    '          script.src = fullUrl;',
    '',
    '          window[callbackName] = function (data) {',
    '            resolve(data);',
    '            document.head.removeChild(script);',
    '            delete window[callbackName];',
    '          };',
    '',
    '          script.onerror = function () {',
    '            reject(new Error("JSONP failed"));',
    '            document.head.removeChild(script);',
    '            delete window[callbackName];',
    '          };',
    '',
    '          document.head.appendChild(script);',
    '        });',
    '      }',
    '',
    '      // Utility: UUID generator',
    '      function generateUUID() {',
    '        return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function(c) {',
    '          const r = (Math.random() * 16) | 0;',
    '          const v = c === "x" ? r : (r & 0x3) | 0x8;',
    '          return v.toString(16);',
    '        });',
    '      }',
    '',
    '      const chart2 = echarts.init(document.getElementById("chart2"));',
    '      const chart3 = echarts.init(document.getElementById("chart3"));',
    '',
    '      function syncTabState(tab) {',
    '        activeTab = tab;',
    '        vscode.setState({ activeTab });',
    '        document.querySelectorAll("[data-tab]").forEach((btn) => {',
    '          btn.classList.toggle("active", btn.getAttribute("data-tab") === tab);',
    '        });',
    '        document.querySelectorAll("[data-tab-panel]").forEach((panel) => {',
    '          panel.classList.toggle("active", panel.getAttribute("data-tab-panel") === tab);',
    '        });',
    '        requestAnimationFrame(() => {',
    '          if (tab === "historyNet") {',
    '            chart2.resize();',
    '          } else if (tab === "historyYield") {',
    '            chart3.resize();',
    '          }',
    '        });',
    '      }',
    '',
    '      document.querySelectorAll("[data-tab]").forEach((btn) => {',
    '        btn.addEventListener("click", () => {',
    '          const tab = btn.getAttribute("data-tab");',
    '          if (tab) {',
    '            syncTabState(tab);',
    '          }',
    '        });',
    '      });',
    '',
    '      document.getElementById("refreshDetailBtn").addEventListener("click", () => {',
    '        const btn = document.getElementById("refreshDetailBtn");',
    '        btn.textContent = "刷新中...";',
    '        btn.disabled = true;',
    '        vscode.postMessage({ command: "refresh", activeTab });',
    '        setTimeout(() => {',
    '          btn.textContent = "刷新";',
    '          btn.disabled = false;',
    '        }, 2000);',
    '      });',
    '',
    '      // 基金导航按钮',
    '      const prevBtn = document.getElementById("prevFundBtn");',
    '      const nextBtn = document.getElementById("nextFundBtn");',
    '      if (prevBtn) {',
    '        prevBtn.addEventListener("click", (e) => {',
    '          e.preventDefault();',
    '          if (!prevBtn.hasAttribute("disabled")) {',
    '            const attrCode = prevBtn.getAttribute("data-code");',
    '            const targetCode = attrCode || (currentIndex > 0 ? allFundCodes[currentIndex - 1] : "");',
    '            if (targetCode) {',
    '              vscode.postMessage({ command: "navigateToFund", code: targetCode });',
    '              return;',
    '            }',
    '          }',
    '          console.error("Cannot navigate prev, disabled or at first");',
    '        });',
    '      }',
    '      if (nextBtn) {',
    '        nextBtn.addEventListener("click", (e) => {',
    '          e.preventDefault();',
    '          if (!nextBtn.hasAttribute("disabled")) {',
    '            const attrCode = nextBtn.getAttribute("data-code");',
    '            const targetCode = attrCode || (currentIndex < allFundCodes.length - 1 ? allFundCodes[currentIndex + 1] : "");',
    '            if (targetCode) {',
    '              vscode.postMessage({ command: "navigateToFund", code: targetCode });',
    '              return;',
    '            }',
    '          }',
    '          console.error("Cannot navigate next, disabled or at last");',
    '        });',
    '      }',
    '',
    '      let featureDataLoaded = false;',
    '      let featureRange = "1n";',
    '      let featureDataCache = null;',
    '      let periodIncreaseListCache = null;',
    '',
    '      const getCommonOption = (title) => ({',
    '        tooltip: { trigger: "axis" },',
    '        legend: {',
    '          data: [],',
    '          textStyle: { color: defaultTextColor },',
    '        },',
    '        grid: { left: "2%", right: "2%", bottom: "2%", containLabel: true },',
    '        xAxis: {',
    '          type: "category",',
    '          boundaryGap: false,',
    '          data: [],',
    '          axisLabel: { color: defaultTextColor, rotate: 45, margin: 12 },',
    '          axisLine: { lineStyle: { color: defaultGridColor } },',
    '        },',
    '        yAxis: {',
    '          type: "value",',
    '          scale: true, // Auto scaling without strictly starting from 0, makes small fluctuations visible',
    '          axisLabel: { color: defaultTextColor },',
    '          splitLine: { lineStyle: { color: defaultGridColor, type: "dashed" } },',
    '        },',
    '        series: [],',
    '      });',
    '',
    '      // Current Ranges',
    '      let range2 = "y";',
    '      let range3 = "y";',
    '',
    '      // Button Click Binders',
    '      document.querySelectorAll("#rangeBtns2 button").forEach((btn) => {',
    '        btn.addEventListener("click", (e) => {',
    '          document',
    '            .querySelectorAll("#rangeBtns2 button")',
    '            .forEach((b) => b.classList.remove("active"));',
    '          e.target.classList.add("active");',
    '          range2 = e.target.getAttribute("data-value");',
    '          fetchHistoryNetVal();',
    '        });',
    '      });',
    '',
    '      document.querySelectorAll("#rangeBtns3 button").forEach((btn) => {',
    '        btn.addEventListener("click", (e) => {',
    '          document',
    '            .querySelectorAll("#rangeBtns3 button")',
    '            .forEach((b) => b.classList.remove("active"));',
    '          e.target.classList.add("active");',
    '          range3 = e.target.getAttribute("data-value");',
    '          fetchHistoryYield();',
    '        });',
    '      });',
    '',
    '      // 基金概况',
    '      function fetchFundInfo() {',
    '        document.getElementById("loadingInfo").style.display = "block";',
    '        document.getElementById("infoGrid").style.display = "none";',
    `        let url = "https://fundmobapi.eastmoney.com/FundMApi/FundBaseTypeInformation.ashx?FCODE=${fund.code}&deviceid=Wap&plat=Wap&product=EFund&version=2.0.0&Uid=&_=${new Date().getTime()}";`,
    '        let callbackName = "jsonpInfo_" + Date.now();',
    '',
    '        loadJSONP(url, callbackName).then((res) => {',
    '          document.getElementById("loadingInfo").style.display = "none";',
    '          if (!res || !res.Datas) return;',
    '          let data = res.Datas;',
    '',
    '          function formatMoney(val) {',
    '            if (!val) return "--";',
    '            if (val >= 100000000) return (val / 100000000).toFixed(2).replace(/\\B(?=(\\d{3})+(?!\\d))/g, \',\') + " 亿";',
    '            if (val >= 10000) return (val / 10000).toFixed(2).replace(/\\B(?=(\\d{3})+(?!\\d))/g, \',\') + " 万";',
    '            return val.toFixed(2).replace(/\\B(?=(\\d{3})+(?!\\d))/g, \',\');',
    '          }',
    '',
    '          function renderColor(val) {',
    '            if (!val) return "";',
    '            let num = parseFloat(val);',
    '            if (num > 0) return "up";',
    '            if (num < 0) return "down";',
    '            return "";',
    '          }',
    '',
    '          let html = `',
    '              <div class="info-item">',
    '                  <div class="info-label">基金类型</div>',
    '                  <div class="info-value">${data.FTYPE || \'--\'}</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">成立日期</div>',
    '                  <div class="info-value">${data.ESTABDATE || \'--\'}</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">基金公司</div>',
    '                  <div class="info-value">${data.JJGS || \'--\'}</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">基金经理</div>',
    '                  <div class="info-value">${data.JJJL || \'--\'}</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">单位净值</div>',
    '                  <div class="info-value">${data.DWJZ || \'--\'} (${data.FSRQ || \'--\'})</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">累计净值</div>',
    '                  <div class="info-value">${data.LJJZ || \'--\'}</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">基金规模</div>',
    '                  <div class="info-value">${formatMoney(data.ENDNAV)}</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">交易状态</div>',
    '                  <div class="info-value">${data.SGZT || \'--\'} / ${data.SHZT || \'--\'}</div>',
    '              </div>',
    '',
    '              <div class="info-item">',
    '                  <div class="info-label">近1周收益率</div>',
    '                  <div class="info-value ${renderColor(data.SYL_Z)}">${data.SYL_Z > 0 ? \'+\':\'\'}${data.SYL_Z || \'0\'}%</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">近1月收益率 (排名)</div>',
    '                  <div class="info-value ${renderColor(data.SYL_Y)}">${data.SYL_Y > 0 ? \'+\':\'\'}${data.SYL_Y || \'0\'}% (${data.RANKM || \'--\'})</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">近3月收益率 (排名)</div>',
    '                  <div class="info-value ${renderColor(data.SYL_3Y)}">${data.SYL_3Y > 0 ? \'+\':\'\'}${data.SYL_3Y || \'0\'}% (${data.RANKQ || \'--\'})</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">近6月收益率 (排名)</div>',
    '                  <div class="info-value ${renderColor(data.SYL_6Y)}">${data.SYL_6Y > 0 ? \'+\':\'\'}${data.SYL_6Y || \'0\'}% (${data.RANKHY || \'--\'})</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">近1年收益率 (排名)</div>',
    '                  <div class="info-value ${renderColor(data.SYL_1N)}">${data.SYL_1N > 0 ? \'+\':\'\'}${data.SYL_1N || \'0\'}% (${data.RANKY || \'--\'})</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">近3年收益率 (排名)</div>',
    '                  <div class="info-value ${renderColor(data.SYL_3N)}">${data.SYL_3N > 0 ? \'+\':\'\'}${data.SYL_3N || \'0\'}% (${data.RANK3N || \'--\'})</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">近5年收益率 (排名)</div>',
    '                  <div class="info-value ${renderColor(data.SYL_5N)}">${data.SYL_5N > 0 ? \'+\':\'\'}${data.SYL_5N || \'0\'}% (${data.RANK5N || \'--\'})</div>',
    '              </div>',
    '              <div class="info-item">',
    '                  <div class="info-label">成立以来收益率</div>',
    '                  <div class="info-value ${renderColor(data.SYL_LN)}">${data.SYL_LN > 0 ? \'+\':\'\'}${data.SYL_LN || \'0\'}%</div>',
    '              </div>',
    '          `;',
    '',
    '          document.getElementById(\'infoGrid\').innerHTML = html;',
    '          document.getElementById(\'infoGrid\').style.display = \'grid\';',
    '        }).catch(e => {',
    '            document.getElementById(\'loadingInfo\').style.display = \'none\';',
    '        });',
    '      }',
    '',
    '      // 获取详细基金信息（包括基金经理和关联板块）',
    '      function fetchDetailedFundInfo() {',
    '        const url = "https://dgs.tiantianfunds.com/merge/m/api/jjxqy1_2";',
    '        const params = new URLSearchParams({',
    '          deviceid: generateUUID(),',
    '          version: "9.9.9",',
    '          appVersion: "6.5.5",',
    '          product: "EFund",',
    '          plat: "Web",',
    '          uid: "",',
    '          fcode: fundCode,',
    '          ISRG: "0",',
    '          indexfields:',
    '            "_id,INDEXCODE,BKID,INDEXNAME,INDEXVALUA,NEWINDEXTEXCH,PEP100",',
    '          fields:',
    '            "BENCH,ESTDIFF,INDEXNAME,LINKZSB,INDEXCODE,NEWTEXCH,FTYPE,FCODE,BAGTYPE,RISKLEVEL,TTYPENAME,PTDT_FY,PTDT_TRY,PTDT_TWY,PTDT_Y,DWDT_FY,DWDT_TRY,DWDT_TWY,DWDT_Y,MBDT_FY,MBDT_TRY,MBDT_TWY,MBDT_Y,YDDT_FY,YDDT_TRY,YDDT_TWY,YDDT_Y,BFUNDTYPE,YMATCHCODEA,RLEVEL_SZ,RLEVEL_CX,ESTABDATE,JJGS,JJGSID,ENDNAV,FEGMRQ,SHORTNAME,TTYPE,TJDIN,FUNDEXCHG,LISTTEXCHMARK,FSRQ,ISSBDATE,ISSEDATE,FEATURE,DWJZ,LJJZ,MINRG,RZDF,PERIODNAME,SYL_1N,SYL_LN,SYL_Z,SOURCERATE,RATE,TSRQ,BTYPE,BUY,BENCHCODE,BENCH_CORR,TRKERROR,BENCHRATIO,NEWINDEXTEXCH,BESTDT_STRATEGY,BESTDT_Y,BESTDT_TWY,BESTDT_TRY,BESTDT_FY",',
    '          fundUniqueInfo_fIELDS:',
    '            "FCODE,STDDEV1,STDDEV_1NRANK,STDDEV_1NFSC,STDDEV3,STDDEV_3NRANK,STDDEV_3NFSC,STDDEV5,STDDEV_5NRANK,STDDEV_5NFSC,SHARP1,SHARP_1NRANK,SHARP_1NFSC,SHARP3,SHARP_3NRANK,SHARP_3NFSC,SHARP5,SHARP_5NRANK,SHARP_5NFSC,MAXRETRA1,MAXRETRA_1NRANK,MAXRETRA_1NFSC,MAXRETRA3,MAXRETRA_3NRANK,MAXRETRA_3NFSC,MAXRETRA5,MAXRETRA_5NRANK,MAXRETRA_5NFSC,TRKERROR1,TRKERROR_1NRANK,TRKERROR_1NFSC,TRKERROR3,TRKERROR_3NRANK,TRKERROR_3NFSC,TRKERROR5,TRKERROR_5NRANK,TRKERROR_5NFSC",',
    '          fundUniqueInfo_fLFIELDS:',
    '            "FCODE,BUSINESSTYPE,BUSINESSTEXT,BUSINESSCODE,BUSINESSSUBTYPE,MARK",',
    '          cfhFundFInfo_fields: "INVESTMENTIDEAR,INVESTMENTIDEARIMG",',
    '          relateThemeFields: "FCODE,SEC_CODE,SEC_NAME,CORR_1Y,OL2TOP",',
    '        });',
    '',
    '        fetch(url, {',
    '          method: "POST",',
    '          headers: {',
    '            "Content-Type": "application/x-www-form-urlencoded",',
    '            Origin: "https://h5.1234567.com.cn",',
    '            "User-Agent":',
    '              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",',
    '            Referer: "https://servicewechat.com/",',
    '          },',
    '          body: params.toString(),',
    '        })',
    '          .then((response) => response.json())',
    '          .then((data) => {',
    '            if (data && data.data) {',
    '              // 处理基金经理信息',
    '              if (',
    '                data.data.FundManagerInformation &&',
    '                data.data.FundManagerInformation.currentManagerInfos',
    '              ) {',
    '                renderManagerInfo(',
    '                  data.data.FundManagerInformation.currentManagerInfos,',
    '                );',
    '              } else {',
    '                document.getElementById("loadingManager").style.display =',
    '                  "none";',
    '                document.getElementById("managerInfo").innerHTML =',
    '                  \'<p style="text-align: center; color: var(--vscode-descriptionForeground);">暂无基金经理信息</p>\';',
    '                document.getElementById("managerInfo").style.display = "flex";',
    '              }',
    '',
    '              // 处理关联板块信息',
    '              if (',
    '                data.data.fundRelateTheme &&',
    '                data.data.fundRelateTheme.length > 0',
    '              ) {',
    '                renderThemeInfo(data.data.fundRelateTheme);',
    '              } else {',
    '                document.getElementById("loadingTheme").style.display = "none";',
    '                document.getElementById("themeInfo").innerHTML =',
    '                  \'<p style="text-align: center; color: var(--vscode-descriptionForeground);">暂无关联板块信息</p>\';',
    '                document.getElementById("themeInfo").style.display = "flex";',
    '              }',
    '',
    '              // 更新基金概况中的近1周收益率（从详细接口获取）',
    '              if (data.data.baseInfo && data.data.baseInfo.length > 0) {',
    '                const baseInfo = data.data.baseInfo[0];',
    '                updateWeeklyReturn(baseInfo.SYL_Z);',
    '              }',
    '            }',
    '          })',
    '          .catch((error) => {',
    '            console.error("获取详细基金信息失败:", error);',
    '            document.getElementById("loadingManager").style.display = "none";',
    '            document.getElementById("loadingTheme").style.display = "none";',
    '            document.getElementById("managerInfo").innerHTML =',
    '              \'<p style="text-align: center; color: var(--vscode-descriptionForeground);">加载失败</p>\';',
    '            document.getElementById("themeInfo").innerHTML =',
    '              \'<p style="text-align: center; color: var(--vscode-descriptionForeground);">加载失败</p>\';',
    '            document.getElementById("managerInfo").style.display = "block";',
    '            document.getElementById("themeInfo").style.display = "flex";',
    '          });',
    '      }',
    '',
    '      // 渲染基金经理信息',
    '      function renderManagerInfo(managers) {',
    '        document.getElementById("loadingManager").style.display = "none";',
    '',
    '        let html = "";',
    '        managers.forEach((manager) => {',
    '          const sInfo = manager.SINFO || {};',
    '          const pInfo =',
    '            manager.PINFO && manager.PINFO.length > 0 ? manager.PINFO[0] : {};',
    '',
    '          const managerName = sInfo.MGRNAME || pInfo.MGRNAME || "--";',
    '          const totalDays = sInfo.TOTALDAYS || 0;',
    '          const penavGrowth = sInfo.PENAVGROWTH || 0;',
    '          const yieldSe = pInfo.YIELDSE || 0;',
    '          const resume = pInfo.RESUME || "暂无简历信息";',
    '          const avatar = pInfo.NEWPHOTOURL || "";',
    '          const investmentIdea = pInfo.INVESTMENTIDEAR || "暂无投资理念";',
    '',
    '          // 计算任职年限',
    '          const years = Math.floor(totalDays / 365);',
    '          const months = Math.floor((totalDays % 365) / 30);',
    '          const tenureText = years > 0 ? `${years}年${months}个月` : `${months}个月`;',
    '',
    '          html += `',
    '              <div class="manager-card">',
    '                  <img class="manager-avatar" src="${avatar}" alt="${managerName}" onerror="this.style.display=\'none\'">',
    '                  <div class="manager-details">',
    '                      <div class="manager-name">${managerName}</div>',
    '                      <div>',
    '                          <span class="manager-tag">任职 ${tenureText}</span>',
    '                          <span class="manager-tag">任职回报 ${penavGrowth > 0 ? \'+\' : \'\'}${penavGrowth.toFixed(2)}%</span>',
    '                      </div>',
    '                      <div class="manager-stats">',
    '                          <div class="manager-stat">',
    '                              <div class="manager-stat-label">任职天数</div>',
    '                              <div class="manager-stat-value">${totalDays}天</div>',
    '                          </div>',
    '                          <div class="manager-stat">',
    '                              <div class="manager-stat-label">年化收益</div>',
    '                              <div class="manager-stat-value">${yieldSe > 0 ? \'+\' : \'\'}${yieldSe.toFixed(2)}%</div>',
    '                          </div>',
    '                      </div>',
    '                      <div style="margin-top: 10px;">',
    '                          <strong>投资理念：</strong>${investmentIdea}',
    '                      </div>',
    '                      <div class="manager-resume">',
    '                          <strong>个人简历：</strong>${resume}',
    '                      </div>',
    '                  </div>',
    '              </div>',
    '          `;',
    '        });',
    '',
    '        document.getElementById("managerInfo").innerHTML = html;',
    '        document.getElementById("managerInfo").style.display = "block";',
    '      }',
    '',
    '      // 渲染关联板块信息',
    '      function renderThemeInfo(themes) {',
    '        document.getElementById("loadingTheme").style.display = "none";',
    '',
    '        let html = "";',
    '        themes.forEach((theme) => {',
    '          const secName = theme.SEC_NAME || "--";',
    '          const corr1Y = theme.CORR_1Y || 0;',
    '          const ol2Top = theme.OL2TOP || 0;',
    '',
    '          html += `',
    '              <div class="theme-tag">',
    '                  <span class="theme-name">${secName}</span>',
    '                  <span class="theme-corr">相关性 ${corr1Y.toFixed(1)}%</span>',
    '              </div>',
    '          `;',
    '        });',
    '',
    '        document.getElementById("themeInfo").innerHTML = html;',
    '        document.getElementById("themeInfo").style.display = "flex";',
    '      }',
    '',
    '      // 更新近1周收益率',
    '      function updateWeeklyReturn(sylZ) {',
    '        // 等待基金概况加载完成后更新',
    '        setTimeout(() => {',
    '          const weeklyElements = document.querySelectorAll(',
    '            ".info-grid .info-item",',
    '          );',
    '          weeklyElements.forEach((item) => {',
    '            const label = item.querySelector(".info-label");',
    '            if (label && label.textContent === "近1周收益率") {',
    '              const valueElement = item.querySelector(".info-value");',
    '              if (valueElement && sylZ !== undefined && sylZ !== null) {',
    '                const colorClass = sylZ > 0 ? "up" : sylZ < 0 ? "down" : "";',
    '                valueElement.className = `info-value ${colorClass}`;',
    '                valueElement.textContent = `${sylZ > 0 ? "+" : ""}${sylZ}%`;',
    '              }',
    '            }',
    '          });',
    '        }, 1000);',
    '      }',
    '',
    '      // 历史净值',
    '      function fetchHistoryNetVal() {',
    '        document.getElementById("loading2").style.display = "block";',
    '        let actualRange = range2 === "1w" ? "y" : range2;',
    `        let url = "https://fundmobapi.eastmoney.com/FundMApi/FundNetDiagram.ashx?FCODE=${fund.code}&RANGE=" + actualRange + "&deviceid=Wap&plat=Wap&product=EFund&version=2.0.0&_=${new Date().getTime()}";`,
    '',
    '        let callbackName =',
    '          "jsonpCallback2_" +',
    '          new Date().getTime() +',
    '          Math.floor(Math.random() * 10000);',
    '',
    '        loadJSONP(url, callbackName)',
    '          .then((data) => {',
    '            document.getElementById("loading2").style.display = "none";',
    '            if (!data || !data.Datas || data.Datas.length === 0) {',
    '              chart2.clear();',
    '              chart2.setOption({',
    '                title: {',
    '                  text: "暂无净值数据",',
    '                  left: "center",',
    '                  top: "center",',
    '                  textStyle: {',
    '                    color: defaultTextColor,',
    '                    fontSize: 13,',
    '                    fontWeight: "normal",',
    '                  },',
    '                },',
    '              });',
    '              return;',
    '            }',
    '            let dataList = data.Datas;',
    '            if (range2 === "1w") {',
    '              dataList = dataList.slice(-5);',
    '              if (dataList.length === 0) {',
    '                chart2.clear();',
    '                chart2.setOption({',
    '                  title: {',
    '                    text: "暂无近一周数据",',
    '                    left: "center",',
    '                    top: "center",',
    '                    textStyle: {',
    '                      color: defaultTextColor,',
    '                      fontSize: 13,',
    '                      fontWeight: "normal",',
    '                    },',
    '                  },',
    '                });',
    '                return;',
    '              }',
    '            }',
    '            let dates = dataList.map((item) => item.FSRQ);',
    '            let dwjz = dataList.map((item) => +item.DWJZ);',
    '            let ljjz = dataList.map((item) => +item.LJJZ);',
    '            let jzzzl = dataList.map((item) => item.JZZZL);',
    '',
    '            let option = getCommonOption("历史净值");',
    '            option.legend.data = ["单位净值", "累计净值"];',
    '            option.xAxis.data = dates;',
    '',
    '            // Set more precise Y-axis label formatting to catch small nav value changes',
    '            option.yAxis.axisLabel.formatter = function (val) {',
    '              return val.toFixed(4); // Use 4 decimal degrees for accuracy',
    '            };',
    '',
    '            option.tooltip.formatter = function (params) {',
    '              let dataIndex = params[0].dataIndex;',
    '              let date = params[0].name;',
    '              let res = "时间: " + date + "<br/>";',
    '              params.forEach((p) => {',
    '                res +=',
    '                  p.marker +',
    '                  p.seriesName +',
    '                  ": " +',
    '                  Number(p.value).toFixed(4) +',
    '                  "<br/>";',
    '              });',
    '',
    '              let rate = jzzzl[dataIndex];',
    '              if (rate !== undefined && rate !== "" && rate !== null) {',
    '                let colorStr =',
    '                  Number(rate) > 0',
    '                    ? "#f56c6c"',
    '                    : Number(rate) < 0',
    '                      ? "#4eb61b"',
    '                      : defaultTextColor;',
    '                res +=',
    '                  \'<span style="display:inline-block;margin-right:4px;border-radius:10px;width:10px;height:10px;background-color:#909399;"></span>日增长率: <span style="color:\' +',
    '                  colorStr +',
    '                  \';font-weight:bold;">\' +',
    '                  rate +',
    '                  "%</span><br/>";',
    '              }',
    '              return res;',
    '            };',
    '            option.series = [',
    '              {',
    '                name: "单位净值",',
    '                type: "line",',
    '                data: dwjz,',
    '                showSymbol: false,',
    '                lineStyle: { color: "#409EFF" },',
    '              },',
    '              {',
    '                name: "累计净值",',
    '                type: "line",',
    '                data: ljjz,',
    '                showSymbol: false,',
    '                lineStyle: { color: "#E6A23C" },',
    '              },',
    '            ];',
    '            chart2.setOption(option);',
    '          })',
    '          .catch((e) => {',
    '            document.getElementById("loading2").style.display = "none";',
    '          });',
    '      }',
    '',
    '      // 历史累计收益率',
    '      function fetchHistoryYield() {',
    '        document.getElementById("loading3").style.display = "block";',
    '        let actualRange = range3 === "1w" ? "y" : range3;',
    `        let url = "https://dataapi.1234567.com.cn/dataapi/fund/FundVPageAcc?INDEXCODE=000300&CODE=${fund.code}&FCODE=${fund.code}&RANGE=" + actualRange + "&deviceid=Wap&product=EFund";`,
    '',
    '        fetch(url, {',
    '          headers: {',
    '            accept: "application/json, text/plain, */*",',
    '            "accept-language": "zh-CN,zh;q=0.9",',
    '          },',
    '        })',
    '          .then((r) => r.json())',
    '          .then((data) => {',
    '            document.getElementById("loading3").style.display = "none";',
    '            if (',
    '              !data ||',
    '              data.errorCode !== 0 ||',
    '              !data.data ||',
    '              data.data.length === 0',
    '            ) {',
    '              chart3.clear();',
    '              chart3.setOption({',
    '                title: {',
    '                  text: "暂无累计收益数据",',
    '                  left: "center",',
    '                  top: "center",',
    '                  textStyle: {',
    '                    color: defaultTextColor,',
    '                    fontSize: 13,',
    '                    fontWeight: "normal",',
    '                  },',
    '                },',
    '              });',
    '              return;',
    '            }',
    '            let dataList = data.data;',
    '            if (range3 === "1w") {',
    '              dataList = dataList.slice(-5);',
    '              if (dataList.length === 0) {',
    '                chart3.clear();',
    '                chart3.setOption({',
    '                  title: {',
    '                    text: "暂无近一周数据",',
    '                    left: "center",',
    '                    top: "center",',
    '                    textStyle: {',
    '                      color: defaultTextColor,',
    '                      fontSize: 13,',
    '                      fontWeight: "normal",',
    '                    },',
    '                  },',
    '                });',
    '                return;',
    '              }',
    '            }',
    '            let dates = dataList.map((item) => item.pdate);',
    '            let yieldData = dataList.map((item) => +(item.yield || 0));',
    '            let indexYieldData = dataList.map(',
    '              (item) => +(item.indexYield || 0),',
    '            );',
    '            let fundTypeYieldData = dataList.map(',
    '              (item) => +(item.fundTypeYield || 0),',
    '            );',
    '',
    '            let option = getCommonOption("历史累计收益率");',
    '            option.legend.data = ["涨幅", "沪深300", "同类平均"];',
    '            option.xAxis.data = dates;',
    '            option.yAxis.axisLabel.formatter = "{value}%";',
    '            option.tooltip.formatter = function (params) {',
    '              let date = params[0].name;',
    '              let res = "时间: " + date + "<br/>";',
    '              params.forEach((p) => {',
    '                res +=',
    '                  p.marker +',
    '                  p.seriesName +',
    '                  ": " +',
    '                  Number(p.value).toFixed(2) +',
    '                  "%<br/>";',
    '              });',
    '              return res;',
    '            };',
    '            option.series = [',
    '              {',
    '                name: "涨幅",',
    '                type: "line",',
    '                data: yieldData,',
    '                showSymbol: false,',
    '                lineStyle: { color: "#F56C6C" },',
    '              },',
    '              {',
    '                name: "沪深300",',
    '                type: "line",',
    '                data: indexYieldData,',
    '                showSymbol: false,',
    '                lineStyle: { color: "#67C23A" },',
    '              },',
    '              {',
    '                name: "同类平均",',
    '                type: "line",',
    '                data: fundTypeYieldData,',
    '                showSymbol: false,',
    '                lineStyle: { color: "#E6A23C" },',
    '              },',
    '            ];',
    '            chart3.setOption(option);',
    '          })',
    '          .catch((e) => {',
    '            document.getElementById("loading3").style.display = "none";',
    '            console.error(e);',
    '          });',
    '      }',
    '',
    '      fetchFundInfo();',
    '      fetchDetailedFundInfo();',
    '      fetchHistoryNetVal();',
    '      fetchHistoryYield();',
    '',
    '      // ==================== 持仓明细 ====================',
    '',
    '      let positionLoaded = false;',
    '',
    '      function fetchInvestmentPosition() {',
    '        if (positionLoaded) return;',
    '        positionLoaded = true;',
    '',
    '        const loadingEl = document.getElementById("loadingPosition");',
    '        const contentEl = document.getElementById("positionContent");',
    '        const emptyEl = document.getElementById("positionEmpty");',
    '',
    `        vscode.postMessage({ command: "fetchInvestmentPosition", fundCode: "${fund.code}" });`,
    '      }',
    '',
    '      // 监听 extension host 返回的持仓数据',
    '      window.addEventListener("message", function handlePositionMsg(event) {',
    '        const message = event.data;',
    '        if (message.command !== "investmentPositionData") return;',
    '',
    '        const loadingEl = document.getElementById("loadingPosition");',
    '        const contentEl = document.getElementById("positionContent");',
    '        const emptyEl = document.getElementById("positionEmpty");',
    '        const data = message.data;',
    '',
    '        if (loadingEl) loadingEl.style.display = "none";',
    '        if (!data || !data.Datas) {',
    '          if (emptyEl) emptyEl.style.display = "block";',
    '          if (contentEl) contentEl.style.display = "block";',
    '          return;',
    '        }',
    '',
    '        const datas = data.Datas;',
    '        const expansion = data.Expansion || "";',
    '',
    '        // 截止日期',
    '        const dateEl = document.getElementById("positionDate");',
    '        if (dateEl && expansion) dateEl.textContent = "截止日期：" + expansion;',
    '',
    '        // 解析股票持仓',
    '        const rawStocks = datas.fundStocks || [];',
    '        const stocks = rawStocks.map(s => ({',
    '          code: s.GPDM || "",',
    '          name: s.GPJC || "",',
    '          ratio: parseFloat(s.JZBL) || 0,',
    '          changeType: s.PCTNVCHGTYPE || "",',
    '          changeRatio: parseFloat(s.PCTNVCHG) || 0,',
    '          price: null,',
    '          changePercent: null,',
    '          newTexch: s.NEWTEXCH || "0",',
    '        }));',
    '',
    '        // 解析债券持仓',
    '        const rawBonds = datas.fundboods || [];',
    '        const bonds = rawBonds.map(b => ({',
    '          code: b.ZQDM || "",',
    '          name: b.ZQMC || "",',
    '          ratio: parseFloat(b.ZJZBL) || 0,',
    '        }));',
    '',
    '        if (stocks.length === 0 && bonds.length === 0) {',
    '          if (emptyEl) emptyEl.style.display = "block";',
    '          if (contentEl) contentEl.style.display = "block";',
    '          return;',
    '        }',
    '',
    '        // 渲染股票持仓',
    '        if (stocks.length > 0) {',
    '          const stockSection = document.getElementById("stockSection");',
    '          const stockTable = document.getElementById("stockTable");',
    '          if (stockSection) stockSection.style.display = "block";',
    '          if (stockTable) {',
    '            stockTable.innerHTML = renderStockTable(stocks);',
    '          }',
    '          // 异步拉取实时行情',
    '          fetchStockQuotes(stocks);',
    '        }',
    '',
    '        // 渲染债券持仓',
    '        if (bonds.length > 0) {',
    '          const bondSection = document.getElementById("bondSection");',
    '          const bondTable = document.getElementById("bondTable");',
    '          if (bondSection) bondSection.style.display = "block";',
    '          if (bondTable) {',
    '            bondTable.innerHTML = renderBondTable(bonds);',
    '          }',
    '        }',
    '',
    '        if (contentEl) contentEl.style.display = "block";',
    '      });',
    '',
    '      function renderStockTable(stocks) {',
    '        let html = \'<table class="position-table">\';',
    '        html += \'<thead><tr>\';',
    '        html += \'<th>股票名称（代码）</th>\';',
    '        html += \'<th>价格</th>\';',
    '        html += \'<th>涨跌幅</th>\';',
    '        html += \'<th>持仓占比</th>\';',
    '        html += \'<th>较上期</th>\';',
    '        html += \'</tr></thead><tbody>\';',
    '        stocks.forEach((s, i) => {',
    '          html += \'<tr data-stock-index="\' + i + \'">\';',
    '          html += \'<td><div class="position-stock-name">\' + s.name + \'</div><div class="position-stock-code">\' + s.code + \'</div></td>\';',
    '          html += \'<td class="stock-price-\' + i + \'">--</td>\';',
    '          html += \'<td class="stock-change-\' + i + \'">--</td>\';',
    '          html += \'<td>\' + s.ratio.toFixed(2) + \'%</td>\';',
    '          html += \'<td>\' + renderCompared(s) + \'</td>\';',
    '          html += \'</tr>\';',
    '        });',
    '        html += \'</tbody></table>\';',
    '        return html;',
    '      }',
    '',
    '      function renderBondTable(bonds) {',
    '        let html = \'<table class="position-table">\';',
    '        html += \'<thead><tr>\';',
    '        html += \'<th>债券名称（代码）</th>\';',
    '        html += \'<th>占净值比</th>\';',
    '        html += \'</tr></thead><tbody>\';',
    '        bonds.forEach(b => {',
    '          html += \'<tr>\';',
    '          html += \'<td><div class="position-stock-name">\' + b.name + \'</div><div class="position-stock-code">\' + b.code + \'</div></td>\';',
    '          html += \'<td>\' + b.ratio.toFixed(2) + \'%</td>\';',
    '          html += \'</tr>\';',
    '        });',
    '        html += \'</tbody></table>\';',
    '        return html;',
    '      }',
    '',
    '      function renderCompared(s) {',
    '        const type = s.changeType || "";',
    '        if (type === "新进" || type === "新增") {',
    '          return \'<span class="position-compared-new">新增</span>\';',
    '        }',
    '        const ratio = s.changeRatio;',
    '        if (!ratio && ratio !== 0) return \'<span class="position-compared-flat">--</span>\';',
    '        if (ratio > 0) return \'<span class="position-compared-up">↑\' + ratio.toFixed(2) + \'%</span>\';',
    '        if (ratio < 0) return \'<span class="position-compared-down">↓\' + Math.abs(ratio).toFixed(2) + \'%</span>\';',
    '        return \'<span class="position-compared-flat">不变</span>\';',
    '      }',
    '',
    '      function fetchStockQuotes(stocks) {',
    '        const secids = stocks.map(s => s.newTexch + "." + s.code).join(",");',
    '        const url = "https://push2.eastmoney.com/api/qt/ulist.np/get?fields=f2,f3&fltt=2&secids=" + encodeURIComponent(secids) + "&_=" + Date.now();',
    '        fetch(url)',
    '          .then(r => r.json())',
    '          .then(data => {',
    '            const diff = (data && data.data && data.data.diff) ? data.data.diff : [];',
    '            diff.forEach((q, i) => {',
    '              const priceEl = document.querySelector(".stock-price-" + i);',
    '              const changeEl = document.querySelector(".stock-change-" + i);',
    '              if (priceEl && typeof q.f2 === "number") {',
    '                priceEl.textContent = q.f2.toFixed(2);',
    '              }',
    '              if (changeEl && typeof q.f3 === "number") {',
    '                const pct = q.f3;',
    '                const cls = pct > 0 ? "position-up" : pct < 0 ? "position-down" : "position-flat";',
    '                const sign = pct > 0 ? "+" : "";',
    '                changeEl.innerHTML = \'<span class="\' + cls + \'">\' + sign + pct.toFixed(2) + \'%</span>\';',
    '              }',
    '            });',
    '          })',
    '          .catch(() => {});',
    '      }',
    '',
    '      // 切换到持仓明细 tab 时懒加载',
    '      document.querySelectorAll("[data-tab]").forEach(btn => {',
    '        btn.addEventListener("click", () => {',
    '          const tabName = btn.getAttribute("data-tab");',
    '          if (tabName === "position") {',
    '            fetchInvestmentPosition();',
    '          } else if (tabName === "feature") {',
    '            fetchFeatureData();',
    '          } else if (tabName === "deep") {',
    '            fetchDeepData();',
    '          }',
    '        });',
    '      });',
    '',
    '      // 如果初始 tab 就是 position，立即加载',
    `      if ("${activeTab}" === "position") {`,
    '        fetchInvestmentPosition();',
    '      }',
    `      if ("${activeTab}" === "feature") {`,
    '        fetchFeatureData();',
    '      }',
    `      if ("${activeTab}" === "deep") {`,
    '        fetchDeepData();',
    '      }',
    '',
    '      // 持仓概况始终加载关联板块（无论是否为初始tab）',
    '      fetchRelateTheme();',
    '',
    '      // ========== 特色数据相关 ==========',
    '',
    '      document.querySelectorAll("#featureRangeBtns button").forEach((btn) => {',
    '        btn.addEventListener("click", (e) => {',
    '          document.querySelectorAll("#featureRangeBtns button").forEach((b) => b.classList.remove("active"));',
    '          e.target.classList.add("active");',
    '          featureRange = e.target.getAttribute("data-value");',
    '          renderFeatureCards();',
    '        });',
    '      });',
    '',
    '      function fetchFeatureData() {',
    '        if (featureDataLoaded) return;',
    '        featureDataLoaded = true;',
    '',
    '        document.getElementById("loadingFeature").style.display = "block";',
    '        document.getElementById("featureContent").style.display = "none";',
    '        document.getElementById("featureEmpty").style.display = "none";',
    '',
    '        const url = "https://dgs.tiantianfunds.com/merge/m/api/jjxqy1_2";',
    '        const params = new URLSearchParams({',
    '          deviceid: generateUUID(),',
    '          version: "9.9.9",',
    '          appVersion: "6.5.5",',
    '          product: "EFund",',
    '          plat: "Web",',
    '          uid: "",',
    '          fcode: fundCode,',
    '          ISRG: "0",',
    '          indexfields: "_id,INDEXCODE,BKID,INDEXNAME,INDEXVALUA,NEWINDEXTEXCH,PEP100",',
    '          fields: "BENCH,ESTDIFF,INDEXNAME,LINKZSB,INDEXCODE,NEWTEXCH,FTYPE,FCODE,BAGTYPE,RISKLEVEL,TTYPENAME,ESTABDATE,JJGS,JJGSID,ENDNAV,SHORTNAME,TTYPE,FSRQ,DWJZ,LJJZ,SYL_1N,SYL_LN,SYL_Z,SOURCERATE,RATE",',
    '          fundUniqueInfo_fIELDS: "FCODE,STDDEV1,STDDEV_1NRANK,STDDEV_1NFSC,STDDEV3,STDDEV_3NRANK,STDDEV_3NFSC,STDDEV5,STDDEV_5NRANK,STDDEV_5NFSC,SHARP1,SHARP_1NRANK,SHARP_1NFSC,SHARP3,SHARP_3NRANK,SHARP_3NFSC,SHARP5,SHARP_5NRANK,SHARP_5NFSC,MAXRETRA1,MAXRETRA_1NRANK,MAXRETRA_1NFSC,MAXRETRA3,MAXRETRA_3NRANK,MAXRETRA_3NFSC,MAXRETRA5,MAXRETRA_5NRANK,MAXRETRA_5NFSC",',
    '          fundUniqueInfo_fLFIELDS: "FCODE,BUSINESSTYPE,BUSINESSTEXT,BUSINESSCODE,BUSINESSSUBTYPE,MARK",',
    '          cfhFundFInfo_fields: "INVESTMENTIDEAR,INVESTMENTIDEARIMG",',
    '          relateThemeFields: "FCODE,SEC_CODE,SEC_NAME,CORR_1Y,OL2TOP"',
    '        });',
    '',
    '        fetch(url, {',
    '          method: "POST",',
    '          headers: {',
    '            "Content-Type": "application/x-www-form-urlencoded",',
    '            Origin: "https://h5.1234567.com.cn",',
    '            Referer: "https://servicewechat.com/"',
    '          },',
    '          body: params.toString()',
    '        })',
    '        .then(r => r.json())',
    '        .then(data => {',
    '          document.getElementById("loadingFeature").style.display = "none";',
    '',
    '          if (data && data.data && data.data.uniqueInfo && data.data.uniqueInfo.length > 0) {',
    '            featureDataCache = data.data.uniqueInfo[0];',
    '            periodIncreaseListCache = data.data.FundPeriodIncrease || [];',
    '            document.getElementById("featureContent").style.display = "block";',
    '            renderFeatureCards();',
    '          } else {',
    '            document.getElementById("featureEmpty").style.display = "block";',
    '          }',
    '        })',
    '        .catch((err) => {',
    '          console.error("特色数据加载失败:", err);',
    '          document.getElementById("loadingFeature").style.display = "none";',
    '          document.getElementById("featureEmpty").style.display = "block";',
    '        });',
    '      }',
    '',
    '      function renderFeatureCards() {',
    '        if (!featureDataCache) return;',
    '',
    '        const fd = featureDataCache;',
    '        const range = featureRange;',
    '',
    '        const targetTitle = range.toUpperCase();',
    '        const found = periodIncreaseListCache.find(item => item.title === targetTitle);',
    '        const sc = found ? parseInt(found.sc) || 0 : 0;',
    '',
    '        let stddev, stddevRank, sharp, sharpRank, maxRetra, maxRetraRank;',
    '',
    '        if (range === "1n") {',
    '          stddev = fd.STDDEV1;',
    '          stddevRank = parseInt(fd.STDDEV_1NRANK) || 0;',
    '          sharp = fd.SHARP1;',
    '          sharpRank = parseInt(fd.SHARP_1NRANK) || 0;',
    '          maxRetra = fd.MAXRETRA1;',
    '          maxRetraRank = parseInt(fd.MAXRETRA_1NRANK) || 0;',
    '        } else if (range === "3n") {',
    '          stddev = fd.STDDEV3;',
    '          stddevRank = parseInt(fd.STDDEV_3NRANK) || 0;',
    '          sharp = fd.SHARP3;',
    '          sharpRank = parseInt(fd.SHARP_3NRANK) || 0;',
    '          maxRetra = fd.MAXRETRA3;',
    '          maxRetraRank = parseInt(fd.MAXRETRA_3NRANK) || 0;',
    '        } else if (range === "5n") {',
    '          stddev = fd.STDDEV5;',
    '          stddevRank = parseInt(fd.STDDEV_5NRANK) || 0;',
    '          sharp = fd.SHARP5;',
    '          sharpRank = parseInt(fd.SHARP_5NRANK) || 0;',
    '          maxRetra = fd.MAXRETRA5;',
    '          maxRetraRank = parseInt(fd.MAXRETRA_5NRANK) || 0;',
    '        }',
    '',
    '        const calcRatio = (rank, total) => {',
    '          if (!rank || !total) return null;',
    '          const ratio = ((total - rank) / total) * 100;',
    '          return Math.max(0, Math.min(100, ratio));',
    '        };',
    '',
    '        const stddevRatio = calcRatio(stddevRank, sc);',
    '        const sharpRatio = calcRatio(sharpRank, sc);',
    '        const maxRetraRatio = calcRatio(maxRetraRank, sc);',
    '',
    '        const stddevVal = typeof stddev === "number" ? stddev : (typeof stddev === "string" && stddev !== "" && stddev !== "--" ? parseFloat(stddev) : null);',
    '        const sharpVal = typeof sharp === "number" ? sharp : (typeof sharp === "string" && sharp !== "" && sharp !== "--" ? parseFloat(sharp) : null);',
    '        const maxRetraVal = typeof maxRetra === "number" ? maxRetra : (typeof maxRetra === "string" && maxRetra !== "" && maxRetra !== "--" ? parseFloat(maxRetra) : null);',
    '',
    '        let html = "";',
    '',
    '        html += \'<div class="feature-card">\';',
    '        html += \'  <div class="feature-card-header">\';',
    '        html += \'    <div class="feature-metric-info">\';',
    '        html += \'      <span class="feature-value">\' + (stddevVal != null ? stddevVal.toFixed(2) + "%" : "--") + \'</span>\';',
    '        html += \'      <span class="feature-label">移动率（波动率）</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="feature-rank-info">\';',
    '        if (stddevRatio != null) {',
    '          html += \'      <span class="feature-rank-desc">领先 <span class="highlight-text">\' + stddevRatio.toFixed(2) + \'%</span> 同类</span>\';',
    '        } else {',
    '          html += \'      <span class="feature-rank-desc">暂无排名</span>\';',
    '        }',
    '        html += \'    </div>\';',
    '        html += \'  </div>\';',
    '        html += \'  <div class="feature-progress-track stddev-track">\';',
    '        if (stddevRatio != null) {',
    '          html += \'    <div class="feature-progress-fill stddev-fill" style="width: \' + stddevRatio + \'%"></div>\';',
    '          html += \'    <div class="progress-indicator stddev-indicator" style="left: \' + stddevRatio + \'%"></div>\';',
    '        }',
    '        html += \'  </div>\';',
    '        html += \'</div>\';',
    '',
    '        html += \'<div class="feature-card">\';',
    '        html += \'  <div class="feature-card-header">\';',
    '        html += \'    <div class="feature-metric-info">\';',
    '        html += \'      <span class="feature-value">\' + (sharpVal != null ? sharpVal.toFixed(4) : "--") + \'</span>\';',
    '        html += \'      <span class="feature-label">夏普比率</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="feature-rank-info">\';',
    '        if (sharpRatio != null) {',
    '          html += \'      <span class="feature-rank-desc">领先 <span class="highlight-text">\' + sharpRatio.toFixed(2) + \'%</span> 同类</span>\';',
    '        } else {',
    '          html += \'      <span class="feature-rank-desc">暂无排名</span>\';',
    '        }',
    '        html += \'    </div>\';',
    '        html += \'  </div>\';',
    '        html += \'  <div class="feature-progress-track sharp-track">\';',
    '        if (sharpRatio != null) {',
    '          html += \'    <div class="feature-progress-fill sharp-fill" style="width: \' + sharpRatio + \'%"></div>\';',
    '          html += \'    <div class="progress-indicator sharp-indicator" style="left: \' + sharpRatio + \'%"></div>\';',
    '        }',
    '        html += \'  </div>\';',
    '        html += \'</div>\';',
    '',
    '        html += \'<div class="feature-card">\';',
    '        html += \'  <div class="feature-card-header">\';',
    '        html += \'    <div class="feature-metric-info">\';',
    '        html += \'      <span class="feature-value">\' + (maxRetraVal != null ? maxRetraVal.toFixed(2) + "%" : "--") + \'</span>\';',
    '        html += \'      <span class="feature-label">最大回撤</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="feature-rank-info">\';',
    '        if (maxRetraRatio != null) {',
    '          html += \'      <span class="feature-rank-desc">领先 <span class="highlight-text">\' + maxRetraRatio.toFixed(2) + \'%</span> 同类</span>\';',
    '        } else {',
    '          html += \'      <span class="feature-rank-desc">暂无排名</span>\';',
    '        }',
    '        html += \'    </div>\';',
    '        html += \'  </div>\';',
    '        html += \'  <div class="feature-progress-track maxretra-track">\';',
    '        if (maxRetraRatio != null) {',
    '          html += \'    <div class="feature-progress-fill maxretra-fill" style="width: \' + maxRetraRatio + \'%"></div>\';',
    '          html += \'    <div class="progress-indicator maxretra-indicator" style="left: \' + maxRetraRatio + \'%"></div>\';',
    '        }',
    '        html += \'  </div>\';',
    '        html += \'</div>\';',
    '',
    '        document.getElementById("featureCards").innerHTML = html;',
    '      }',
    '',
    '      // ========== 深度数据相关 ==========',
    '',
    '      function fetchDeepData() {',
    '        if (deepDataLoaded) return;',
    '        deepDataLoaded = true;',
    '',
    '        document.getElementById("loadingDeep").style.display = "block";',
    '        document.getElementById("deepContent").style.display = "none";',
    '        document.getElementById("deepEmpty").style.display = "none";',
    '',
    '        const script = document.createElement("script");',
    '        script.src = "https://fund.eastmoney.com/pingzhongdata/" + fundCode + ".js?_=" + Date.now();',
    '        script.async = true;',
    '',
    '        script.onload = () => {',
    '          document.getElementById("loadingDeep").style.display = "none";',
    '',
    '          if (window.Data_grandTotal || window.Data_fluctuationScale || window.Data_netWorthTrend) {',
    '            renderDeepData();',
    '            document.getElementById("deepContent").style.display = "block";',
    '          } else {',
    '            document.getElementById("deepEmpty").style.display = "block";',
    '          }',
    '',
    '          script.remove();',
    '        };',
    '',
    '        script.onerror = () => {',
    '          document.getElementById("loadingDeep").style.display = "none";',
    '          document.getElementById("deepEmpty").style.display = "block";',
    '          script.remove();',
    '        };',
    '',
    '        document.head.appendChild(script);',
    '      }',
    '',
    '      function formatTsDate(ts) {',
    '        const date = new Date(ts);',
    '        const year = date.getFullYear();',
    '        const month = String(date.getMonth() + 1).padStart(2, "0");',
    '        const day = String(date.getDate()).padStart(2, "0");',
    '        return year + "-" + month + "-" + day;',
    '      }',
    '',
    '      function renderDeepData() {',
    '        renderDeepBasicInfo();',
    '        setTimeout(() => {',
    '          renderGrandTotalChart();',
    '          renderRankChart();',
    '          renderFluctuationChart();',
    '          renderHolderChart();',
    '          renderAssetChart();',
    '          renderPerformanceChart();',
    '          renderBuySellChart();',
    '          renderSharePositionChart();',
    '          renderNetWorthTrendChart();',
    '          renderAcWorthTrendChart();',
    '          renderDeepManagers();',
    '          renderSameTypeRanking();',
    '          renderStockCodes();',
    '        }, 100);',
    '      }',
    '',
    '      function renderDeepBasicInfo() {',
    '        const info = {',
    '          sourceRate: window.fund_sourceRate || "--",',
    '          currentRate: window.fund_Rate || "--",',
    '          minPurchase: window.fund_minsg || "--",',
    '          stockCount: (window.stockCodes || []).length,',
    '          bondCount: (window.zqCodes || "").split(",").filter(Boolean).length,',
    '          year1: window.syl_1n || "--",',
    '          sixMonth: window.syl_6y || "--",',
    '          threeMonth: window.syl_3y || "--",',
    '          oneMonth: window.syl_1y || "--"',
    '        };',
    '',
    '        let html = "";',
    '',
    '        // 阶段收益率卡片',
    '        html += \'<div class="deep-info-section">\';',
    '        html += \'  <div class="deep-section-title">阶段收益率</div>\';',
    '        html += \'  <div class="deep-return-grid">\';',
    '        html += \'    <div class="deep-return-item">\';',
    '        html += \'      <span class="deep-return-label">近1月</span>\';',
    '        html += \'      <span class="deep-return-value">\' + info.oneMonth + (info.oneMonth !== "--" ? "%" : "") + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="deep-return-item">\';',
    '        html += \'      <span class="deep-return-label">近3月</span>\';',
    '        html += \'      <span class="deep-return-value">\' + info.threeMonth + (info.threeMonth !== "--" ? "%" : "") + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="deep-return-item">\';',
    '        html += \'      <span class="deep-return-label">近6月</span>\';',
    '        html += \'      <span class="deep-return-value">\' + info.sixMonth + (info.sixMonth !== "--" ? "%" : "") + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="deep-return-item">\';',
    '        html += \'      <span class="deep-return-label">近1年</span>\';',
    '        html += \'      <span class="deep-return-value">\' + info.year1 + (info.year1 !== "--" ? "%" : "") + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'  </div>\';',
    '        html += \'</div>\';',
    '',
    '        // 基本信息卡片',
    '        html += \'<div class="deep-info-section" style="margin-top: 10px;">\';',
    '        html += \'  <div class="deep-section-title">基本信息</div>\';',
    '        html += \'  <div class="deep-info-grid">\';',
    '        html += \'    <div class="deep-info-item">\';',
    '        html += \'      <span class="deep-info-label">原费率</span>\';',
    '        html += \'      <span class="deep-info-value">\' + info.sourceRate + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="deep-info-item">\';',
    '        html += \'      <span class="deep-info-label">现费率</span>\';',
    '        html += \'      <span class="deep-info-value">\' + info.currentRate + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="deep-info-item">\';',
    '        html += \'      <span class="deep-info-label">最小申购</span>\';',
    '        html += \'      <span class="deep-info-value">\' + info.minPurchase + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="deep-info-item">\';',
    '        html += \'      <span class="deep-info-label">股票持仓数</span>\';',
    '        html += \'      <span class="deep-info-value">\' + info.stockCount + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'    <div class="deep-info-item">\';',
    '        html += \'      <span class="deep-info-label">债券持仓数</span>\';',
    '        html += \'      <span class="deep-info-value">\' + info.bondCount + \'</span>\';',
    '        html += \'    </div>\';',
    '        html += \'  </div>\';',
    '        html += \'</div>\';',
    '',
    '        document.getElementById("deepBasicInfo").innerHTML = html;',
    '      }',
    '',
    '      function getDeepChartOption() {',
    '        return {',
    '          tooltip: { trigger: "axis" },',
    '          legend: { textStyle: { color: defaultTextColor } },',
    '          grid: { left: "3%", right: "3%", bottom: "10%", containLabel: true },',
    '          xAxis: {',
    '            type: "category",',
    '            boundaryGap: false,',
    '            data: [],',
    '            axisLabel: { color: defaultTextColor, rotate: 45 },',
    '            axisLine: { lineStyle: { color: defaultGridColor } }',
    '          },',
    '          yAxis: {',
    '            type: "value",',
    '            scale: true,',
    '            axisLabel: { color: defaultTextColor },',
    '            splitLine: { lineStyle: { color: defaultGridColor, type: "dashed" } }',
    '          },',
    '          series: []',
    '        };',
    '      }',
    '',
    '      function renderGrandTotalChart() {',
    '        const data = window.Data_grandTotal;',
    '        if (!data || !data.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("grandTotalChart"));',
    '        deepCharts.grandTotal = chart;',
    '',
    '        const categories = data[0].data.map(item => formatTsDate(item[0]));',
    '        const option = getDeepChartOption();',
    '        option.xAxis.data = categories;',
    '        option.yAxis.axisLabel.formatter = "{value}%";',
    '        option.legend.data = data.map(s => s.name);',
    '        option.series = data.map(series => ({',
    '          name: series.name,',
    '          type: "line",',
    '          smooth: true,',
    '          showSymbol: false,',
    '          data: series.data.map(item => item[1]),',
    '          lineStyle: { width: 2 }',
    '        }));',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderRankChart() {',
    '        const rankData = window.Data_rateInSimilarType;',
    '        const percentData = window.Data_rateInSimilarPersent;',
    '        if (!rankData || !rankData.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("rankChart"));',
    '        deepCharts.rank = chart;',
    '',
    '        const dates = rankData.map(item => formatTsDate(item.x));',
    '        const option = {',
    '          tooltip: { trigger: "axis" },',
    '          legend: { data: ["排名", "百分位"], textStyle: { color: defaultTextColor } },',
    '          grid: { left: "3%", right: "3%", bottom: "10%", containLabel: true },',
    '          xAxis: {',
    '            type: "category",',
    '            data: dates,',
    '            axisLabel: { color: defaultTextColor, rotate: 45 },',
    '            axisLine: { lineStyle: { color: defaultGridColor } }',
    '          },',
    '          yAxis: [',
    '            {',
    '              type: "value",',
    '              name: "排名",',
    '              inverse: true,',
    '              axisLabel: { color: defaultTextColor },',
    '              splitLine: { lineStyle: { color: defaultGridColor, type: "dashed" } }',
    '            },',
    '            {',
    '              type: "value",',
    '              name: "百分位(%)",',
    '              axisLabel: { formatter: "{value}%", color: defaultTextColor },',
    '              splitLine: { show: false }',
    '            }',
    '          ],',
    '          series: [',
    '            {',
    '              name: "排名",',
    '              type: "line",',
    '              data: rankData.map(item => item.y),',
    '              showSymbol: false,',
    '              lineStyle: { width: 2, color: "#5470c6" },',
    '              smooth: true',
    '            },',
    '            {',
    '              name: "百分位",',
    '              type: "line",',
    '              yAxisIndex: 1,',
    '              data: percentData ? percentData.map(item => item[1]) : [],',
    '              showSymbol: false,',
    '              lineStyle: { width: 2, color: "#ee6666" },',
    '              smooth: true',
    '            }',
    '          ]',
    '        };',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderFluctuationChart() {',
    '        const data = window.Data_fluctuationScale;',
    '        if (!data || !data.categories || !data.categories.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("fluctuationChart"));',
    '        deepCharts.fluctuation = chart;',
    '',
    '        const option = {',
    '          tooltip: { trigger: "axis" },',
    '          legend: { data: ["规模", "环比"], textStyle: { color: defaultTextColor } },',
    '          grid: { left: "3%", right: "3%", bottom: "10%", containLabel: true },',
    '          xAxis: {',
    '            type: "category",',
    '            data: data.categories,',
    '            axisLabel: { color: defaultTextColor, rotate: 45 },',
    '            axisLine: { lineStyle: { color: defaultGridColor } }',
    '          },',
    '          yAxis: [',
    '            {',
    '              type: "value",',
    '              name: "规模(亿)",',
    '              axisLabel: { color: defaultTextColor },',
    '              splitLine: { lineStyle: { color: defaultGridColor, type: "dashed" } }',
    '            },',
    '            {',
    '              type: "value",',
    '              name: "环比(%)",',
    '              axisLabel: { formatter: "{value}%", color: defaultTextColor },',
    '              splitLine: { show: false }',
    '            }',
    '          ],',
    '          series: [',
    '            {',
    '              name: "规模",',
    '              type: "bar",',
    '              data: data.series.map(item => item.y),',
    '              itemStyle: { color: "#5470c6" },',
    '              barMaxWidth: 40',
    '            },',
    '            {',
    '              name: "环比",',
    '              type: "line",',
    '              yAxisIndex: 1,',
    '              data: data.series.map(item => parseFloat(item.mom.replace("%", "")) || 0),',
    '              itemStyle: { color: "#ee6666" },',
    '              lineStyle: { width: 2 },',
    '              showSymbol: false,',
    '              smooth: true',
    '            }',
    '          ]',
    '        };',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderHolderChart() {',
    '        const data = window.Data_holderStructure;',
    '        if (!data || !data.categories || !data.categories.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("holderChart"));',
    '        deepCharts.holder = chart;',
    '',
    '        const option = {',
    '          tooltip: { trigger: "axis" },',
    '          legend: { data: data.series.map(s => s.name), textStyle: { color: defaultTextColor } },',
    '          grid: { left: "3%", right: "3%", bottom: "10%", containLabel: true },',
    '          xAxis: {',
    '            type: "category",',
    '            data: data.categories,',
    '            axisLabel: { color: defaultTextColor, rotate: 45 },',
    '            axisLine: { lineStyle: { color: defaultGridColor } }',
    '          },',
    '          yAxis: {',
    '            type: "value",',
    '            axisLabel: { formatter: "{value}%", color: defaultTextColor },',
    '            splitLine: { lineStyle: { color: defaultGridColor, type: "dashed" } }',
    '          },',
    '          series: data.series.map((item, index) => ({',
    '            name: item.name,',
    '            type: "bar",',
    '            stack: "holder",',
    '            data: item.data,',
    '            itemStyle: { color: ["#5470c6", "#91cc75", "#fac858"][index] },',
    '            barMaxWidth: 40',
    '          }))',
    '        };',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderAssetChart() {',
    '        const data = window.Data_assetAllocation;',
    '        if (!data || !data.categories || !data.categories.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("assetChart"));',
    '        deepCharts.asset = chart;',
    '',
    '        const option = {',
    '          tooltip: { trigger: "axis" },',
    '          legend: { data: data.series.map(s => s.name), textStyle: { color: defaultTextColor } },',
    '          grid: { left: "3%", right: "3%", bottom: "10%", containLabel: true },',
    '          xAxis: {',
    '            type: "category",',
    '            data: data.categories,',
    '            axisLabel: { color: defaultTextColor, rotate: 45 },',
    '            axisLine: { lineStyle: { color: defaultGridColor } }',
    '          },',
    '          yAxis: [',
    '            {',
    '              type: "value",',
    '              axisLabel: { formatter: "{value}%", color: defaultTextColor },',
    '              splitLine: { lineStyle: { color: defaultGridColor, type: "dashed" } }',
    '            },',
    '            {',
    '              type: "value",',
    '              axisLabel: { color: defaultTextColor },',
    '              splitLine: { show: false }',
    '            }',
    '          ],',
    '          series: data.series.map(item => ({',
    '            name: item.name,',
    '            type: item.type === "line" ? "line" : "bar",',
    '            yAxisIndex: item.yAxis || 0,',
    '            smooth: item.type === "line",',
    '            showSymbol: item.type === "line" ? false : true,',
    '            data: item.data,',
    '            lineStyle: item.type === "line" ? { width: 2 } : undefined,',
    '            barMaxWidth: 40',
    '          }))',
    '        };',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderPerformanceChart() {',
    '        const data = window.Data_performanceEvaluation;',
    '        if (!data || !data.categories || !data.categories.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("performanceChart"));',
    '        deepCharts.performance = chart;',
    '',
    '        const option = {',
    '          tooltip: { trigger: "item" },',
    '          radar: {',
    '            indicator: data.categories.map(name => ({ name, max: 100 })),',
    '            splitArea: {',
    '              areaStyle: {',
    '                color: isDark ? ["rgba(255,255,255,0.02)", "rgba(255,255,255,0.04)"] : ["rgba(0,0,0,0.02)", "rgba(0,0,0,0.04)"]',
    '              }',
    '            },',
    '            axisName: { color: defaultTextColor },',
    '            splitLine: { lineStyle: { color: defaultGridColor } },',
    '            axisLine: { lineStyle: { color: defaultGridColor } },',
    '            center: ["50%", "55%"],',
    '            radius: "65%"',
    '          },',
    '          series: [{',
    '            name: "业绩评价",',
    '            type: "radar",',
    '            data: [{',
    '              value: data.data,',
    '              name: "平均 " + (data.avr || ""),',
    '              areaStyle: { color: "rgba(84, 112, 198, 0.3)" },',
    '              lineStyle: { color: "#5470c6", width: 2 },',
    '              itemStyle: { color: "#5470c6" }',
    '            }]',
    '          }]',
    '        };',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderBuySellChart() {',
    '        const data = window.Data_buySedemption;',
    '        if (!data || !data.categories || !data.categories.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("buySellChart"));',
    '        deepCharts.buySell = chart;',
    '',
    '        const option = {',
    '          tooltip: { trigger: "axis" },',
    '          legend: { data: data.series.map(s => s.name), textStyle: { color: defaultTextColor } },',
    '          grid: { left: "3%", right: "3%", bottom: "10%", containLabel: true },',
    '          xAxis: {',
    '            type: "category",',
    '            data: data.categories,',
    '            axisLabel: { color: defaultTextColor, rotate: 45 },',
    '            axisLine: { lineStyle: { color: defaultGridColor } }',
    '          },',
    '          yAxis: {',
    '            type: "value",',
    '            axisLabel: { color: defaultTextColor },',
    '            splitLine: { lineStyle: { color: defaultGridColor, type: "dashed" } }',
    '          },',
    '          series: data.series.map((item, index) => ({',
    '            name: item.name,',
    '            type: index === 2 ? "line" : "bar",',
    '            smooth: index === 2,',
    '            data: item.data,',
    '            itemStyle: { color: ["#5470c6", "#ee6666", "#91cc75"][index] },',
    '            lineStyle: index === 2 ? { width: 2 } : undefined,',
    '            showSymbol: index === 2 ? false : true,',
    '            barMaxWidth: 40',
    '          }))',
    '        };',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderSharePositionChart() {',
    '        const data = window.Data_fundSharesPositions;',
    '        if (!data || !data.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("sharePositionChart"));',
    '        deepCharts.sharePosition = chart;',
    '',
    '        const option = getDeepChartOption();',
    '        option.xAxis.data = data.map(item => formatTsDate(item[0]));',
    '        option.yAxis.axisLabel.formatter = "{value}%";',
    '        option.series = [{',
    '          name: "股票仓位",',
    '          type: "line",',
    '          data: data.map(item => item[1]),',
    '          showSymbol: false,',
    '          smooth: true,',
    '          lineStyle: { width: 2, color: "#5470c6" },',
    '          areaStyle: { color: "rgba(84, 112, 198, 0.3)" }',
    '        }];',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderNetWorthTrendChart() {',
    '        const data = window.Data_netWorthTrend;',
    '        if (!data || !data.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("netWorthTrendChart"));',
    '        deepCharts.netWorthTrend = chart;',
    '',
    '        const option = getDeepChartOption();',
    '        option.xAxis.data = data.map(item => formatTsDate(item.x));',
    '        option.series = [{',
    '          name: "单位净值",',
    '          type: "line",',
    '          data: data.map(item => item.y),',
    '          showSymbol: false,',
    '          smooth: true,',
    '          lineStyle: { width: 2, color: "#91cc75" },',
    '          areaStyle: { color: "rgba(145, 204, 117, 0.3)" }',
    '        }];',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderAcWorthTrendChart() {',
    '        const data = window.Data_ACWorthTrend;',
    '        if (!data || !data.length) return;',
    '',
    '        const chart = echarts.init(document.getElementById("acWorthTrendChart"));',
    '        deepCharts.acWorthTrend = chart;',
    '',
    '        const option = getDeepChartOption();',
    '        option.xAxis.data = data.map(item => formatTsDate(item[0]));',
    '        option.series = [{',
    '          name: "累计净值",',
    '          type: "line",',
    '          data: data.map(item => item[1]),',
    '          showSymbol: false,',
    '          smooth: true,',
    '          lineStyle: { width: 2, color: "#fac858" },',
    '          areaStyle: { color: "rgba(250, 200, 88, 0.3)" }',
    '        }];',
    '',
    '        chart.setOption(option);',
    '      }',
    '',
    '      function renderDeepManagers() {',
    '        const managers = window.Data_currentFundManager;',
    '        if (!managers || !managers.length) return;',
    '',
    '        let html = "";',
    '        managers.forEach(m => {',
    '          html += \'<div class="deep-manager-card">\';',
    '          html += \'  <div class="deep-manager-header">\';',
    '          if (m.pic) {',
    '            html += \'    <img class="deep-manager-avatar" src="\' + m.pic + \'" alt="\' + (m.name || "") + \'" referrerpolicy="no-referrer" />\';',
    '          }',
    '          html += \'    <div class="deep-manager-info">\';',
    '          html += \'      <div class="deep-manager-name">\' + (m.name || "--") + \'</div>\';',
    '          html += \'      <div class="deep-manager-meta">\';',
    '          if (m.workTime) html += \'        <span>\' + m.workTime + \'</span>\';',
    '          if (m.fundSize) html += \'        <span>\' + m.fundSize + \'</span>\';',
    '          if (m.star) html += \'        <span>星级 \' + m.star + \'</span>\';',
    '          html += \'      </div>\';',
    '          html += \'    </div>\';',
    '          html += \'  </div>\';',
    '          html += \'  <div class="deep-manager-stats">\';',
    '          html += \'    <div class="deep-manager-stat">\';',
    '          html += \'      <div class="stat-label">能力评分</div>\';',
    '          html += \'      <div class="stat-value">\' + (m.power && m.power.avr ? m.power.avr : "--") + \'</div>\';',
    '          html += \'    </div>\';',
    '          html += \'    <div class="deep-manager-stat">\';',
    '          html += \'      <div class="stat-label">任期收益</div>\';',
    '          const profitVal = m.profit && m.profit.series && m.profit.series[0] && m.profit.series[0].data && m.profit.series[0].data[0] && m.profit.series[0].data[0].y;',
    '          html += \'      <div class="stat-value">\' + (profitVal != null ? profitVal.toFixed(2) + "%" : "--") + \'</div>\';',
    '          html += \'    </div>\';',
    '          html += \'  </div>\';',
    '          html += \'</div>\';',
    '        });',
    '',
    '        document.getElementById("deepManagers").innerHTML = html;',
    '        document.getElementById("deepManagersSection").style.display = "block";',
    '      }',
    '',
    '      function parseSameTypeEntry(entry) {',
    '        const parts = String(entry).split("_");',
    '        const code = parts[0] || "";',
    '        const rate = parts.length > 1 ? (parts[parts.length - 1] || "") : "";',
    '        const name = parts.length > 2 ? parts.slice(1, -1).join("_") : (parts[1] || "");',
    '        return { code, name, rate };',
    '      }',
    '',
    '      function renderSameTypeRanking() {',
    '        const sameType = window.swithSameType;',
    '        if (!sameType || !sameType.length) return;',
    '',
    '        const groups = sameType',
    '          .map(group => group',
    '            .map(entry => parseSameTypeEntry(entry))',
    '            .filter(item => item.code || item.name || item.rate)',
    '          )',
    '          .filter(group => group.length > 0);',
    '',
    '        if (!groups.length) return;',
    '',
    '        let html = "";',
    '        groups.forEach((group, groupIndex) => {',
    '          html += \'<div class="deep-same-type-group">\';',
    '          html += \'  <div class="deep-same-type-header">第 \' + (groupIndex + 1) + \' 组</div>\';',
    '          html += \'  <div class="deep-same-type-items">\';',
    '          group.forEach(item => {',
    '            const rateNum = parseFloat(item.rate);',
    '            const rateClass = rateNum > 0 ? "positive" : (rateNum < 0 ? "negative" : "");',
    '            html += \'    <div class="deep-same-type-item">\';',
    '            html += \'      <div class="deep-same-type-name">\';',
    '            html += \'        <span>\' + item.code + \'</span>\';',
    '            html += \'        <span>\' + item.name + \'</span>\';',
    '            html += \'      </div>\';',
    '            html += \'      <span class="deep-same-type-rate \' + rateClass + \'">\' + item.rate + \'%</span>\';',
    '            html += \'    </div>\';',
    '          });',
    '          html += \'  </div>\';',
    '          html += \'</div>\';',
    '        });',
    '',
    '        document.getElementById("deepSameType").innerHTML = html;',
    '        document.getElementById("deepSameTypeSection").style.display = "block";',
    '      }',
    '',
    '      function renderStockCodes() {',
    '        const stockCodes = window.stockCodes || [];',
    '        const stockCodesNew = window.stockCodesNew || [];',
    '        const bondCodes = typeof window.zqCodes === "string" ? window.zqCodes.split(",").filter(Boolean) : [];',
    '        const bondCodesNew = typeof window.zqCodesNew === "string" ? window.zqCodesNew.split(",").filter(Boolean) : [];',
    '',
    '        let hasAnyCodes = false;',
    '',
    '        if (stockCodes.length > 0) {',
    '          let html = "";',
    '          stockCodes.forEach(code => {',
    '            html += \'<span class="deep-code-chip">\' + code + \'</span>\';',
    '          });',
    '          document.getElementById("deepStockCodesList").innerHTML = html;',
    '          document.getElementById("deepStockCodes").style.display = "block";',
    '          hasAnyCodes = true;',
    '        }',
    '',
    '        if (stockCodesNew.length > 0) {',
    '          let html = "";',
    '          stockCodesNew.forEach(code => {',
    '            html += \'<span class="deep-code-chip">\' + code + \'</span>\';',
    '          });',
    '          document.getElementById("deepStockCodesNewList").innerHTML = html;',
    '          document.getElementById("deepStockCodesNew").style.display = "block";',
    '          hasAnyCodes = true;',
    '        }',
    '',
    '        if (bondCodes.length > 0) {',
    '          let html = "";',
    '          bondCodes.forEach(code => {',
    '            html += \'<span class="deep-code-chip">\' + code + \'</span>\';',
    '          });',
    '          document.getElementById("deepBondCodesList").innerHTML = html;',
    '          document.getElementById("deepBondCodes").style.display = "block";',
    '          hasAnyCodes = true;',
    '        }',
    '',
    '        if (bondCodesNew.length > 0) {',
    '          let html = "";',
    '          bondCodesNew.forEach(code => {',
    '            html += \'<span class="deep-code-chip">\' + code + \'</span>\';',
    '          });',
    '          document.getElementById("deepBondCodesNewList").innerHTML = html;',
    '          document.getElementById("deepBondCodesNew").style.display = "block";',
    '          hasAnyCodes = true;',
    '        }',
    '',
    '        if (hasAnyCodes) {',
    '          document.getElementById("deepCodesSection").style.display = "block";',
    '        }',
    '      }',
    '',
    '      window.addEventListener("resize", () => {',
    '        chart2.resize();',
    '        chart3.resize();',
    '        Object.values(deepCharts).forEach(chart => {',
    '          if (chart && chart.resize) chart.resize();',
    '        });',
    '      });',
    '',
    '      // ========== 获取关联板块（用于持仓概况） ==========',
    '      function fetchRelateTheme() {',
    '        const url = "https://dgs.tiantianfunds.com/merge/m/api/jjxqy1_2";',
    '        const params = new URLSearchParams({',
    '          deviceid: generateUUID(),',
    '          version: "9.9.9",',
    '          appVersion: "6.5.5",',
    '          product: "EFund",',
    '          plat: "Web",',
    '          uid: "",',
    '          fcode: fundCode,',
    '          ISRG: "0",',
    '          indexfields: "_id,INDEXCODE,BKID,INDEXNAME",',
    '          fields: "INDEXNAME,INDEXCODE,FCODE,TTYPENAME",',
    '          fundUniqueInfo_fIELDS: "FCODE",',
    '          fundUniqueInfo_fLFIELDS: "FCODE",',
    '          cfhFundFInfo_fields: "INVESTMENTIDEAR,INVESTMENTIDEARIMG",',
    '          relateThemeFields: "FCODE,SEC_CODE,SEC_NAME,CORR_1Y,OL2TOP"',
    '        });',
    '',
    '        fetch(url, {',
    '          method: "POST",',
    '          headers: {',
    '            "Content-Type": "application/x-www-form-urlencoded",',
    '            Origin: "https://h5.1234567.com.cn",',
    '            Referer: "https://servicewechat.com/"',
    '          },',
    '          body: params.toString()',
    '        })',
    '        .then(r => r.json())',
    '        .then(data => {',
    '          if (data && data.data && data.data.fundRelateTheme && data.data.fundRelateTheme.length > 0) {',
    '            const themes = data.data.fundRelateTheme.filter(t => t.FCODE === fundCode);',
    '            if (themes.length > 0) {',
    '              const topTheme = themes.sort((a, b) => (b.CORR_1Y || 0) - (a.CORR_1Y || 0))[0];',
    '              const themeEl = document.getElementById("relateThemeValue");',
    '              if (themeEl) {',
    '                themeEl.textContent = topTheme.SEC_NAME || "--";',
    '              }',
    '            }',
    '          }',
    '        })',
    '        .catch(() => {});',
    '      }',
    '',
    '      syncTabState(activeTab);',
  ]
}