export function getStyles(): string[] {
  return [
    'body {',
    '  font-family: var(--vscode-font-family), sans-serif;',
    '  color: var(--vscode-editor-foreground);',
    '  background-color: var(--vscode-editor-background);',
    '  padding: 16px;',
    '  margin: 0;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 14px;',
    '}',
    '.header, .tabs, .tab-panel {',
    '  max-width: 1200px;',
    '  width: 100%;',
    '  margin: 0 auto;',
    '  box-sizing: border-box;',
    '}',
    'h1 {',
    '  font-size: 1.1rem;',
    '  font-weight: 600;',
    '  margin: 0;',
    '}',
    'h2 {',
    '  margin-top: 0;',
    '  margin-bottom: 5px;',
    '  font-size: 1rem;',
    '  word-break: break-all;',
    '}',
    'h3 {',
    '  margin-top: 0;',
    '  margin-bottom: 12px;',
    '  font-size: 1rem;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.header {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '  padding-bottom: 12px;',
    '  gap: 10px;',
    '}',
    '.refresh-btn {',
    '  padding: 4px 12px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  font-size: .82em;',
    '  font-family: inherit;',
    '  transition: background .2s;',
    '  white-space: nowrap;',
    '}',
    '.refresh-btn:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.tabs {',
    '  display: flex;',
    '  gap: 2px;',
    '  overflow-x: auto;',
    '  overflow-y: hidden;',
    '  scrollbar-width: none;',
    '  position: relative;',
    '  padding-bottom: 2px;',
    '}',
    '.tabs::-webkit-scrollbar {',
    '  display: none;',
    '}',
    '.tabs::before {',
    '  content: "";',
    '  position: absolute;',
    '  bottom: 0;',
    '  width: max(100%, 530px);',
    '  height: 1px;',
    '  background: var(--vscode-panel-border);',
    '}',
    '.tab-btn {',
    '  padding: 6px 14px;',
    '  background: transparent;',
    '  border: none;',
    '  border-bottom: 3px solid transparent;',
    '  color: var(--vscode-descriptionForeground);',
    '  cursor: pointer;',
    '  font-size: .82rem;',
    '  font-family: inherit;',
    '  transition: all .2s;',
    '  margin-bottom: -2px;',
    '  border-radius: 4px 4px 0 0;',
    '  white-space: nowrap;',
    '}',
    '.tab-btn:hover {',
    '  color: var(--vscode-editor-foreground);',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '.tab-btn.active {',
    '  color: var(--vscode-editor-foreground);',
    '  border-bottom-color: var(--vscode-focusBorder);',
    '  font-weight: 600;',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '.tab-panel {',
    '  display: none;',
    '  box-sizing: border-box;',
    '}',
    '.tab-panel.active {',
    '  display: block;',
    '}',
    '.card {',
    '  background-color: var(--vscode-editorWidget-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  padding: 14px;',
    '  position: relative;',
    '  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08);',
    '}',
    '.chart-container {',
    '  width: 100%;',
    '  min-height: 300px;',
    '  margin-top: 10px;',
    '}',
    '.controls {',
    '  display: flex;',
    '  gap: 8px;',
    '  margin-bottom: 10px;',
    '  flex-wrap: wrap;',
    '}',
    '',
    '.btn-group {',
    '  display: flex;',
    '  gap: 5px;',
    '  flex-wrap: wrap;',
    '}',
    '.btn-group button {',
    '  background-color: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  padding: 5px 10px;',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  outline: none;',
    '  transition: all 0.2s;',
    '  white-space: nowrap;',
    '  font-size: 0.8em;',
    '}',
    '.btn-group button:hover {',
    '  background-color: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.btn-group button.active {',
    '  background-color: var(--vscode-button-background);',
    '  color: var(--vscode-button-foreground);',
    '  border-color: var(--vscode-button-background);',
    '}',
    '',
    '.loading {',
    '  position: absolute;',
    '  top: 50%;',
    '  left: 50%;',
    '  transform: translate(-50%, -50%);',
    '  font-size: 14px;',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '',
    '.info-grid {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));',
    '  gap: 12px;',
    '}',
    '.info-item {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 4px;',
    '  padding: 10px;',
    '  background: var(--vscode-editor-background);',
    '  border-radius: 6px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '}',
    '.info-item:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08);',
    '  transform: translateY(-1px);',
    '}',
    '.info-label {',
    '  font-size: 0.85em;',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '.info-value {',
    '  font-size: 1.05em;',
    '  font-weight: 500;',
    '}',
    '.info-value.up {',
    '  color: #f56c6c;',
    '}',
    '.info-value.down {',
    '  color: #4eb61b;',
    '}',
    '@media (max-width: 800px) {',
    '  body {',
    '    padding: 12px;',
    '    gap: 12px;',
    '  }',
    '  .header {',
    '    gap: 8px;',
    '    padding-bottom: 10px;',
    '  }',
    '  h2 {',
    '    flex: 0 1 100%;',
    '    font-size: 0.95rem;',
    '  }',
    '  .refresh-btn {',
    '    padding: 4px 10px;',
    '    font-size: .75em;',
    '  }',
    '  .card {',
    '    padding: 12px;',
    '    border-radius: 6px;',
    '  }',
    '  .chart-container {',
    '    height: 250px;',
    '    margin-top: 8px;',
    '  }',
    '  h3 {',
    '    font-size: 0.95rem;',
    '    margin-bottom: 10px;',
    '  }',
    '  .info-grid {',
    '    grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));',
    '    gap: 10px;',
    '  }',
    '  .info-item {',
    '    padding: 8px;',
    '    gap: 3px;',
    '  }',
    '  .info-label {',
    '    font-size: 0.75em;',
    '  }',
    '  .info-value {',
    '    font-size: 0.9em;',
    '  }',
    '  .controls {',
    '    flex-direction: column;',
    '    align-items: stretch;',
    '    gap: 8px;',
    '  }',
    '  .btn-group {',
    '    gap: 4px;',
    '  }',
    '  .btn-group button {',
    '    padding: 5px 10px;',
    '    font-size: 0.75em;',
    '  }',
    '  .manager-card {',
    '    flex-direction: column;',
    '    gap: 12px;',
    '    padding: 12px;',
    '    align-items: center;',
    '    text-align: center;',
    '  }',
    '  .manager-avatar {',
    '    width: 70px;',
    '    height: 70px;',
    '    border-width: 2px;',
    '  }',
    '  .manager-details {',
    '    gap: 10px;',
    '    align-items: center;',
    '  }',
    '  .manager-name {',
    '    font-size: 1.05em;',
    '  }',
    '  .manager-tag {',
    '    font-size: 0.75em;',
    '    padding: 3px 10px;',
    '    margin-right: 4px;',
    '  }',
    '  .manager-stats {',
    '    grid-template-columns: repeat(2, 1fr);',
    '    gap: 8px;',
    '    margin-top: 2px;',
    '  }',
    '  .manager-stat {',
    '    padding: 10px;',
    '  }',
    '  .manager-stat-label {',
    '    font-size: 0.75em;',
    '    margin-bottom: 4px;',
    '  }',
    '  .manager-stat-value {',
    '    font-size: 0.95em;',
    '  }',
    '  .manager-resume {',
    '    max-height: 120px;',
    '    font-size: 0.85em;',
    '    padding: 10px;',
    '  }',
    '  .theme-info {',
    '    gap: 8px;',
    '  }',
    '  .theme-tag {',
    '    padding: 8px 12px;',
    '    font-size: 0.8em;',
    '    gap: 6px;',
    '  }',
    '  .tab-btn {',
    '    padding: 5px 12px;',
    '    font-size: 0.75rem;',
    '  }',
    '}',
    '@media (max-width: 600px) {',
    '  body {',
    '    padding: 8px;',
    '    gap: 10px;',
    '  }',
    '  .header {',
    '    padding-bottom: 8px;',
    '    gap: 6px;',
    '  }',
    '  h1 {',
    '    font-size: 1rem;',
    '  }',
    '  h2 {',
    '    font-size: 0.85rem;',
    '  }',
    '  h3 {',
    '    font-size: 0.85rem;',
    '    margin-bottom: 8px;',
    '  }',
    '  .refresh-btn {',
    '    padding: 3px 8px;',
    '    font-size: .7em;',
    '  }',
    '  .card {',
    '    padding: 10px;',
    '    border-radius: 5px;',
    '    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08);',
    '  }',
    '  .chart-container {',
    '    height: 200px;',
    '    margin-top: 6px;',
    '  }',
    '  .info-grid {',
    '    grid-template-columns: repeat(2, 1fr);',
    '    gap: 8px;',
    '  }',
    '  .info-item {',
    '    padding: 6px;',
    '    gap: 2px;',
    '  }',
    '  .info-label {',
    '    font-size: 0.7em;',
    '  }',
    '  .info-value {',
    '    font-size: 0.8em;',
    '  }',
    '  .controls {',
    '    flex-direction: column;',
    '    align-items: stretch;',
    '    gap: 6px;',
    '  }',
    '  .btn-group {',
    '    gap: 3px;',
    '  }',
    '  .btn-group button {',
    '    padding: 4px 8px;',
    '    font-size: 0.65em;',
    '    flex: 1;',
    '  }',
    '  .tab-btn {',
    '    padding: 4px 8px;',
    '    font-size: 0.7rem;',
    '  }',
    '  .tabs::before {',
    '    width: max(100%, 300px);',
    '  }',
    '  .manager-card {',
    '    padding: 10px;',
    '    gap: 10px;',
    '  }',
    '  .manager-avatar {',
    '    width: 60px;',
    '    height: 60px;',
    '    border-width: 2px;',
    '  }',
    '  .manager-name {',
    '    font-size: 0.95em;',
    '  }',
    '  .manager-tag {',
    '    font-size: 0.65em;',
    '    padding: 2px 8px;',
    '    margin-right: 2px;',
    '  }',
    '  .manager-stats {',
    '    grid-template-columns: 1fr 1fr;',
    '    gap: 6px;',
    '  }',
    '  .manager-stat {',
    '    padding: 8px;',
    '  }',
    '  .manager-stat-label {',
    '    font-size: 0.65em;',
    '  }',
    '  .manager-stat-value {',
    '    font-size: 0.85em;',
    '  }',
    '  .manager-resume {',
    '    max-height: 100px;',
    '    font-size: 0.75em;',
    '    line-height: 1.4;',
    '    padding: 8px;',
    '  }',
    '  .theme-info {',
    '    gap: 6px;',
    '  }',
    '  .theme-tag {',
    '    padding: 6px 10px;',
    '    font-size: 0.7em;',
    '    gap: 4px;',
    '  }',
    '  .theme-corr {',
    '    font-size: 0.7em;',
    '    padding: 2px 6px;',
    '  }',
    '}',
    '',
    '.manager-info {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 15px;',
    '}',
    '.manager-card {',
    '  display: flex;',
    '  gap: 16px;',
    '  padding: 14px;',
    '  background: var(--vscode-editor-background);',
    '  border-radius: 8px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  transition: all 0.2s ease;',
    '}',
    '.manager-card:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);',
    '}',
    '.manager-avatar {',
    '  width: 80px;',
    '  height: 80px;',
    '  border-radius: 50%;',
    '  object-fit: cover;',
    '  background: linear-gradient(',
    '    135deg,',
    '    var(--vscode-button-secondaryBackground) 0%,',
    '    var(--vscode-button-background) 100%',
    '  );',
    '  border: 3px solid var(--vscode-panel-border);',
    '  flex-shrink: 0;',
    '}',
    '.manager-details {',
    '  flex: 1;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 12px;',
    '}',
    '.manager-name {',
    '  font-size: 1.2em;',
    '  font-weight: 600;',
    '  color: var(--vscode-editor-foreground);',
    '  margin-bottom: 4px;',
    '}',
    '.manager-tag {',
    '  display: inline-block;',
    '  padding: 4px 12px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border-radius: 16px;',
    '  font-size: 0.85em;',
    '  margin-right: 8px;',
    '  font-weight: 500;',
    '  transition: all 0.2s ease;',
    '}',
    '.manager-tag:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.manager-stats {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));',
    '  gap: 12px;',
    '  margin-top: 4px;',
    '}',
    '.manager-stat {',
    '  text-align: center;',
    '  padding: 12px;',
    '  background: var(--vscode-editorWidget-background);',
    '  border-radius: 8px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  transition: all 0.2s ease;',
    '}',
    '.manager-stat:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  transform: translateY(-2px);',
    '}',
    '.manager-stat-label {',
    '  font-size: 0.85em;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-bottom: 6px;',
    '  font-weight: 500;',
    '}',
    '.manager-stat-value {',
    '  font-size: 1.1em;',
    '  font-weight: 600;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.manager-resume {',
    '  margin-top: 8px;',
    '  padding: 14px;',
    '  background: var(--vscode-editorWidget-background);',
    '  border-radius: 8px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  font-size: 0.9em;',
    '  line-height: 1.6;',
    '  color: var(--vscode-editor-foreground);',
    '  max-height: 150px;',
    '  overflow-y: auto;',
    '}',
    '.manager-resume::-webkit-scrollbar {',
    '  width: 6px;',
    '}',
    '.manager-resume::-webkit-scrollbar-thumb {',
    '  background: var(--vscode-scrollbarSlider-background);',
    '  border-radius: 3px;',
    '}',
    '.manager-resume::-webkit-scrollbar-thumb:hover {',
    '  background: var(--vscode-scrollbarSlider-hoverBackground);',
    '}',
    '',
    '.theme-info {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 12px;',
    '}',
    '.theme-tag {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 10px 16px;',
    '  background: var(--vscode-editor-background);',
    '  border-radius: 24px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  font-size: 0.9em;',
    '  transition: all 0.2s ease;',
    '  cursor: default;',
    '}',
    '.theme-tag:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08);',
    '  transform: translateY(-1px);',
    '}',
    '.theme-name {',
    '  font-weight: 600;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.theme-corr {',
    '  font-size: 0.85em;',
    '  color: var(--vscode-descriptionForeground);',
    '  background: var(--vscode-button-secondaryBackground);',
    '  padding: 3px 8px;',
    '  border-radius: 12px;',
    '  font-weight: 500;',
    '}',
    '',
    '/* ========== 持仓明细表格 ========== */',
    '.position-table {',
    '  width: 100%;',
    '  border-collapse: collapse;',
    '  font-size: 12px;',
    '}',
    '.position-table th {',
    '  padding: 6px 10px;',
    '  text-align: right;',
    '  font-weight: 600;',
    '  color: var(--vscode-descriptionForeground);',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '  white-space: nowrap;',
    '  background: var(--vscode-editorWidget-background);',
    '}',
    '.position-table th:first-child {',
    '  text-align: left;',
    '}',
    '.position-table td {',
    '  padding: 7px 10px;',
    '  text-align: right;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '  vertical-align: middle;',
    '}',
    '.position-table td:first-child {',
    '  text-align: left;',
    '}',
    '.position-table tr:last-child td {',
    '  border-bottom: none;',
    '}',
    '.position-table tr:hover td {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '.position-stock-name {',
    '  font-weight: 500;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.position-stock-code {',
    '  font-size: 11px;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-top: 2px;',
    '}',
    '.position-up { color: #f56c6c; }',
    '.position-down { color: #4eb61b; }',
    '.position-flat { color: var(--vscode-descriptionForeground); }',
    '.position-compared-new {',
    '  font-size: 11px;',
    '  padding: 1px 5px;',
    '  border-radius: 3px;',
    '  background: rgba(115, 201, 145, 0.15);',
    '  color: #73c991;',
    '  border: 1px solid rgba(115, 201, 145, 0.4);',
    '}',
    '.position-compared-up { color: #f56c6c; font-size: 11px; }',
    '.position-compared-down { color: #4eb61b; font-size: 11px; }',
    '.position-compared-flat { color: var(--vscode-descriptionForeground); font-size: 11px; }',
  ];
}