export function getStyles(): string[] {
  return [
    'body {',
    '  font-family: var(--vscode-font-family), sans-serif;',
    '  color: var(--vscode-editor-foreground);',
    '  background-color: var(--vscode-editor-background);',
    '  padding: 20px;',
    '  margin: 0;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 20px;',
    '}',
    'h2 {',
    '  margin-top: 0;',
    '  margin-bottom: 5px;',
    '  font-size: 1.2rem;',
    '}',
    'h3 {',
    '  margin-top: 0;',
    '  margin-bottom: 12px;',
    '  font-size: 1.1rem;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.header {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '  padding-bottom: 15px;',
    '}',
    '.card {',
    '  background-color: var(--vscode-editorWidget-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 8px;',
    '  padding: 15px;',
    '  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);',
    '}',
    '.chart-container {',
    '  width: 100%;',
    '  height: 350px;',
    '  margin-top: 10px;',
    '}',
    '.controls {',
    '  display: flex;',
    '  gap: 10px;',
    '  margin-bottom: 10px;',
    '}',
    '',
    '.btn-group {',
    '  display: flex;',
    '  gap: 5px;',
    '}',
    '.btn-group button {',
    '  background-color: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  padding: 6px 12px;',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  outline: none;',
    '  transition: all 0.2s;',
    '}',
    '.btn-group button:hover {',
    '  background-color: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.btn-group button.active {',
    '  background-color: var(--vscode-button-background);',
    '  color: var(--vscode-button-foreground);',
    '  border-color: var(--vscode-button-background);',
    '}',
    '',
    '.loading {',
    '  position: absolute;',
    '  top: 50%;',
    '  left: 50%;',
    '  transform: translate(-50%, -50%);',
    '  font-size: 14px;',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '',
    '.info-grid {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));',
    '  gap: 15px;',
    '}',
    '.info-item {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 4px;',
    '  padding: 10px;',
    '  background: var(--vscode-editor-background);',
    '  border-radius: 6px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '}',
    '.info-item:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08);',
    '  transform: translateY(-1px);',
    '}',
    '.info-label {',
    '  font-size: 0.85em;',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '.info-value {',
    '  font-size: 1.05em;',
    '  font-weight: 500;',
    '}',
    '.info-value.up {',
    '  color: #f56c6c;',
    '}',
    '.info-value.down {',
    '  color: #4eb61b;',
    '}',
    '',
    '.manager-info {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 15px;',
    '}',
    '.manager-card {',
    '  display: flex;',
    '  gap: 20px;',
    '  padding: 20px;',
    '  background: var(--vscode-editor-background);',
    '  border-radius: 12px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  transition: all 0.2s ease;',
    '}',
    '.manager-card:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);',
    '}',
    '.manager-avatar {',
    '  width: 80px;',
    '  height: 80px;',
    '  border-radius: 50%;',
    '  object-fit: cover;',
    '  background: linear-gradient(',
    '    135deg,',
    '    var(--vscode-button-secondaryBackground) 0%,',
    '    var(--vscode-button-background) 100%',
    '  );',
    '  border: 3px solid var(--vscode-panel-border);',
    '  flex-shrink: 0;',
    '}',
    '.manager-details {',
    '  flex: 1;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 12px;',
    '}',
    '.manager-name {',
    '  font-size: 1.2em;',
    '  font-weight: 600;',
    '  color: var(--vscode-editor-foreground);',
    '  margin-bottom: 4px;',
    '}',
    '.manager-tag {',
    '  display: inline-block;',
    '  padding: 4px 12px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border-radius: 16px;',
    '  font-size: 0.85em;',
    '  margin-right: 8px;',
    '  font-weight: 500;',
    '  transition: all 0.2s ease;',
    '}',
    '.manager-tag:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.manager-stats {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));',
    '  gap: 12px;',
    '  margin-top: 4px;',
    '}',
    '.manager-stat {',
    '  text-align: center;',
    '  padding: 12px;',
    '  background: var(--vscode-editorWidget-background);',
    '  border-radius: 8px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  transition: all 0.2s ease;',
    '}',
    '.manager-stat:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  transform: translateY(-2px);',
    '}',
    '.manager-stat-label {',
    '  font-size: 0.85em;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-bottom: 6px;',
    '  font-weight: 500;',
    '}',
    '.manager-stat-value {',
    '  font-size: 1.1em;',
    '  font-weight: 600;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.manager-resume {',
    '  margin-top: 8px;',
    '  padding: 14px;',
    '  background: var(--vscode-editorWidget-background);',
    '  border-radius: 8px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  font-size: 0.9em;',
    '  line-height: 1.6;',
    '  color: var(--vscode-editor-foreground);',
    '  max-height: 150px;',
    '  overflow-y: auto;',
    '}',
    '.manager-resume::-webkit-scrollbar {',
    '  width: 6px;',
    '}',
    '.manager-resume::-webkit-scrollbar-thumb {',
    '  background: var(--vscode-scrollbarSlider-background);',
    '  border-radius: 3px;',
    '}',
    '.manager-resume::-webkit-scrollbar-thumb:hover {',
    '  background: var(--vscode-scrollbarSlider-hoverBackground);',
    '}',
    '',
    '.theme-info {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 12px;',
    '}',
    '.theme-tag {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 10px 16px;',
    '  background: var(--vscode-editor-background);',
    '  border-radius: 24px;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  font-size: 0.9em;',
    '  transition: all 0.2s ease;',
    '  cursor: default;',
    '}',
    '.theme-tag:hover {',
    '  border-color: var(--vscode-focusBorder);',
    '  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08);',
    '  transform: translateY(-1px);',
    '}',
    '.theme-name {',
    '  font-weight: 600;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.theme-corr {',
    '  font-size: 0.85em;',
    '  color: var(--vscode-descriptionForeground);',
    '  background: var(--vscode-button-secondaryBackground);',
    '  padding: 3px 8px;',
    '  border-radius: 12px;',
    '  font-weight: 500;',
    '}',
  ];
}