/**
 * 批量加减仓弹窗样式
 */
export function getBatchAdjustStyles(): string[] {
  return [
    /* ── overlay ── */
    '#batchAdjustOverlay, #pendingConfirmOverlay {',
    '  display: none;',
    '  position: fixed; inset: 0;',
    '  background: rgba(0,0,0,.45);',
    '  z-index: 2000;',
    '  align-items: flex-end;',
    '  justify-content: center;',
    '}',
    '#batchAdjustPanel, #pendingConfirmPanel {',
    '  background: var(--vscode-editor-background);',
    '  width: 100%; max-width: 520px;',
    '  max-height: 82vh;',
    '  border-radius: 12px 12px 0 0;',
    '  display: flex; flex-direction: column;',
    '  box-shadow: 0 -4px 24px rgba(0,0,0,.2);',
    '  overflow: hidden;',
    '}',
    /* ── header ── */
    '.ba-header, .ba-confirm-header-bar {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 14px 14px 0; flex-shrink: 0;',
    '}',
    '.ba-title {',
    '  font-size: 14px; font-weight: 600;',
    '  color: var(--vscode-editor-foreground);',
    '}',
    '.ba-close {',
    '  background: none; border: none; cursor: pointer;',
    '  color: var(--vscode-descriptionForeground);',
    '  font-size: 18px; line-height: 1; padding: 2px 6px; border-radius: 4px;',
    '}',
    '.ba-close:hover { background: var(--vscode-list-hoverBackground); }',
    /* ── tabs ── */
    '.ba-tabs {',
    '  display: flex; gap: 4px; padding: 10px 14px 0; flex-shrink: 0;',
    '}',
    '.ba-tab {',
    '  flex: 1; padding: 6px 0;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 5px;',
    '  background: var(--vscode-editor-background);',
    '  color: var(--vscode-editor-foreground);',
    '  font-size: 12px; cursor: pointer; position: relative;',
    '}',
    '.ba-tab:hover { background: var(--vscode-list-hoverBackground); }',
    '.ba-tab.active {',
    '  background: var(--vscode-button-background);',
    '  color: var(--vscode-button-foreground);',
    '  border-color: var(--vscode-button-background);',
    '  font-weight: 600;',
    '}',
    '.ba-tab-badge {',
    '  position: absolute; top: -6px; right: -6px;',
    '  background: var(--vscode-notificationsErrorIcon-foreground, #f14c4c);',
    '  color: #fff; border-radius: 8px; font-size: 10px;',
    '  padding: 0 4px; min-width: 14px; line-height: 14px;',
    '}',
    /* ── body ── */
    '.ba-body {',
    '  flex: 1; overflow-y: auto; padding: 10px 14px;',
    '  display: flex; flex-direction: column; gap: 8px; min-height: 300px;',
    '}',
    '.ba-empty {',
    '  text-align: center; color: var(--vscode-descriptionForeground);',
    '  font-size: 12px; padding: 28px 0;',
    '}',
    /* ── search ── */
    '.ba-search-wrap { position: relative; flex-shrink: 0; }',
    '.ba-search {',
    '  width: 100%; box-sizing: border-box;',
    '  padding: 7px 10px;',
    '  border: 1px solid var(--vscode-input-border);',
    '  border-radius: 6px; font-size: 12px;',
    '  background: var(--vscode-input-background);',
    '  color: var(--vscode-input-foreground);',
    '  outline: none;',
    '}',
    '.ba-search:focus { border-color: var(--vscode-focusBorder); }',
    '.ba-search-dropdown {',
    '  position: absolute; left: 0; right: 0; top: calc(100% + 3px);',
    '  background: var(--vscode-editorWidget-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  box-shadow: 0 4px 12px rgba(0,0,0,.15);',
    '  z-index: 10; max-height: 180px; overflow-y: auto;',
    '}',
    '.ba-dropdown-item {',
    '  display: flex; align-items: center; gap: 6px;',
    '  padding: 7px 10px; cursor: pointer; font-size: 12px;',
    '}',
    '.ba-dropdown-item:hover { background: var(--vscode-list-hoverBackground); }',
    '.ba-dc { color: var(--vscode-descriptionForeground); min-width: 50px; }',
    '.ba-dn { flex: 1; }',
    '.ba-ds { color: var(--vscode-descriptionForeground); font-size: 11px; }',
    /* ── items ── */
    '.ba-items { display: flex; flex-direction: column; gap: 8px; }',
    '.ba-item {',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 8px; padding: 10px;',
    '  background: var(--vscode-editor-background);',
    '  display: flex; flex-direction: column; gap: 7px;',
    '}',
    '.ba-pending-item { border-color: #b8860b44; background: #b8860b0a; }',
    '.ba-item-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 6px; }',
    '.ba-item-name { font-size: 12px; font-weight: 600; color: var(--vscode-editor-foreground); }',
    '.ba-item-code { font-size: 11px; color: var(--vscode-descriptionForeground); margin-top: 1px; }',
    '.ba-item-remove {',
    '  background: none; border: none; cursor: pointer;',
    '  color: var(--vscode-descriptionForeground); font-size: 16px;',
    '  padding: 0 4px; border-radius: 3px; line-height: 1;',
    '}',
    '.ba-item-remove:hover { color: var(--vscode-notificationsErrorIcon-foreground, #f14c4c); }',
    '.ba-item-row { display: flex; align-items: center; gap: 6px; }',
    '.ba-label { font-size: 11px; color: var(--vscode-descriptionForeground); min-width: 56px; flex-shrink: 0; }',
    /* ── nav select ── */
    '.ba-nav-select {',
    '  flex: 1; padding: 4px 6px;',
    '  border: 1px solid var(--vscode-input-border);',
    '  border-radius: 5px; font-size: 11px;',
    '  background: var(--vscode-input-background);',
    '  color: var(--vscode-input-foreground);',
    '  cursor: pointer; outline: none; min-width: 0;',
    '}',
    '.ba-nav-select:focus { border-color: var(--vscode-focusBorder); }',
    '.ba-pending-nav { color: #b8860b; font-style: italic; font-size: 12px; }',
    /* ── amount ── */
    '.ba-amount-wrap {',
    '  flex: 1; display: flex; align-items: center;',
    '  border: 1px solid var(--vscode-input-border);',
    '  border-radius: 5px; overflow: hidden;',
    '  background: var(--vscode-input-background);',
    '}',
    '.ba-amount-wrap:focus-within { border-color: var(--vscode-focusBorder); }',
    '.ba-amount {',
    '  flex: 1; border: none; outline: none;',
    '  background: transparent; padding: 5px 7px;',
    '  font-size: 12px; color: var(--vscode-input-foreground); min-width: 0;',
    '}',
    '.ba-amount::-webkit-outer-spin-button,.ba-amount::-webkit-inner-spin-button{-webkit-appearance:none;}',
    '.ba-amount[type=number]{-moz-appearance:textfield;}',
    '.ba-unit {',
    '  padding: 0 7px; font-size: 11px;',
    '  color: var(--vscode-descriptionForeground);',
    '  border-left: 1px solid var(--vscode-panel-border);',
    '  background: var(--vscode-editorWidget-background);',
    '  line-height: 26px; flex-shrink: 0;',
    '}',
    /* ── preview ── */
    '.ba-preview {',
    '  background: var(--vscode-editorWidget-background);',
    '  border-radius: 5px; padding: 7px 9px;',
    '  display: flex; flex-direction: column; gap: 4px;',
    '}',
    '.ba-preview-pending { border: 1px dashed #b8860b66; }',
    '.ba-preview-row {',
    '  display: flex; justify-content: space-between;',
    '  font-size: 11px; color: var(--vscode-editor-foreground);',
    '}',
    '.ba-plabel { color: var(--vscode-descriptionForeground); min-width: 56px; }',
    '.ba-positive { color: var(--vscode-notificationsErrorIcon-foreground, #f14c4c); }',
    '.ba-negative { color: var(--vscode-terminal-ansiGreen, #4caf50); }',
    '.ba-muted { color: var(--vscode-descriptionForeground); }',
    '.ba-error { color: var(--vscode-notificationsErrorIcon-foreground, #f14c4c); font-size: 11px; }',
    '.ba-retry {',
    '  background: none; border: none;',
    '  color: var(--vscode-textLink-foreground);',
    '  cursor: pointer; font-size: 11px; padding: 0 2px;',
    '}',
    /* ── pending tag ── */
    '.ba-pending-tag {',
    '  font-size: 11px; color: #b8860b;',
    '  background: #b8860b18; border-radius: 4px; padding: 2px 7px;',
    '  width: fit-content;',
    '}',
    /* ── footer ── */
    '.ba-footer {',
    '  display: flex; gap: 8px; padding: 10px 14px;',
    '  border-top: 1px solid var(--vscode-panel-border); flex-shrink: 0;',
    '}',
    '.ba-btn-cancel {',
    '  flex: 1; padding: 7px 0;',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  background: var(--vscode-editor-background);',
    '  color: var(--vscode-editor-foreground);',
    '  font-size: 13px; cursor: pointer;',
    '}',
    '.ba-btn-cancel:hover { background: var(--vscode-list-hoverBackground); }',
    '.ba-btn-confirm {',
    '  flex: 2; padding: 7px 0; border: none; border-radius: 6px;',
    '  background: var(--vscode-button-background);',
    '  color: var(--vscode-button-foreground);',
    '  font-size: 13px; font-weight: 600; cursor: pointer;',
    '}',
    '.ba-btn-confirm:hover:not([disabled]) { background: var(--vscode-button-hoverBackground); }',
    '.ba-btn-confirm[disabled] { opacity: .5; cursor: not-allowed; }',
    /* ── pending confirm panel ── */
    '.ba-confirm-hint { font-size: 12px; color: var(--vscode-descriptionForeground); margin: 8px 14px 0; }',
    '.ba-confirm-list { flex: 1; overflow-y: auto; padding: 0 14px 8px; display: flex; flex-direction: column; gap: 8px; min-height: 0; }',
    '.ba-confirm-card {',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 8px; padding: 10px;',
    '  display: flex; flex-direction: column; gap: 6px;',
    '}',
    '.ba-confirm-header { display: flex; align-items: baseline; gap: 8px; }',
    '.ba-confirm-row { display: flex; justify-content: space-between; font-size: 12px; }',
    '.ba-clabel { color: var(--vscode-descriptionForeground); min-width: 56px; }',
    '.ba-divider { height: 1px; background: var(--vscode-panel-border); margin: 2px 0; }',
    /* ── btn-batch-adjust ── */
    '#btnBatchAdjust { position: relative; }',
    '.batch-badge {',
    '  position: absolute; top: -5px; right: -5px;',
    '  background: var(--vscode-notificationsErrorIcon-foreground, #f14c4c);',
    '  color: #fff; border-radius: 7px; font-size: 9px;',
    '  padding: 0 3px; min-width: 13px; line-height: 13px;',
    '  text-align: center; pointer-events: none;',
    '}',
  ]
}
