/**
 * 批量加减仓弹窗 - Webview 端脚本
 * 通过 vscode.postMessage 与 Extension Host 通信
 */

export function getBatchAdjustScript(): string[] {
  return [
    'window.initBatchAdjust = function(vscodeApi) {',
    '',
    '// ── 内部确认/提示弹窗（不依赖 alert/confirm，兼容 sandbox）──',
    'function baConfirm(message, onOk) {',
    '  var existing = document.getElementById("baConfirmDialog");',
    '  if (existing) existing.remove();',
    '  var d = document.createElement("div");',
    '  d.id = "baConfirmDialog";',
    '  d.style.cssText = "position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.45);";',
    '  var hasOk = typeof onOk === "function";',
    '  d.innerHTML = \'<div style="background:var(--vscode-editor-background);border:1px solid var(--vscode-panel-border);border-radius:8px;padding:20px 24px;max-width:320px;width:90%;box-shadow:0 4px 20px rgba(0,0,0,.3);">\'',
    '    +\'<div style="font-size:13px;color:var(--vscode-editor-foreground);margin-bottom:16px;line-height:1.5;">\'+message+\'</div>\'',
    '    +\'<div style="display:flex;gap:8px;justify-content:flex-end;">\'',
    '    +(hasOk ? \'<button id="baConfirmCancel" style="padding:5px 14px;border:1px solid var(--vscode-panel-border);border-radius:4px;background:var(--vscode-editor-background);color:var(--vscode-editor-foreground);cursor:pointer;font-size:12px;">取消</button>\' : "")',
    '    +\'<button id="baConfirmOk" style="padding:5px 14px;border:none;border-radius:4px;background:var(--vscode-button-background);color:var(--vscode-button-foreground);cursor:pointer;font-size:12px;">\' +(hasOk ? "确定" : "知道了")+ \'</button>\'',
    '    +\'</div></div>\';',
    '  document.body.appendChild(d);',
    '  function close() { d.remove(); }',
    '  d.querySelector("#baConfirmOk").addEventListener("click", function() { close(); if (hasOk) onOk(); });',
    '  var cancelBtn = d.querySelector("#baConfirmCancel");',
    '  if (cancelBtn) cancelBtn.addEventListener("click", close);',
    '  d.addEventListener("click", function(e) { if (e.target === d) close(); });',
    '}',
    '',
    '// ── 状态 ─────────────────────────────────────────────────',
    'var ba = {',
    '  vscode: vscodeApi,',
    '  visible: false,',
    '  activeTab: "buy",        // "buy" | "sell" | "pending"',
    '  buyItems: [],            // [{code,name,navList,navLoading,navError,selectedDate,selectedNav,amount}]',
    '  sellItems: [],           // [{code,name,maxShares,maxCost,sellShares}]',
    '  pendingList: [],         // BuyRecord[]',
    '  pendingCount: 0,',
    '  fundDataCache: [],       // 来自外部注入',
    '  buySearchTimer: null,',
    '  confirming: false,',
    '',
    '  // pending 确认弹窗',
    '  pendingReadyList: [],',
    '  pendingConfirmVisible: false,',
    '};',
    '',
    '// ── 外部注入 fund cache ───────────────────────────────────',
    'ba.setFundCache = function(data) { ba.fundDataCache = data || []; };',
    '',
    '// ── 今日日期 ──────────────────────────────────────────────',
    'ba.todayStr = function() {',
    '  var d = new Date();',
    '  var mm = String(d.getMonth()+1).padStart(2,"0");',
    '  var dd = String(d.getDate()).padStart(2,"0");',
    '  return d.getFullYear() + "-" + mm + "-" + dd;',
    '};',
    '',
    '// ── 格式化时间戳 ──────────────────────────────────────────',
    'ba.fmtTime = function(ts) {',
    '  var d = new Date(ts);',
    '  return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")',
    '    +" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0");',
    '};',
    '',
    '// ── pending 数量角标 ──────────────────────────────────────',
    'ba.updatePendingBadge = function() {',
    '  var btn = document.getElementById("btnBatchAdjust");',
    '  if (!btn) return;',
    '  var badge = btn.querySelector(".batch-badge");',
    '  if (ba.pendingCount > 0) {',
    '    if (!badge) {',
    '      badge = document.createElement("span");',
    '      badge.className = "batch-badge";',
    '      btn.appendChild(badge);',
    '    }',
    '    badge.textContent = ba.pendingCount;',
    '  } else {',
    '    if (badge) badge.remove();',
    '  }',
    '};',
    '',
    '// ── 打开 / 关闭弹窗 ──────────────────────────────────────',
    'ba.open = function() {',
    '  ba.visible = true;',
    '  ba.vscode.postMessage({ command: "batchAdjust_loadPending" });',
    '  ba.render();',
    '  var overlay = document.getElementById("batchAdjustOverlay");',
    '  if (overlay) overlay.style.display = "flex";',
    '};',
    '',
    'ba.close = function() {',
    '  ba.visible = false;',
    '  var overlay = document.getElementById("batchAdjustOverlay");',
    '  if (overlay) overlay.style.display = "none";',
    '  ba.buyItems = [];',
    '  ba.sellItems = [];',
    '  ba.activeTab = "buy";',
    '};',
    '',
    '// ── 主渲染 ───────────────────────────────────────────────',
    'ba.render = function() {',
    '  var panel = document.getElementById("batchAdjustPanel");',
    '  if (!panel) return;',
    '  panel.innerHTML = ba.renderPanel();',
    '  ba.bindPanelEvents();',
    '};',
    '',
    'ba.renderPanel = function() {',
    '  var tabs = ["buy","sell","pending"];',
    '  var tabLabels = { buy:"加仓", sell:"减仓", pending:"进行中" };',
    '  var tabsHtml = tabs.map(function(t) {',
    '    var badge = t==="pending" && ba.pendingCount>0',
    '      ? \'<span class="ba-tab-badge">\'+ba.pendingCount+\'</span>\'',
    '      : "";',
    '    return \'<button class="ba-tab\'+(ba.activeTab===t?" active":\'\')+\'" data-tab="\'+t+\'">\'+tabLabels[t]+badge+\'</button>\';',
    '  }).join("");',
    '',
    '  var bodyHtml = "";',
    '  if (ba.activeTab==="buy")     bodyHtml = ba.renderBuyPanel();',
    '  else if (ba.activeTab==="sell")  bodyHtml = ba.renderSellPanel();',
    '  else                          bodyHtml = ba.renderPendingPanel();',
    '',
    '  var footer = ba.activeTab !== "pending" ? \'<div class="ba-footer">\'',
    '    +\'<button class="ba-btn-cancel" id="baBtnCancel">取消</button>\'',
    '    +\'<button class="ba-btn-confirm" id="baBtnConfirm" \'+(ba.canConfirm()?"":"disabled")+\'>\'+',
    '    (ba.confirming?"处理中...":"确认操作")+\'</button></div>\' : "";',
    '',
    '  return \'<div class="ba-header">\'',
    '    +\'<span class="ba-title">批量加减仓</span>\'',
    '    +\'<button class="ba-close" id="baBtnClose">×</button>\'',
    '    +\'</div>\'',
    '    +\'<div class="ba-tabs">\'+tabsHtml+\'</div>\'',
    '    +\'<div class="ba-body">\'+bodyHtml+\'</div>\'',
    '    +footer;',
    '};',
    '',
  ]
}

export function getBatchAdjustScript2(): string[] {
  return [
    '// ── 加仓面板渲染 ─────────────────────────────────────────',
    'ba.renderBuyPanel = function() {',
    '  var searchHtml = \'<div class="ba-search-wrap">\'',
    '    +\'<input class="ba-search" id="baBuySearch" placeholder="搜索基金代码或名称..." autocomplete="off"/>\'',
    '    +\'<div class="ba-search-dropdown" id="baBuyDropdown" style="display:none;"></div>\'',
    '    +\'</div>\';',
    '',
    '  var itemsHtml = ba.buyItems.length===0',
    '    ? \'<div class="ba-empty">搜索并点击基金以添加加仓计划</div>\'',
    '    : ba.buyItems.map(ba.renderBuyItem).join("");',
    '',
    '  return searchHtml + \'<div class="ba-items">\' + itemsHtml + \'</div>\';',
    '};',
    '',
    'ba.renderBuyItem = function(item) {',
    '  var removeBtn = \'<button class="ba-item-remove" data-code="\'+item.code+\'" data-type="buy">×</button>\';',
    '',
    '  var navSelectHtml;',
    '  if (item.navLoading) {',
    '    navSelectHtml = \'<span class="ba-muted">加载中...</span>\';',
    '  } else if (item.navError) {',
    '    navSelectHtml = \'<span class="ba-error">加载失败 <button class="ba-retry" data-code="\'+item.code+\'">重试</button></span>\';',
    '  } else {',
    '    var opts = \'<option value="" disabled \' + (item.selectedDate===""?"selected":"")+\'>选择日期</option>\';',
    '    opts += \'<option value="today" \'+(item.selectedDate==="today"?"selected":"")+\'>今日 \'+ba.todayStr()+\'（待更新）</option>\';',
    '    item.navList.forEach(function(nav) {',
    '      opts += \'<option value="\'+nav.date+\'" \'+(item.selectedDate===nav.date?"selected":"")+\'>\'+',
    '        nav.date+\'  净值 \'+nav.netValue.toFixed(4)+\'  \'+(nav.changePercent>=0?"+":"")+nav.changePercent.toFixed(2)+\'%</option>\';',
    '    });',
    '    navSelectHtml = \'<select class="ba-nav-select" data-code="\'+item.code+\'">\'+opts+\'</select>\';',
    '  }',
    '',
    '  var navValueHtml = "";',
    '  if (item.selectedDate) {',
    '    var navVal = item.selectedDate==="today" ? \'<span class="ba-pending-nav">待更新</span>\' : (item.selectedNav ? item.selectedNav.toFixed(4) : "—");',
    '    navValueHtml = \'<div class="ba-item-row"><span class="ba-label">买入净值</span><span>\'+navVal+\'</span></div>\';',
    '  }',
    '',
    '  var amountHtml = \'<div class="ba-item-row">\'',
    '    +\'<span class="ba-label">买入金额</span>\'',
    '    +\'<div class="ba-amount-wrap">\'',
    '    +\'<input class="ba-amount" type="number" min="0.01" step="100" data-code="\'+item.code+\'" data-type="buy" value="\' + (item.amount||"") + \'" placeholder="输入金额（元）"/>\'',
    '    +\'<span class="ba-unit">元</span>\'',
    '    +\'</div></div>\';',
    '',
    '  var previewHtml = "";',
    '  if (item.selectedDate==="today" && item.amount>0) {',
    '    previewHtml = \'<div class="ba-preview ba-preview-pending">\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">买入金额</span><span>\'+item.amount.toFixed(2)+\' 元</span></div>\'',
    '      +\'<div class="ba-preview-row ba-muted"><span>净值待更新后自动计算</span></div>\'',
    '      +\'</div>\';',
    '  } else if (item.selectedDate && item.selectedDate!=="today" && item.selectedNav && item.amount>0) {',
    '    var fund = ba.fundDataCache.find(function(f){return f.code===item.code;});',
    '    var oldNum = fund ? parseFloat(fund.num)||0 : 0;',
    '    var oldCost = fund ? parseFloat(fund.cost)||0 : 0;',
    '    var addNum = item.amount / item.selectedNav;',
    '    var newNum = oldNum + addNum;',
    '    var newCost = newNum>0 ? (oldCost*oldNum + item.selectedNav*addNum)/newNum : item.selectedNav;',
    '    var oldAmount = oldNum * oldCost;',
    '    var newAmount = newNum * newCost;',
    '    previewHtml = \'<div class="ba-preview">\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">新增份额</span><span class="ba-positive">+\'+addNum.toFixed(2)+\' 份</span></div>\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">持有份额</span><span>\'+oldNum.toFixed(2)+\' → <strong>\'+newNum.toFixed(2)+\'</strong> 份</span></div>\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">成本价</span><span>\'+oldCost.toFixed(4)+\' → <strong>\'+newCost.toFixed(4)+\'</strong></span></div>\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">持仓总额</span><span>\'+oldAmount.toFixed(2)+\' → <strong>\'+newAmount.toFixed(2)+\'</strong> 元</span></div>\'',
    '      +\'</div>\';',
    '  }',
    '',
    '  return \'<div class="ba-item" data-code="\'+item.code+\'">\'',
    '    +\'<div class="ba-item-header">\'',
    '    +\'<div><div class="ba-item-name">\'+item.name+\'</div><div class="ba-item-code">\'+item.code+\'</div></div>\'',
    '    +removeBtn+\'</div>\'',
    '    +\'<div class="ba-item-row"><span class="ba-label">买入日期</span>\'+navSelectHtml+\'</div>\'',
    '    +navValueHtml',
    '    +amountHtml',
    '    +previewHtml',
    '    +\'</div>\';',
    '};',
    '',
    '// ── 减仓面板渲染 ─────────────────────────────────────────',
    'ba.renderSellPanel = function() {',
    '  var searchHtml = \'<div class="ba-search-wrap">\'',
    '    +\'<input class="ba-search" id="baSellSearch" placeholder="从持仓中搜索基金..." autocomplete="off"/>\'',
    '    +\'<div class="ba-search-dropdown" id="baSellDropdown" style="display:none;"></div>\'',
    '    +\'</div>\';',
    '',
    '  var itemsHtml = ba.sellItems.length===0',
    '    ? \'<div class="ba-empty">搜索持仓基金以添加减仓计划</div>\'',
    '    : ba.sellItems.map(ba.renderSellItem).join("");',
    '',
    '  return searchHtml + \'<div class="ba-items">\' + itemsHtml + \'</div>\';',
    '};',
    '',
    'ba.renderSellItem = function(item) {',
    '  var removeBtn = \'<button class="ba-item-remove" data-code="\'+item.code+\'" data-type="sell">×</button>\';',
    '  var sharesHtml = \'<div class="ba-item-row">\'',
    '    +\'<span class="ba-label">减仓份额</span>\'',
    '    +\'<div class="ba-amount-wrap">\'',
    '    +\'<input class="ba-amount" type="number" min="0.01" max="\'+item.maxShares+\'" step="1" data-code="\'+item.code+\'" data-type="sell" value="\' + (item.sellShares||"") + \'" placeholder="最多 \'+item.maxShares.toFixed(2)+\' 份"/>\'',
    '    +\'<span class="ba-unit">份</span>\'',
    '    +\'</div></div>\';',
    '',
    '  var previewHtml = "";',
    '  if (item.sellShares>0 && item.sellShares<=item.maxShares) {',
    '    var newNum = item.maxShares - item.sellShares;',
    '    var oldAmount = item.maxShares * item.maxCost;',
    '    var newAmount = newNum * item.maxCost;',
    '    previewHtml = \'<div class="ba-preview">\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">减少份额</span><span class="ba-negative">-\'+item.sellShares.toFixed(2)+\' 份</span></div>\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">持有份额</span><span>\'+item.maxShares.toFixed(2)+\' → <strong>\'+newNum.toFixed(2)+\'</strong> 份</span></div>\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">成本价</span><span>\'+item.maxCost.toFixed(4)+\'（不变）</span></div>\'',
    '      +\'<div class="ba-preview-row"><span class="ba-plabel">持仓总额</span><span>\'+oldAmount.toFixed(2)+\' → <strong>\'+newAmount.toFixed(2)+\'</strong> 元</span></div>\'',
    '      +\'</div>\';',
    '  }',
    '',
    '  return \'<div class="ba-item" data-code="\'+item.code+\'">\'',
    '    +\'<div class="ba-item-header">\'',
    '    +\'<div><div class="ba-item-name">\'+item.name+\'</div><div class="ba-item-code">\'+item.code+\'</div></div>\'',
    '    +removeBtn+\'</div>\'',
    '    +sharesHtml',
    '    +previewHtml',
    '    +\'</div>\';',
    '};',
    '',
    '// ── 进行中面板渲染 ────────────────────────────────────────',
    'ba.renderPendingPanel = function() {',
    '  if (ba.pendingList.length===0)',
    '    return \'<div class="ba-empty">暂无等待更新净值的加仓记录</div>\';',
    '',
    '  return \'<div class="ba-items">\'+ba.pendingList.map(function(r) {',
    '    return \'<div class="ba-item ba-pending-item">\'',
    '      +\'<div class="ba-item-header">\'',
    '      +\'<div><div class="ba-item-name">\'+r.name+\'</div><div class="ba-item-code">\'+r.code+\'</div></div>\'',
    '      +\'<button class="ba-item-remove" data-id="\'+r.id+\'" data-type="pending">×</button>\'',
    '      +\'</div>\'',
    '      +\'<div class="ba-pending-tag">⏳ 等待 \'+r.buyDate+\' 净值更新</div>\'',
    '      +\'<div class="ba-item-row"><span class="ba-label">买入日期</span><span>\'+r.buyDate+\'</span></div>\'',
    '      +\'<div class="ba-item-row"><span class="ba-label">买入金额</span><span>\'+r.amount.toFixed(2)+\' 元</span></div>\'',
    '      +\'<div class="ba-item-row ba-muted" style="font-size:11px;">创建于 \'+ba.fmtTime(r.createdAt)+\'</div>\'',
    '      +\'</div>\';',
    '  }).join("")+\'</div>\';',
    '};',
    '',
  ]
}

export function getBatchAdjustScript3(): string[] {
  return [
    '// ── refreshPreview：只更新当前 item 的预览区，不整体 render ─',
    'ba.refreshPreview = function(code, type) {',
    '  if (type==="buy") {',
    '    var item = ba.buyItems.find(function(i){return i.code===code;});',
    '    if (!item) return;',
    '    var card = document.querySelector(\'.ba-item[data-code="\'+code+\'"]\');',
    '    if (!card) return;',
    '    var oldPreview = card.querySelector(".ba-preview");',
    '    if (oldPreview) oldPreview.remove();',
    '    var previewHtml = "";',
    '    if (item.selectedDate==="today" && item.amount>0) {',
    '      previewHtml = \'<div class="ba-preview ba-preview-pending">\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">买入金额</span><span>\'+item.amount.toFixed(2)+\' 元</span></div>\'',
    '        +\'<div class="ba-preview-row ba-muted"><span>净值待更新后自动计算</span></div>\'',
    '        +\'</div>\';',
    '    } else if (item.selectedDate && item.selectedDate!=="today" && item.selectedNav && item.amount>0) {',
    '      var fund = ba.fundDataCache.find(function(f){return f.code===item.code;});',
    '      var oldNum = fund ? parseFloat(fund.num)||0 : 0;',
    '      var oldCost = fund ? parseFloat(fund.cost)||0 : 0;',
    '      var addNum = item.amount / item.selectedNav;',
    '      var newNum = oldNum + addNum;',
    '      var newCost = newNum>0 ? (oldCost*oldNum + item.selectedNav*addNum)/newNum : item.selectedNav;',
    '      var oldAmount = oldNum * oldCost;',
    '      var newAmount = newNum * newCost;',
    '      previewHtml = \'<div class="ba-preview">\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">新增份额</span><span class="ba-positive">+\'+addNum.toFixed(2)+\' 份</span></div>\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">持有份额</span><span>\'+oldNum.toFixed(2)+\' → <strong>\'+newNum.toFixed(2)+\'</strong> 份</span></div>\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">成本价</span><span>\'+oldCost.toFixed(4)+\' → <strong>\'+newCost.toFixed(4)+\'</strong></span></div>\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">持仓总额</span><span>\'+oldAmount.toFixed(2)+\' → <strong>\'+newAmount.toFixed(2)+\'</strong> 元</span></div>\'',
    '        +\'</div>\';',
    '    }',
    '    if (previewHtml) {',
    '      var tmp = document.createElement("div");',
    '      tmp.innerHTML = previewHtml;',
    '      card.appendChild(tmp.firstChild);',
    '    }',
    '    // 更新确认按钮状态',
    '    var confirmBtn = document.getElementById("baBtnConfirm");',
    '    if (confirmBtn) confirmBtn.disabled = !ba.canConfirm();',
    '  } else if (type==="sell") {',
    '    var sitem = ba.sellItems.find(function(i){return i.code===code;});',
    '    if (!sitem) return;',
    '    var scardEl = document.querySelector(\'.ba-item[data-code="\'+code+\'"]\');',
    '    if (!scardEl) return;',
    '    var oldP = scardEl.querySelector(".ba-preview");',
    '    if (oldP) oldP.remove();',
    '    var sPreviewHtml = "";',
    '    if (sitem.sellShares>0 && sitem.sellShares<=sitem.maxShares) {',
    '      var sNewNum = sitem.maxShares - sitem.sellShares;',
    '      var sOldAmt = sitem.maxShares * sitem.maxCost;',
    '      var sNewAmt = sNewNum * sitem.maxCost;',
    '      sPreviewHtml = \'<div class="ba-preview">\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">减少份额</span><span class="ba-negative">-\'+sitem.sellShares.toFixed(2)+\' 份</span></div>\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">持有份额</span><span>\'+sitem.maxShares.toFixed(2)+\' → <strong>\'+sNewNum.toFixed(2)+\'</strong> 份</span></div>\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">成本价</span><span>\'+sitem.maxCost.toFixed(4)+\'（不变）</span></div>\'',
    '        +\'<div class="ba-preview-row"><span class="ba-plabel">持仓总额</span><span>\'+sOldAmt.toFixed(2)+\' → <strong>\'+sNewAmt.toFixed(2)+\'</strong> 元</span></div>\'',
    '        +\'</div>\';',
    '    }',
    '    if (sPreviewHtml) {',
    '      var stmp = document.createElement("div");',
    '      stmp.innerHTML = sPreviewHtml;',
    '      scardEl.appendChild(stmp.firstChild);',
    '    }',
    '    var sConfirmBtn = document.getElementById("baBtnConfirm");',
    '    if (sConfirmBtn) sConfirmBtn.disabled = !ba.canConfirm();',
    '  }',
    '};',
    '',
    'ba.canConfirm = function() {',
    '  if (ba.activeTab==="buy")',
    '    return ba.buyItems.some(function(i){return i.amount>0 && i.selectedDate;});',
    '  if (ba.activeTab==="sell")',
    '    return ba.sellItems.some(function(i){return i.sellShares>0 && i.sellShares<=i.maxShares;});',
    '  return false;',
    '};',
    '',
    '// ── 事件绑定 ──────────────────────────────────────────────',
    'ba.bindPanelEvents = function() {',
    '  var panel = document.getElementById("batchAdjustPanel");',
    '  if (!panel) return;',
    '',
    '  panel.querySelector("#baBtnClose")?.addEventListener("click", function(){ ba.close(); });',
    '  panel.querySelector("#baBtnCancel")?.addEventListener("click", function(){ ba.close(); });',
    '  panel.querySelector("#baBtnConfirm")?.addEventListener("click", function(){ ba.handleConfirm(); });',
    '',
    '  // tab 切换',
    '  panel.querySelectorAll(".ba-tab").forEach(function(btn) {',
    '    btn.addEventListener("click", function(e) {',
    '      ba.activeTab = e.target.dataset.tab || e.target.closest(".ba-tab").dataset.tab;',
    '      ba.render();',
    '    });',
    '  });',
    '',
    '  // 加仓搜索',
    '  var buySearch = panel.querySelector("#baBuySearch");',
    '  if (buySearch) {',
    '    buySearch.addEventListener("input", function(e) {',
    '      clearTimeout(ba.buySearchTimer);',
    '      var q = e.target.value.trim();',
    '      var dropdown = document.getElementById("baBuyDropdown");',
    '      if (!q) { if(dropdown) dropdown.style.display="none"; return; }',
    '      ba.buySearchTimer = setTimeout(function() {',
    '        ba.vscode.postMessage({ command: "batchAdjust_searchFund", keyword: q, target: "buy" });',
    '      }, 300);',
    '    });',
    '    buySearch.addEventListener("blur", function() {',
    '      setTimeout(function(){',
    '        var dropdown = document.getElementById("baBuyDropdown");',
    '        if (dropdown) dropdown.style.display="none";',
    '      }, 200);',
    '    });',
    '  }',
    '',
    '  // 减仓搜索（从本地 fundDataCache 过滤）',
    '  var sellSearch = panel.querySelector("#baSellSearch");',
    '  if (sellSearch) {',
    '    sellSearch.addEventListener("input", function(e) {',
    '      var q = e.target.value.trim().toLowerCase();',
    '      var dropdown = document.getElementById("baSellDropdown");',
    '      if (!q || !dropdown) { if(dropdown) dropdown.style.display="none"; return; }',
    '      var results = ba.fundDataCache.filter(function(f) {',
    '        return f.code.includes(q) || (f.name||"").toLowerCase().includes(q);',
    '      }).slice(0,10);',
    '      if (results.length===0) { dropdown.style.display="none"; return; }',
    '      dropdown.innerHTML = results.map(function(f) {',
    '        return \'<div class="ba-dropdown-item" data-code="\'+f.code+\'" data-name="\'+f.name+\'" data-num="\'+f.num+\'" data-cost="\'+f.cost+\'">\'',
    '          +\'<span class="ba-dc">\'+f.code+\'</span><span class="ba-dn">\'+f.name+\'</span>\'',
    '          +\'<span class="ba-ds">\'+parseFloat(f.num).toFixed(2)+\' 份</span></div>\';',
    '      }).join("");',
    '      dropdown.style.display = "block";',
    '      dropdown.querySelectorAll(".ba-dropdown-item").forEach(function(item) {',
    '        item.addEventListener("mousedown", function(e) {',
    '          e.preventDefault();',
    '          ba.addSellItem(item.dataset.code, item.dataset.name, parseFloat(item.dataset.num)||0, parseFloat(item.dataset.cost)||0);',
    '          if(sellSearch) sellSearch.value="";',
    '          dropdown.style.display="none";',
    '        });',
    '      });',
    '    });',
    '  }',
    '',
    '  // 移除按钮',
    '  panel.querySelectorAll(".ba-item-remove").forEach(function(btn) {',
    '    btn.addEventListener("click", function() {',
    '      var type = btn.dataset.type;',
    '      if (type==="buy")  ba.removeBuyItem(btn.dataset.code);',
    '      else if (type==="sell") ba.removeSellItem(btn.dataset.code);',
    '      else if (type==="pending") ba.cancelPendingItem(btn.dataset.id);',
    '    });',
    '  });',
    '',
    '  // 净值日期 select',
    '  panel.querySelectorAll(".ba-nav-select").forEach(function(sel) {',
    '    sel.addEventListener("change", function() {',
    '      ba.onNavDateChange(sel.dataset.code, sel.value);',
    '    });',
    '  });',
    '',
    '  // 重试按钮',
    '  panel.querySelectorAll(".ba-retry").forEach(function(btn) {',
    '    btn.addEventListener("click", function() { ba.loadNavForCode(btn.dataset.code); });',
    '  });',
    '',
    '  // 金额/份额输入：input 事件只更新数据不重渲染（防止失焦）',
    '  panel.querySelectorAll(".ba-amount").forEach(function(inp) {',
    '    inp.addEventListener("input", function() {',
    '      var val = parseFloat(inp.value) || 0;',
    '      if (inp.dataset.type==="buy") {',
    '        var item = ba.buyItems.find(function(i){return i.code===inp.dataset.code;});',
    '        if (item) {',
    '          item.amount = val;',
    '          ba.refreshPreview(inp.dataset.code, "buy");',
    '        }',
    '      } else if (inp.dataset.type==="sell") {',
    '        var sitem = ba.sellItems.find(function(i){return i.code===inp.dataset.code;});',
    '        if (sitem) {',
    '          sitem.sellShares = val;',
    '          ba.refreshPreview(inp.dataset.code, "sell");',
    '        }',
    '      }',
    '    });',
    '    // change（失焦）时做一次完整 render，更新确认按钮状态',
    '    inp.addEventListener("change", function() {',
    '      var code = inp.dataset.code;',
    '      var type = inp.dataset.type;',
    '      ba.render();',
    '      // render 后重新聚焦同一个输入框',
    '      var sel = \'.ba-amount[data-code="\'+code+\'"][data-type="\'+type+\'"]\';',
    '      var refocus = document.querySelector(sel);',
    '      if (refocus) { refocus.focus(); refocus.select(); }',
    '    });',
    '  });',
    '};',
    '',
    '// ── 加仓操作 ──────────────────────────────────────────────',
    'ba.addBuyItem = function(code, name) {',
    '  if (ba.buyItems.find(function(i){return i.code===code;})) {',
    '    baConfirm("该基金已添加", null); return;',
    '  }',
    '  ba.buyItems.push({ code:code, name:name, navList:[], navLoading:true, navError:false, selectedDate:"", selectedNav:null, amount:0 });',
    '  ba.render();',
    '  ba.loadNavForCode(code);',
    '};',
    '',
    'ba.removeBuyItem = function(code) {',
    '  ba.buyItems = ba.buyItems.filter(function(i){return i.code!==code;});',
    '  ba.render();',
    '};',
    '',
    'ba.onNavDateChange = function(code, val) {',
    '  var item = ba.buyItems.find(function(i){return i.code===code;});',
    '  if (!item) return;',
    '  item.selectedDate = val;',
    '  if (val==="today") { item.selectedNav = null; }',
    '  else {',
    '    var found = item.navList.find(function(n){return n.date===val;});',
    '    item.selectedNav = found ? found.netValue : null;',
    '  }',
    '  ba.render();',
    '};',
    '',
    'ba.loadNavForCode = function(code) {',
    '  ba.vscode.postMessage({ command: "batchAdjust_getNavHistory", code: code });',
    '};',
    '',
    '// ── 减仓操作 ──────────────────────────────────────────────',
    'ba.addSellItem = function(code, name, maxShares, maxCost) {',
    '  if (ba.sellItems.find(function(i){return i.code===code;})) {',
    '    baConfirm("该基金已添加", null); return;',
    '  }',
    '  ba.sellItems.push({ code:code, name:name, maxShares:maxShares, maxCost:maxCost, sellShares:0 });',
    '  ba.render();',
    '};',
    '',
    'ba.removeSellItem = function(code) {',
    '  ba.sellItems = ba.sellItems.filter(function(i){return i.code!==code;});',
    '  ba.render();',
    '};',
    '',
    '// ── pending 操作 ──────────────────────────────────────────',
    'ba.cancelPendingItem = function(id) {',
    '  baConfirm("确认取消该笔待加仓记录？", function() {',
    '    ba.vscode.postMessage({ command: "batchAdjust_cancelPending", id: id });',
    '    ba.pendingList = ba.pendingList.filter(function(r){return r.id!==id;});',
    '    ba.pendingCount = ba.pendingList.length;',
    '    ba.updatePendingBadge();',
    '    ba.render();',
    '  });',
    '};',
    '',
    '// ── 确认操作 ──────────────────────────────────────────────',
    'ba.handleConfirm = function() {',
    '  if (ba.confirming) return;',
    '  if (ba.activeTab==="buy")  ba.confirmBuy();',
    '  else if (ba.activeTab==="sell") ba.confirmSell();',
    '};',
    '',
    'ba.confirmBuy = function() {',
    '  var valid = ba.buyItems.filter(function(i){return i.amount>0 && i.selectedDate;});',
    '  if (valid.length===0) { baConfirm("请填写有效的加仓信息", null); return; }',
    '  ba.confirming = true; ba.render();',
    '  ba.vscode.postMessage({ command: "batchAdjust_confirmBuy", items: valid.map(function(i) {',
    '    return { code:i.code, name:i.name, buyDate:i.selectedDate==="today"?ba.todayStr():i.selectedDate, amount:i.amount, nav:i.selectedNav, isPending:i.selectedDate==="today" };',
    '  })});',
    '};',
    '',
    'ba.confirmSell = function() {',
    '  var valid = ba.sellItems.filter(function(i){return i.sellShares>0 && i.sellShares<=i.maxShares;});',
    '  if (valid.length===0) { baConfirm("请填写有效的减仓信息", null); return; }',
    '  ba.confirming = true; ba.render();',
    '  ba.vscode.postMessage({ command: "batchAdjust_confirmSell", items: valid.map(function(i) {',
    '    return { code:i.code, name:i.name, sellShares:i.sellShares };',
    '  })});',
    '};',
    '',
    '// ── 消息处理（从 Extension Host 接收）─────────────────────',
    'ba.handleMessage = function(msg) {',
    '  switch(msg.command) {',
    '    case "batchAdjust_pendingList":',
    '      ba.pendingList = msg.list || [];',
    '      ba.pendingCount = ba.pendingList.length;',
    '      ba.updatePendingBadge();',
    '      if (ba.visible) ba.render();',
    '      break;',
    '    case "batchAdjust_searchResult":',
    '      ba.showSearchDropdown(msg.results || [], msg.target);',
    '      break;',
    '    case "batchAdjust_navHistory":',
    '      ba.onNavHistoryReceived(msg.code, msg.list || [], msg.error);',
    '      break;',
    '    case "batchAdjust_buyDone":',
    '      ba.confirming = false;',
    '      ba.buyItems = [];',
    '      ba.vscode.postMessage({ command: "batchAdjust_loadPending" });',
    '      ba.close();',
    '      baConfirm(msg.message || "操作完成", null);',
    '      break;',
    '    case "batchAdjust_sellDone":',
    '      ba.confirming = false;',
    '      ba.sellItems = [];',
    '      ba.close();',
    '      baConfirm(msg.message || "减仓完成", null);',
    '      break;',
    '    case "batchAdjust_error":',
    '      ba.confirming = false;',
    '      ba.render();',
    '      baConfirm(msg.message || "操作失败", null);',
    '      break;',
    '    case "batchAdjust_pendingReady":',
    '      ba.pendingReadyList = msg.list || [];',
    '      if (ba.pendingReadyList.length > 0) ba.showPendingConfirm();',
    '      break;',
    '  }',
    '};',
    '',
    'ba.showSearchDropdown = function(results, target) {',
    '  var dropdownId = target==="buy" ? "baBuyDropdown" : "baSellDropdown";',
    '  var dropdown = document.getElementById(dropdownId);',
    '  if (!dropdown) return;',
    '  if (results.length===0) { dropdown.style.display="none"; return; }',
    '  dropdown.innerHTML = results.map(function(r) {',
    '    return \'<div class="ba-dropdown-item" data-code="\'+r.code+\'" data-name="\'+r.name+\'">\'',
    '      +\'<span class="ba-dc">\'+r.code+\'</span><span class="ba-dn">\'+r.name+\'</span></div>\';',
    '  }).join("");',
    '  dropdown.style.display = "block";',
    '  dropdown.querySelectorAll(".ba-dropdown-item").forEach(function(item) {',
    '    item.addEventListener("mousedown", function(e) {',
    '      e.preventDefault();',
    '      ba.addBuyItem(item.dataset.code, item.dataset.name);',
    '      var searchEl = document.getElementById("baBuySearch");',
    '      if (searchEl) searchEl.value = "";',
    '      dropdown.style.display = "none";',
    '    });',
    '  });',
    '};',
    '',
    'ba.onNavHistoryReceived = function(code, list, error) {',
    '  var item = ba.buyItems.find(function(i){return i.code===code;});',
    '  if (!item) return;',
    '  item.navLoading = false;',
    '  item.navError = !!error;',
    '  item.navList = list || [];',
    '  ba.render();',
    '};',
    '',
    '// ── Pending 确认弹窗 ──────────────────────────────────────',
    'ba.showPendingConfirm = function() {',
    '  var overlay = document.getElementById("pendingConfirmOverlay");',
    '  if (!overlay) return;',
    '  var panel = document.getElementById("pendingConfirmPanel");',
    '  if (!panel) return;',
    '  panel.innerHTML = ba.renderPendingConfirmContent();',
    '  overlay.style.display = "flex";',
    '  ba.bindPendingConfirmEvents();',
    '};',
    '',
    'ba.renderPendingConfirmContent = function() {',
    '  var itemsHtml = ba.pendingReadyList.map(function(record) {',
    '    var fund = ba.fundDataCache.find(function(f){return f.code===record.code;});',
    '    var oldNum = fund ? parseFloat(fund.num)||0 : 0;',
    '    var oldCost = fund ? parseFloat(fund.cost)||0 : 0;',
    '    var nav = record.navOnBuyDate || 0;',
    '    var addShares = nav>0 ? record.amount/nav : 0;',
    '    var newNum = oldNum + addShares;',
    '    var newCost = newNum>0 ? (oldCost*oldNum + nav*addShares)/newNum : nav;',
    '    var oldAmount = oldNum * oldCost;',
    '    var newAmount = newNum * newCost;',
    '    return \'<div class="ba-confirm-card">\'',
    '      +\'<div class="ba-confirm-header"><span class="ba-item-name">\'+record.name+\'</span><span class="ba-item-code">\'+record.code+\'</span></div>\'',
    '      +\'<div class="ba-confirm-row"><span class="ba-clabel">买入日期</span><span>\'+record.buyDate+\'</span></div>\'',
    '      +\'<div class="ba-confirm-row"><span class="ba-clabel">买入净值</span><span>\'+(nav.toFixed(4))+\'</span></div>\'',
    '      +\'<div class="ba-confirm-row"><span class="ba-clabel">买入金额</span><span>\'+(record.amount.toFixed(2))+\' 元</span></div>\'',
    '      +\'<div class="ba-confirm-row"><span class="ba-clabel">新增份额</span><span class="ba-positive">+\'+(addShares.toFixed(2))+\' 份</span></div>\'',
    '      +\'<div class="ba-divider"></div>\'',
    '      +\'<div class="ba-confirm-row"><span class="ba-clabel">持有份额</span><span>\'+(oldNum.toFixed(2))+\' → <strong>\'+(newNum.toFixed(2))+\'</strong> 份</span></div>\'',
    '      +\'<div class="ba-confirm-row"><span class="ba-clabel">新成本价</span><span>\'+(oldCost.toFixed(4))+\' → <strong>\'+(newCost.toFixed(4))+\'</strong></span></div>\'',
    '      +\'<div class="ba-confirm-row"><span class="ba-clabel">持仓总额</span><span>\'+(oldAmount.toFixed(2))+\' → <strong>\'+(newAmount.toFixed(2))+\'</strong> 元</span></div>\'',
    '      +\'</div>\';',
    '  }).join("");',
    '',
    '  return \'<div class="ba-confirm-header-bar">\'',
    '    +\'<span class="ba-title">净值已更新，确认加仓？</span></div>\'',
    '    +\'<p class="ba-confirm-hint">以下基金的买入日净值已更新，请确认是否加仓：</p>\'',
    '    +\'<div class="ba-confirm-list">\'+ itemsHtml +\'</div>\'',
    '    +\'<div class="ba-footer">\'',
    '    +\'<button class="ba-btn-cancel" id="pendingConfirmDismiss">稍后再说</button>\'',
    '    +\'<button class="ba-btn-confirm" id="pendingConfirmOk">全部确认加仓</button>\'',
    '    +\'</div>\';',
    '};',
    '',
    'ba.bindPendingConfirmEvents = function() {',
    '  var dismiss = document.getElementById("pendingConfirmDismiss");',
    '  var ok = document.getElementById("pendingConfirmOk");',
    '  var overlay = document.getElementById("pendingConfirmOverlay");',
    '  dismiss?.addEventListener("click", function() { overlay.style.display="none"; });',
    '  ok?.addEventListener("click", function() {',
    '    ba.vscode.postMessage({ command: "batchAdjust_confirmPending", ids: ba.pendingReadyList.map(function(r){return r.id;}) });',
    '    overlay.style.display="none";',
    '    ba.pendingReadyList = [];',
    '  });',
    '};',
    '',
    '// ── 暴露给外部 ────────────────────────────────────────────',
    'window.batchAdjust = ba;',
    '',
    '}; // end initBatchAdjust',
  ]
}
