/**
 * Webview 样式
 */

export function getStyles(): string[] {
  return [
    '/**',
    ' * 基金 Webview 样式 - 使用 VSCode 内置 CSS 变量',
    ' */',
    '',
    '* {',
    '  margin: 0;',
    '  padding: 0;',
    '  box-sizing: border-box;',
    '}',
    '',
    'body {',
    '  font-family: var(--vscode-font-family);',
    '  font-size: var(--vscode-font-size);',
    '  color: var(--vscode-foreground);',
    '  background: var(--vscode-sideBar-background);',
    '  overflow: hidden;',
    '}',
    '',
    '.fund-webview-container {',
    '  display: flex;',
    '  flex-direction: column;',
    '  height: 100vh;',
    '}',
    '',
    '/* ========== 账户资产模块 - 一行展示 ========== */',
    '.account-summary {',
    '  padding: 16px 12px;',
    '  background: var(--vscode-sideBar-background);',
    '  border-bottom: 1px solid var(--vscode-sideBarSectionHeader-border);',
    '  flex-shrink: 0;',
    '}',
    '',
    '.account-stats {',
    '  display: flex;',
    '  gap: 20px;',
    '  justify-content: space-between;',
    '}',
    '.stat-item-wrapper {',
    '  display: flex;',
    '  gap: 12px;',
    '}',
    '.stat-item {',
    '  flex: 1;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 2px;',
    '}',
    '',
    '.stat-label {',
    '  font-size: 11px;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-bottom: 4px;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '}',
    '',
    '.btn-toggle-privacy {',
    '  padding: 0;',
    '  background: transparent;',
    '  border: none;',
    '  cursor: pointer;',
    '  color: var(--vscode-icon-foreground);',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  opacity: 0.6;',
    '  transition: opacity 0.1s;',
    '}',
    '',
    '.btn-toggle-privacy:hover {',
    '  opacity: 1;',
    '}',
    '',
    '.stat-value-large {',
    '  font-size: 20px;',
    '  font-weight: 600;',
    '  color: var(--vscode-foreground);',
    '}',
    '',
    '.stat-value {',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '}',
    '',
    '/* 隐私模式 - 模糊敏感数据 */',
    '/* 账户资产区域：',
    '   - 资产总额：隐藏',
    '   - 持有收益：第一行（收益额）隐藏，第二行（收益率）不隐藏',
    '   - 日收益：第一行（收益额）隐藏，第二行（收益率）不隐藏',
    '*/',
    'body.privacy-mode .stat-value-large {',
    '  filter: blur(4px);',
    '  user-select: none;',
    '  cursor: help;',
    '  transition: filter 0.2s ease;',
    '}',
    '',
    'body.privacy-mode .stat-value-large:hover {',
    '  filter: blur(0px);',
    '}',
    '',
    '/* 持有收益和日收益的金额隐藏，百分比不隐藏 */',
    'body.privacy-mode #holdingAmount,',
    'body.privacy-mode #dailyAmount {',
    '  filter: blur(4px);',
    '  user-select: none;',
    '  cursor: help;',
    '  transition: filter 0.2s ease;',
    '}',
    '',
    'body.privacy-mode #holdingAmount:hover,',
    'body.privacy-mode #dailyAmount:hover {',
    '  filter: blur(0px);',
    '}',
    '',
    '/* 表格数据隐藏规则（使用 class 而不是 nth-child，因为列顺序可调整）：',
    '   - 估算涨幅：不隐藏（百分比和更新时间都不是敏感数据）',
    '   - 估算收益：第一行隐藏（金额）',
    '   - 当日涨幅：不隐藏',
    '   - 当日收益：隐藏（金额）',
    '   - 持有收益：第一行隐藏（金额）',
    '   - 总收益率：第一行不隐藏（百分比），第二行隐藏（金额）',
    '   - 关联板块：不隐藏',
    '   - 金额/份额：全部隐藏',
    '   - 成本/最新：不隐藏',
    '*/',
    '',
    '/* 隐藏所有带 privacy-hide-amount class 的元素 */',
    'body.privacy-mode .privacy-hide-amount {',
    '  filter: blur(4px);',
    '  user-select: none;',
    '  cursor: help;',
    '  transition: filter 0.2s ease;',
    '}',
    '',
    'body.privacy-mode .privacy-hide-amount:hover {',
    '  filter: blur(0px);',
    '}',
    '',
    '/* ========== 基金列表模块 ========== */',
    '.fund-list {',
    '  flex: 1;',
    '  display: flex;',
    '  flex-direction: column;',
    '  overflow: hidden;',
    '}',
    '',
    '.fund-list-header {',
    '  padding: 8px 12px;',
    '  background: var(--vscode-sideBarSectionHeader-background);',
    '  border-bottom: 1px solid var(--vscode-sideBarSectionHeader-border);',
    '  flex-shrink: 0;',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  overflow-y: auto;',
    '}',
    '',
    '.header-title {',
    '  font-size: 11px;',
    '  font-weight: 600;',
    '  color: var(--vscode-sideBarTitle-foreground);',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  white-space: nowrap;',
    '}',
    '',
    '.header-actions {',
    '  display: flex;',
    '  gap: 4px;',
    '  align-items: center;',
    '}',
    '',
    '@media (max-width: 400px) {',
    '  .header-actions .btn-settings,',
    '  .header-actions .btn-market {',
    '    padding: 5px 6px;',
    '  }',
    '',
    '  .header-actions .btn-settings span,',
    '  .header-actions .btn-market span {',
    '    display: none;',
    '  }',
    '',
    '  .search-box input {',
    '    width: 100px !important;',
    '  }',
    '}',
    '',
    '.btn-settings {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '  padding: 3.5px 6px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border: 0px solid var(--vscode-panel-border);',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  font-size: 12px;',
    '  font-family: inherit;',
    '  white-space: nowrap;',
    '}',
    '',
    '.btn-settings:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '',
    '.btn-settings svg {',
    '  flex-shrink: 0;',
    '}',
    '',
    '.market-status {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '  padding: 4px 8px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  border-radius: 3px;',
    '  font-size: 11px;',
    '  white-space: nowrap;',
    '}',
    '',
    '.status-dot {',
    '  width: 6px;',
    '  height: 6px;',
    '  border-radius: 50%;',
    '  background: var(--vscode-descriptionForeground);',
    '  flex-shrink: 0;',
    '}',
    '',
    '.status-dot.status-open {',
    '  background: #73c991;',
    '  box-shadow: 0 0 4px rgba(115, 201, 145, 0.6);',
    '  animation: pulse 2s ease-in-out infinite;',
    '}',
    '',
    '.status-dot.status-closed {',
    '  background: #f14c4c;',
    '}',
    '',
    '.status-dot.status-after-hours {',
    '  background: #858585;',
    '}',
    '',
    '@keyframes pulse {',
    '  0%, 100% {',
    '    opacity: 1;',
    '  }',
    '  50% {',
    '    opacity: 0.5;',
    '  }',
    '}',
    '',
    '.status-text {',
    '  color: var(--vscode-badge-foreground);',
    '  font-weight: 500;',
    '}',
    '',
    '.search-box {',
    '  position: relative;',
    '  display: flex;',
    '  align-items: center;',
    '}',
    '',
    '.btn-market {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '  padding: 3.5px 6px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border: 0px solid var(--vscode-panel-border);',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  font-size: 12px;',
    '  font-family: inherit;',
    '  white-space: nowrap;',
    '}',
    '',
    '.btn-market:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '',
    '.btn-market svg {',
    '  flex-shrink: 0;',
    '}',
    '',
    '.search-box input {',
    '  width: 150px;',
    '  padding: 4px 24px 4px 8px;',
    '  background: var(--vscode-input-background);',
    '  border: 1px solid var(--vscode-input-border);',
    '  border-radius: 2px;',
    '  color: var(--vscode-input-foreground);',
    '  font-size: 12px;',
    '  font-family: var(--vscode-font-family);',
    '  outline: none;',
    '',
    '}',
    '',
    '.search-box input:focus {',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '',
    '.search-box input::placeholder {',
    '  color: var(--vscode-input-placeholderForeground);',
    '}',
    '',
    '.btn-clear {',
    '  position: absolute;',
    '  right: 4px;',
    '  width: 16px;',
    '  height: 16px;',
    '  padding: 0;',
    '  background: transparent;',
    '  border: none;',
    '  border-radius: 2px;',
    '  cursor: pointer;',
    '  font-size: 14px;',
    '  line-height: 1;',
    '  color: var(--vscode-icon-foreground);',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '',
    '.btn-clear:hover {',
    '  background: var(--vscode-toolbar-hoverBackground);',
    '}',
    '',
    '.header-btn {',
    '  padding: 4px 8px;',
    '  background: transparent;',
    '  border: none;',
    '  border-radius: 2px;',
    '  cursor: pointer;',
    '  font-size: 11px;',
    '  color: var(--vscode-foreground);',
    '  font-family: var(--vscode-font-family);',
    '  transition: background 0.1s;',
    '}',
    '',
    '.header-btn:hover {',
    '  background: var(--vscode-toolbar-hoverBackground);',
    '}',
    '',
    '.fund-list-content {',
    '  flex: 1;',
    '  overflow-y: auto;',
    '  overflow-x: hidden;',
    '}',
    '',
    '/* ========== 表格样式 ========== */',
    '.fund-table-wrapper {',
    '  position: relative;',
    '  height: 100%;',
    '  overflow: auto;',
    '}',
    '',
    '.fund-table {',
    '  width: max-content;',
    '  min-width: 100%;',
    '  border-collapse: collapse;',
    '  table-layout: auto;',
    '}',
    '',
    '.fund-table-header {',
    '  background: var(--vscode-sideBarSectionHeader-background);',
    '  border-bottom: 1px solid var(--vscode-sideBarSectionHeader-border);',
    '  position: sticky;',
    '  top: 0;',
    '  z-index: 10;',
    '}',
    '',
    '.fund-table-header tr {',
    '  display: table-row;',
    '}',
    '',
    '.fund-table-body {',
    '  display: table-row-group;',
    '}',
    '',
    '.fund-table-body tr {',
    '  border-bottom: 1px solid var(--vscode-sideBarSectionHeader-border);',
    '  transition: background 0.1s;',
    '}',
    '',
    '.fund-table-body tr:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '',
    '.fund-table-header th {',
    '  padding: 8px 12px;',
    '  text-align: center;',
    '  font-size: 11px;',
    '  font-weight: 600;',
    '  color: var(--vscode-descriptionForeground);',
    '  white-space: nowrap;',
    '  background: var(--vscode-sideBar-background);',
    '  user-select: none;',
    '  transition: background 0.1s;',
    '  vertical-align: middle;',
    '}',
    '',
    '.fund-table-header th.th-center {',
    '  text-align: center;',
    '}',
    '',
    '.fund-table-header th.th-name {',
    '  position: sticky;',
    '  left: 0;',
    '  z-index: 12;',
    '  min-width: 140px;',
    '  max-width: 140px;',
    '  text-align: left;',
    '  background: var(--vscode-sideBar-background);',
    '}',
    '',
    '/* 使用伪元素创建阴影，避免被 overflow 裁剪 */',
    '.fund-table-header th.th-name::after {',
    '  content: "";',
    '  position: absolute;',
    '  top: 0;',
    '  right: -10px;',
    '  bottom: 0;',
    '  width: 10px;',
    '  pointer-events: none;',
    '  opacity: 0;',
    '  transition: opacity 0.2s ease;',
    '  background: linear-gradient(to right, rgba(0, 0, 0, 0.15), transparent);',
    '}',
    '',
    '/* 滚动时显示阴影 */',
    '.fund-table-header th.th-name.scrolled::after {',
    '  opacity: 1;',
    '}',
    '',
    '.fund-table-header th[data-sort] {',
    '  cursor: pointer;',
    '}',
    '',
    '.fund-table-header th[data-sort]:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '',
    '.fund-table-header th.th-sector {',
    '  cursor: default;',
    '}',
    '',
    '.fund-table-header th.th-sector:hover {',
    '  background: var(--vscode-sideBarSectionHeader-background);',
    '}',
    '',
    '.th-content {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: flex-end;',
    '  gap: 8px;',
    '}',
    '',
    '.th-text {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: flex-end;',
    '  gap: 2px;',
    '}',
    '',
    '.th-date {',
    '  font-size: 9px;',
    '  color: var(--vscode-descriptionForeground);',
    '  opacity: 0.7;',
    '}',
    '',
    '.sort-arrows {',
    '  display: inline-flex;',
    '  flex-direction: column;',
    '  line-height: 0.5;',
    '  font-size: 8px;',
    '  flex-shrink: 0;',
    '  gap: 4px;',
    '}',
    '',
    '.sort-arrows .arrow-up,',
    '.sort-arrows .arrow-down {',
    '  color: var(--vscode-descriptionForeground);',
    '  opacity: 0.3;',
    '}',
    '',
    '.sort-arrows .arrow-up.active,',
    '.sort-arrows .arrow-down.active {',
    '  color: var(--vscode-foreground);',
    '  opacity: 1;',
    '}',
    '',
    '.fund-table-body td {',
    '  padding: 8px 12px;',
    '  font-size: 13px;',
    '  white-space: nowrap;',
    '  vertical-align: center;',
    '}',
    '',
    '.fund-table-body td.td-name {',
    '  position: sticky;',
    '  left: 0;',
    '  background: var(--vscode-sideBar-background);',
    '  z-index: 9;',
    '  min-width: 140px;',
    '  max-width: 140px;',
    '}',
    '',
    '/* 使用伪元素创建阴影，避免被 overflow 裁剪 */',
    '.fund-table-body td.td-name::after {',
    '  content: "";',
    '  position: absolute;',
    '  top: 0;',
    '  right: -10px;',
    '  bottom: 0;',
    '  width: 10px;',
    '  pointer-events: none;',
    '  opacity: 0;',
    '  transition: opacity 0.2s ease;',
    '  background: linear-gradient(to right, rgba(0, 0, 0, 0.15), transparent);',
    '}',
    '',
    '/* 滚动时显示阴影 */',
    '.fund-table-body td.td-name.scrolled::after {',
    '  opacity: 1;',
    '}',
    '',
    '.fund-table-body tr:hover td.td-name {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '',
    '.fund-table-body td.td-value {',
    '  text-align: right;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '',
    '.td-sub {',
    '  font-size: 11px;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-top: 2px;',
    '}',
    '',
    '/* 基金名称列 */',
    '.fund-name-cell {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 4px;',
    '  min-width: 116px;',
    '  max-width: 116px;',
    '}',
    '',
    '.fund-name {',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  color: var(--vscode-foreground);',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  white-space: nowrap;',
    '}',
    '',
    '.fund-code {',
    '  font-size: 11px;',
    '  color: var(--vscode-descriptionForeground);',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between',
    '}',
    '',
    '.code-text {',
    '  display: inline-flex;',
    '  align-items: center;',
    '}',
    '',
    '/* ========== Tooltip 样式 ========== */',
    '.fund-tooltip {',
    '  position: fixed;',
    '  z-index: 9999;',
    '  background: var(--vscode-editorHoverWidget-background);',
    '  border: 1px solid var(--vscode-editorHoverWidget-border);',
    '  border-radius: 4px;',
    '  padding: 12px;',
    '  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);',
    '  min-width: 120px;',
    '  max-width: 240px;',
    '  font-size: 12px;',
    '  color: var(--vscode-editorHoverWidget-foreground);',
    '  pointer-events: auto;',
    '  box-sizing: border-box;',
    '  overflow: hidden;',
    '}',
    '',
    '.tooltip-header {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: flex-start;',
    '  margin-bottom: 4px;',
    '  gap: 8px;',
    '}',
    '',
    '.tooltip-title {',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '  color: var(--vscode-foreground);',
    '  flex: 1;',
    '  word-break: break-word;',
    '  line-height: 1.4;',
    '  overflow-wrap: break-word;',
    '  hyphens: auto;',
    '  min-width: 0;',
    '}',
    '',
    '.tooltip-actions {',
    '  display: flex;',
    '  gap: 4px;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.tooltip-copy-btn,',
    '.tooltip-close-btn {',
    '  padding: 4px;',
    '  background: transparent;',
    '  border: 1px solid var(--vscode-button-border);',
    '  border-radius: 2px;',
    '  cursor: pointer;',
    '  color: var(--vscode-icon-foreground);',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: all 0.1s;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.tooltip-copy-btn:hover,',
    '.tooltip-close-btn:hover {',
    '  background: var(--vscode-button-hoverBackground);',
    '}',
    '',
    '.tooltip-close-btn {',
    '  font-size: 18px;',
    '  line-height: 1;',
    '  font-weight: 400;',
    '  width: 22px;',
    '  height: 22px;',
    '  padding: 0;',
    '}',
    '',
    '.tooltip-close-btn:hover {',
    '  background: var(--vscode-inputValidation-errorBackground);',
    '  border-color: var(--vscode-errorForeground);',
    '  color: var(--vscode-errorForeground);',
    '}',
    '',
    '.tooltip-code {',
    '  font-size: 11px;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-bottom: 8px;',
    '}',
    '',
    '.tooltip-divider {',
    '  height: 1px;',
    '  background: var(--vscode-editorHoverWidget-border);',
    '  margin: 8px 0;',
    '}',
    '',
    '.tooltip-row {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  padding: 3px 0;',
    '  gap: 12px;',
    '}',
    '',
    '.tooltip-label {',
    '  color: var(--vscode-descriptionForeground);',
    '  font-size: 11px;',
    '  white-space: nowrap;',
    '}',
    '',
    '.tooltip-value {',
    '  font-weight: 500;',
    '  text-align: right;',
    '  font-variant-numeric: tabular-nums;',
    '  word-break: break-word;',
    '  overflow-wrap: break-word;',
    '  min-width: 0;',
    '  flex-shrink: 0;',
    '}',
    '',
    '/* Tooltip 中的颜色类 */',
    '.fund-tooltip .color-up {',
    '  color: #f14c4c;',
    '}',
    '',
    '.fund-tooltip .color-down {',
    '  color: #73c991;',
    '}',
    '',
    '.fund-tooltip .color-flat {',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '',
    '/* Tooltip 操作按钮行 */',
    '.tooltip-actions-row {',
    '  display: flex;',
    '  gap: 6px;',
    '  margin-top: 8px;',
    '  padding-top: 8px;',
    '  border-top: 1px solid var(--vscode-editorHoverWidget-border);',
    '  flex-wrap: wrap;',
    '}',
    '',
    '.tooltip-action-btn {',
    '  flex: 1;',
    '  min-width: 60px;',
    '  padding: 6px 8px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  border: 1px solid var(--vscode-button-border);',
    '  border-radius: 3px;',
    '  cursor: pointer;',
    '  font-size: 11px;',
    '  color: var(--vscode-button-secondaryForeground);',
    '  font-family: var(--vscode-font-family);',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 4px;',
    '  transition: all 0.1s;',
    '  white-space: nowrap;',
    '}',
    '',
    '.tooltip-action-btn:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '',
    '.tooltip-action-btn svg {',
    '  flex-shrink: 0;',
    '}',
    '',
    '.tooltip-action-btn.btn-success {',
    '  color: #73c991;',
    '  border-color: #73c991;',
    '}',
    '',
    '.tooltip-action-btn.btn-success:hover {',
    '  background: rgba(115, 201, 145, 0.1);',
    '}',
    '',
    '.tooltip-action-btn.btn-warning {',
    '  color: #cca700;',
    '  border-color: #cca700;',
    '}',
    '',
    '.tooltip-action-btn.btn-warning:hover {',
    '  background: rgba(204, 167, 0, 0.1);',
    '}',
    '',
    '.tooltip-action-btn.btn-danger {',
    '  color: var(--vscode-errorForeground);',
    '  border-color: var(--vscode-errorForeground);',
    '}',
    '',
    '.tooltip-action-btn.btn-danger:hover {',
    '  background: var(--vscode-inputValidation-errorBackground);',
    '}',
    '',
    '/* 基金名称可 hover */',
    '.fund-name[data-tooltip] {',
    '  cursor: help;',
    '  position: relative;',
    '}',
    '',
    '.fund-name[data-tooltip]:hover {',
    '  text-decoration: underline;',
    '  text-decoration-style: dotted;',
    '}',
    '',
    '/* ========== 分组 Tooltip 样式 ========== */',
    '.group-tooltip {',
    '  position: fixed;',
    '  z-index: 9999;',
    '  background: var(--vscode-editorHoverWidget-background);',
    '  border: 1px solid var(--vscode-editorHoverWidget-border);',
    '  border-radius: 4px;',
    '  padding: 12px;',
    '  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);',
    '  min-width: 180px;',
    '  max-width: 280px;',
    '  font-size: 12px;',
    '  color: var(--vscode-editorHoverWidget-foreground);',
    '  pointer-events: auto;',
    '  box-sizing: border-box;',
    '  overflow: hidden;',
    '}',
    '',
    '/* 分组 Tooltip 中的颜色类 */',
    '.group-tooltip .color-up {',
    '  color: #f14c4c;',
    '}',
    '',
    '.group-tooltip .color-down {',
    '  color: #73c991;',
    '}',
    '',
    '.group-tooltip .color-flat {',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '',
    '/* 分组标签可 hover */',
    '.group-tag-btn[data-group-stats] {',
    '  cursor: pointer;',
    '  position: relative;',
    '}',
    '',
    '/* ========== 列设置弹窗 ========== */',
    '.column-settings-modal {',
    '  position: fixed;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  z-index: 10000;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '',
    '.modal-overlay {',
    '  position: absolute;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  background: rgba(0, 0, 0, 0.5);',
    '}',
    '',
    '.modal-content {',
    '  position: relative;',
    '  background: var(--vscode-editor-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  width: 90%;',
    '  max-width: 500px;',
    '  max-height: 80vh;',
    '  display: flex;',
    '  flex-direction: column;',
    '  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.3);',
    '}',
    '',
    '.modal-header {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  padding: 12px 14px;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '}',
    '',
    '.modal-header h3 {',
    '  margin: 0;',
    '  font-size: 16px;',
    '  font-weight: 600;',
    '  color: var(--vscode-foreground);',
    '}',
    '',
    '.modal-close {',
    '  width: 28px;',
    '  height: 28px;',
    '  padding: 0;',
    '  background: transparent;',
    '  border: none;',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  font-size: 20px;',
    '  line-height: 1;',
    '  color: var(--vscode-foreground);',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: background 0.1s;',
    '}',
    '',
    '.modal-close:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '',
    '.modal-body {',
    '  flex: 1;',
    '  overflow-y: auto;',
    '  padding: 12px;',
    '}',
    '',
    '.settings-section {',
    '  margin-bottom: 24px;',
    '}',
    '',
    '.settings-section:last-child {',
    '  margin-bottom: 0;',
    '}',
    '',
    '.settings-section h4 {',
    '  margin: 0 0 8px 0;',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '  color: var(--vscode-foreground);',
    '}',
    '',
    '.settings-hint {',
    '  margin: 0 0 12px 0;',
    '  font-size: 12px;',
    '  color: var(--vscode-descriptionForeground);',
    '  line-height: 1.4;',
    '}',
    '',
    '.column-checkboxes {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 8px;',
    '}',
    '',
    '.column-checkbox {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  padding: 6px 8px;',
    '  border-radius: 3px;',
    '  cursor: pointer;',
    '  transition: background 0.1s;',
    '}',
    '',
    '.column-checkbox:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '',
    '.column-checkbox.disabled {',
    '  opacity: 0.5;',
    '  cursor: not-allowed;',
    '}',
    '',
    '.column-checkbox input[type="checkbox"] {',
    '  cursor: pointer;',
    '}',
    '',
    '.column-checkbox.disabled input[type="checkbox"] {',
    '  cursor: not-allowed;',
    '}',
    '',
    '.column-order-list {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 6px;',
    '}',
    '',
    '.column-order-item {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 12px;',
    '  padding: 10px 12px;',
    '  background: var(--vscode-input-background);',
    '  border: 1px solid var(--vscode-input-border);',
    '  border-radius: 3px;',
    '  transition: all 0.2s;',
    '  cursor: move;',
    '}',
    '',
    '.column-order-item:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '',
    '.column-order-item.fixed-column {',
    '  background: var(--vscode-editor-inactiveSelectionBackground);',
    '  opacity: 0.8;',
    '  cursor: default;',
    '}',
    '',
    '.column-order-item.dragging {',
    '  opacity: 0.5;',
    '  transform: scale(0.95);',
    '}',
    '',
    '.column-order-item.drag-over {',
    '  border-color: var(--vscode-focusBorder);',
    '  border-width: 2px;',
    '  background: var(--vscode-list-activeSelectionBackground);',
    '  transform: translateY(-2px);',
    '  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);',
    '}',
    '',
    '.column-checkbox-inline {',
    '  flex: 1;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  cursor: pointer;',
    '  min-width: 0;',
    '}',
    '',
    '.column-checkbox-inline input[type="checkbox"] {',
    '  cursor: pointer;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.column-checkbox-inline input[type="checkbox"]:disabled {',
    '  cursor: not-allowed;',
    '}',
    '',
    '.drag-handle {',
    '  cursor: grab;',
    '  color: var(--vscode-descriptionForeground);',
    '  font-size: 16px;',
    '  user-select: none;',
    '  flex-shrink: 0;',
    '  transition: color 0.2s;',
    '}',
    '',
    '.column-order-item:not(.fixed-column):hover .drag-handle {',
    '  color: var(--vscode-foreground);',
    '}',
    '',
    '.column-order-item.fixed-column .drag-handle {',
    '  cursor: not-allowed;',
    '  opacity: 0.5;',
    '}',
    '',
    '.column-order-item:active .drag-handle {',
    '  cursor: grabbing;',
    '}',
    '',
    '.column-label {',
    '  font-size: 13px;',
    '  color: var(--vscode-foreground);',
    '  user-select: none;',
    '}',
    '',
    '.order-buttons {',
    '  display: flex;',
    '  gap: 4px;',
    '}',
    '',
    '.btn-order-up,',
    '.btn-order-down {',
    '  width: 24px;',
    '  height: 24px;',
    '  padding: 0;',
    '  background: transparent;',
    '  border: 1px solid var(--vscode-button-border);',
    '  border-radius: 2px;',
    '  cursor: pointer;',
    '  font-size: 12px;',
    '  color: var(--vscode-button-foreground);',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: all 0.1s;',
    '}',
    '',
    '.btn-order-up:hover:not(:disabled),',
    '.btn-order-down:hover:not(:disabled) {',
    '  background: var(--vscode-button-hoverBackground);',
    '}',
    '',
    '.btn-order-up:disabled,',
    '.btn-order-down:disabled {',
    '  opacity: 0.3;',
    '  cursor: not-allowed;',
    '}',
    '',
    '.modal-footer {',
    '  display: flex;',
    '  justify-content: flex-end;',
    '  gap: 10px;',
    '  padding: 10px 12px;',
    '  border-top: 1px solid var(--vscode-panel-border);',
    '}',
    '',
    '.btn-secondary {',
    '  padding: 6px 14px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  border: none;',
    '  border-radius: 2px;',
    '  color: var(--vscode-button-secondaryForeground);',
    '  cursor: pointer;',
    '  font-size: 13px;',
    '  font-family: var(--vscode-font-family);',
    '  transition: background 0.1s;',
    '}',
    '',
    '.btn-secondary:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '',
    '/* ========== 颜色类 ========== */',
    '.color-up {',
    '  color: #f14c4c;',
    '}',
    '',
    '.color-down {',
    '  color: #73c991;',
    '}',
    '',
    '.color-flat {',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '',
    '/* ========== 空状态 ========== */',
    '.empty-state {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: center;',
    '  justify-content: center;',
    '  padding: 60px 20px;',
    '  text-align: center;',
    '}',
    '',
    '.empty-state p {',
    '  font-size: 13px;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-bottom: 16px;',
    '}',
    '',
    '.btn-primary {',
    '  padding: 6px 14px;',
    '  background: var(--vscode-button-background);',
    '  border: none;',
    '  border-radius: 2px;',
    '  color: var(--vscode-button-foreground);',
    '  cursor: pointer;',
    '  font-size: 13px;',
    '  font-family: var(--vscode-font-family);',
    '  transition: background 0.1s;',
    '}',
    '',
    '.btn-primary:hover {',
    '  background: var(--vscode-button-hoverBackground);',
    '}',
    '',
    '/* ========== 加载状态 ========== */',
    '.loading {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  padding: 40px;',
    '  font-size: 13px;',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '',
    '/* ========== 滚动条样式 ========== */',
    '.fund-list-content::-webkit-scrollbar {',
    '  width: 10px;',
    '  height: 10px;',
    '}',
    '',
    '.fund-list-content::-webkit-scrollbar-track {',
    '  background: var(--vscode-scrollbarSlider-background);',
    '}',
    '',
    '.fund-list-content::-webkit-scrollbar-thumb {',
    '  background: var(--vscode-scrollbarSlider-background);',
    '  border-radius: 5px;',
    '}',
    '',
    '.fund-list-content::-webkit-scrollbar-thumb:hover {',
    '  background: var(--vscode-scrollbarSlider-hoverBackground);',
    '}',
    '',
    '.fund-list-content::-webkit-scrollbar-thumb:active {',
    '  background: var(--vscode-scrollbarSlider-activeBackground);',
    '}',
    '',
    '/* ========== 操作按钮 ========== */',
    '.fund-actions {',
    '  display: flex;',
    '  gap: 4px;',
    '  justify-content: flex-end;',
    '}',
    '',
    '.btn-action {',
    '  padding: 4px 8px;',
    '  background: transparent;',
    '  border: 1px solid var(--vscode-button-border);',
    '  border-radius: 2px;',
    '  cursor: pointer;',
    '  font-size: 11px;',
    '  color: var(--vscode-button-foreground);',
    '  font-family: var(--vscode-font-family);',
    '  transition: all 0.1s;',
    '}',
    '',
    '.btn-action:hover {',
    '  background: var(--vscode-button-hoverBackground);',
    '}',
    '',
    '.btn-danger {',
    '  color: var(--vscode-errorForeground);',
    '  border-color: var(--vscode-errorForeground);',
    '}',
    '',
    '.btn-danger:hover {',
    '  background: var(--vscode-inputValidation-errorBackground);',
    '}',
    '',
    '.btn-success {',
    '  color: #73c991;',
    '  border-color: #73c991;',
    '}',
    '',
    '.btn-success:hover {',
    '  background: rgba(115, 201, 145, 0.1);',
    '}',
    '',
    '.btn-warning {',
    '  color: #cca700;',
    '  border-color: #cca700;',
    '}',
    '',
    '.btn-warning:hover {',
    '  background: rgba(204, 167, 0, 0.1);',
    '}',
    '',
    '/* ==================== 确认对话框样式 ==================== */',
    '.confirm-dialog {',
    '  position: fixed;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  z-index: 10000;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '',
    '.confirm-overlay {',
    '  position: absolute;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  background-color: rgba(0, 0, 0, 0.5);',
    '}',
    '',
    '.confirm-content {',
    '  position: relative;',
    '  background-color: var(--vscode-editor-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  padding: 20px;',
    '  min-width: 300px;',
    '  max-width: 500px;',
    '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);',
    '  z-index: 1;',
    '}',
    '',
    '.confirm-message {',
    '  color: var(--vscode-foreground);',
    '  font-size: 14px;',
    '  line-height: 1.6;',
    '  margin-bottom: 20px;',
    '  word-break: break-word;',
    '}',
    '',
    '.confirm-buttons {',
    '  display: flex;',
    '  justify-content: flex-end;',
    '  gap: 10px;',
    '}',
    '',
    '.confirm-btn {',
    '  padding: 6px 16px;',
    '  border: none;',
    '  border-radius: 4px;',
    '  font-size: 13px;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '  outline: none;',
    '}',
    '',
    '.confirm-btn:focus {',
    '  outline: 1px solid var(--vscode-focusBorder);',
    '  outline-offset: 2px;',
    '}',
    '',
    '.confirm-btn-cancel {',
    '  background-color: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '}',
    '',
    '.confirm-btn-cancel:hover {',
    '  background-color: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '',
    '.confirm-btn-ok {',
    '  background-color: var(--vscode-button-background);',
    '  color: var(--vscode-button-foreground);',
    '}',
    '',
    '.confirm-btn-ok:hover {',
    '  background-color: var(--vscode-button-hoverBackground);',
    '}',
    '',
    '/* ==================== 分组选择对话框 ==================== */',
    '.group-select-dialog {',
    '  position: fixed;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  z-index: 10001;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '',
    '.group-select-overlay {',
    '  position: absolute;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  background-color: rgba(0, 0, 0, 0.5);',
    '}',
    '',
    '.group-select-content {',
    '  position: relative;',
    '  background-color: var(--vscode-editor-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  min-width: 300px;',
    '  max-width: 400px;',
    '  max-height: 80vh;',
    '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);',
    '  z-index: 1;',
    '  display: flex;',
    '  flex-direction: column;',
    '}',
    '',
    '.group-select-header {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  padding: 16px 20px;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '}',
    '',
    '.group-select-title {',
    '  font-size: 14px;',
    '  font-weight: 600;',
    '  color: var(--vscode-foreground);',
    '}',
    '',
    '.group-select-close {',
    '  width: 24px;',
    '  height: 24px;',
    '  padding: 0;',
    '  background: transparent;',
    '  border: none;',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  font-size: 18px;',
    '  line-height: 1;',
    '  color: var(--vscode-icon-foreground);',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: background 0.1s;',
    '}',
    '',
    '.group-select-close:hover {',
    '  background: var(--vscode-toolbar-hoverBackground);',
    '}',
    '',
    '.group-select-fund-info {',
    '  padding: 12px 20px;',
    '  background: var(--vscode-editor-inactiveSelectionBackground);',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '}',
    '',
    '.fund-info-name {',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  color: var(--vscode-foreground);',
    '  margin-bottom: 4px;',
    '}',
    '',
    '.fund-info-code {',
    '  font-size: 11px;',
    '  color: var(--vscode-descriptionForeground);',
    '}',
    '',
    '.group-select-body {',
    '  padding: 8px 0;',
    '  max-height: 400px;',
    '  overflow-y: auto;',
    '}',
    '',
    '.group-option {',
    '  padding: 10px 20px;',
    '  cursor: pointer;',
    '  font-size: 13px;',
    '  color: var(--vscode-foreground);',
    '  transition: background 0.1s;',
    '}',
    '',
    '.group-option:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '',
    '.group-option:first-child {',
    '  color: var(--vscode-descriptionForeground);',
    '  font-style: italic;',
    '}',
    '',
    '/* ==================== 分组管理 ==================== */',
    '.group-tags-wrapper {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  padding: 8px 12px 0 0;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '}',
    '.group-tags-container {',
    '  flex: 1;',
    '  display: flex;',
    '  flex-wrap: nowrap;',
    '  overflow-x: auto;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  padding: 0 12px 8px 12px;',
    '}',
    '.group-tags-container::-webkit-scrollbar {',
    '  height: 6px;',
    '}',
    '.group-tags-container::-webkit-scrollbar-track {',
    '  background: var(--vscode-scrollbarSlider-background);',
    '}',
    '.group-tags-container::-webkit-scrollbar-thumb {',
    '  background: var(--vscode-scrollbarSlider-background);',
    '  border-radius: 3px;',
    '}',
    '.group-tags-container::-webkit-scrollbar-thumb:hover {',
    '  background: var(--vscode-scrollbarSlider-hoverBackground);',
    '}',
    '.group-tag-btn {',
    '  flex-shrink: 0;',
    '  padding: 4px 10px;',
    '  border-radius: 4px;',
    '  font-size: 12px;',
    '  cursor: pointer;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border: 0;',
    '  white-space: nowrap;',
    '  transition: all 0.2s;',
    '  height: 24px;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  position: relative;',
    '}',
    '.group-tag-btn:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.group-tag-btn.active {',
    '  background: var(--vscode-button-background);',
    '  color: var(--vscode-button-foreground);',
    '}',
    '.group-tag-text {',
    '  flex: 1;',
    '}',
    '.group-tag-delete {',
    '  display: none;',
    '  width: 16px;',
    '  height: 16px;',
    '  border-radius: 2px;',
    '  background: rgba(0, 0, 0, 0.2);',
    '  color: currentColor;',
    '  font-size: 14px;',
    '  line-height: 1;',
    '  align-items: center;',
    '  justify-content: center;',
    '  cursor: pointer;',
    '  transition: all 0.1s;',
    '  flex-shrink: 0;',
    '}',
    '.group-tag-btn:hover .group-tag-delete {',
    '  display: none;',
    '}',
    '.group-tag-delete:hover {',
    '  background: var(--vscode-errorForeground);',
    '  color: white;',
    '}',
    '.group-tag-stat {',
    '  font-size: 10px;',
    '  margin-left: 4px;',
    '  opacity: 0.8;',
    '}',
    '.group-tag-btn.active .color-up,',
    '.group-tag-btn.active .color-down,',
    '.group-tag-btn.active .color-flat {',
    '  color: inherit;',
    '  opacity: 0.9;',
    '}',
    '.group-tag-add {',
    '  flex-shrink: 0;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-width: 24px;',
    '  height: 24px;',
    '  padding: 0 8px;',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  background: transparent;',
    '  color: var(--vscode-descriptionForeground);',
    '  border: 1px dashed var(--vscode-panel-border);',
    '  font-size: 16px;',
    '  line-height: 1;',
    '  transition: all 0.2s;',
    '}',
    '.group-tag-add:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '  color: var(--vscode-foreground);',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '.group-tag-settings {',
    '  flex-shrink: 0;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-width: 24px;',
    '  height: 24px;',
    '  padding: 0 8px;',
    '  border-radius: 4px;',
    '  cursor: pointer;',
    '  background: transparent;',
    '  color: var(--vscode-descriptionForeground);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  font-size: 14px;',
    '  line-height: 1;',
    '  transition: all 0.2s;',
    '  margin-bottom: 8px;',
    '}',
    '.group-tag-settings:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '  color: var(--vscode-foreground);',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '.fund-group-label {',
    '  font-size: 11px;',
    '  padding: 2px 6px;',
    '  border-radius: 4px;',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border: 0;',
    '  margin-left: 4px;',
    '  display: inline-block;',
    '  max-width: 61px;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  white-space: nowrap;',
    '  vertical-align: middle;',
    '}',
    '',
    '/* ==================== 分组管理弹窗 ==================== */',
    '.group-manager-modal {',
    '  position: fixed;',
    '  inset: 0;',
    '  z-index: 10000;',
    '  display: none;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '.group-manager-overlay {',
    '  position: absolute;',
    '  inset: 0;',
    '  background: rgba(0, 0, 0, 0.45);',
    '}',
    '.group-manager-content {',
    '  position: relative;',
    '  z-index: 1;',
    '  width: min(900px, calc(100vw - 32px));',
    '  height: min(700px, calc(100vh - 32px));',
    '  background: var(--vscode-editor-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 8px;',
    '  display: flex;',
    '  flex-direction: column;',
    '}',
    '.group-manager-header {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  padding: 12px 14px;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '  min-width: 0;',
    '}',
    '.group-manager-header h3 {',
    '  flex: 1;',
    '  min-width: 0;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  white-space: nowrap;',
    '  margin: 0;',
    '  font-size: 16px;',
    '  font-weight: 600;',
    '}',
    '.group-manager-close {',
    '  width: 28px;',
    '  height: 28px;',
    '  padding: 0;',
    '  background: transparent;',
    '  border: none;',
    '  border-radius: 4px;',
    '  color: var(--vscode-foreground);',
    '  font-size: 20px;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: background 0.1s;',
    '  flex-shrink: 0;',
    '}',
    '.group-manager-close:hover {',
    '  background: var(--vscode-list-hoverBackground);',
    '}',
    '.group-manager-body {',
    '  flex: 1;',
    '  min-height: 0;',
    '  min-width: 0;',
    '  display: grid;',
    '  grid-template-rows: 1fr 1fr;',
    '  gap: 12px;',
    '  padding: 12px;',
    '}',
    '.group-manager-panel {',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-height: 0;',
    '  min-width: 0;',
    '  max-width: 100%;',
    '}',
    '.group-manager-panel-header {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  padding: 8px 10px;',
    '  border-bottom: 1px solid var(--vscode-panel-border);',
    '  min-width: 0;',
    '  height: 44px;',
    '}',
    '.group-manager-panel-title {',
    '  font-size: 12px;',
    '  color: var(--vscode-descriptionForeground);',
    '  flex: 1;',
    '  min-width: 0;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  white-space: nowrap;',
    '}',
    '.group-manager-add {',
    '  border: 1px dashed var(--vscode-editorWidget-border);',
    '  background: transparent;',
    '  color: var(--vscode-foreground);',
    '  border-radius: 4px;',
    '  padding: 4px 8px;',
    '  white-space: nowrap;',
    '  cursor: pointer;',
    '  font-size: 12px;',
    '  transition: all 0.2s;',
    '  flex-shrink: 0;',
    '  marign-left: 4px;',
    '}',
    '@media screen and (max-width: 370px) {',
    '  .group-manager-add span{',
    '    display: none;',
    '  }',
    '}',
    '.group-manager-add:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.group-manager-top-list,',
    '.group-manager-fund-list {',
    '  flex: 1;',
    '  min-height: 0;',
    '  min-width: 0;',
    '  max-width: 100%;',
    '  overflow: auto;',
    '  padding: 8px;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 8px;',
    '}',
    '.group-manager-item {',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  padding: 6px 8px;',
    '  gap: 8px;',
    '  background: var(--vscode-editorWidget-background);',
    '  min-width: 0;',
    '  max-width: 100%;',
    '  cursor: pointer;',
    '}',
    '.group-manager-item.active {',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '.group-manager-item-left {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  flex: 1;',
    '}',
    '.group-manager-item-name {',
    '  flex: 1;',
    '  min-width: 0;',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '}',
    '.group-manager-item-actions {',
    '  display: flex;',
    '  gap: 6px;',
    '  flex-shrink: 0;',
    '}',
    '.gm-icon {',
    '  opacity: 0.7;',
    '  flex-shrink: 0;',
    '}',
    '.gm-icon.drag {',
    '  cursor: grab;',
    '}',
    '.gm-icon.disabled {',
    '  opacity: 0.3;',
    '  cursor: not-allowed;',
    '}',
    '.gm-icon-btn {',
    '  border: 1px solid var(--vscode-panel-border);',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '  border-radius: 4px;',
    '  width: 24px;',
    '  height: 24px;',
    '  cursor: pointer;',
    '  display: flex;',
    '  justify-content: center;',
    '  align-items: center;',
    '}',
    '.gm-icon-btn.danger {',
    '  color: var(--vscode-errorForeground);',
    '}',
    '.group-manager-fund-item {',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  padding: 6px 8px;',
    '  background: var(--vscode-editorWidget-background);',
    '  min-width: 0;',
    '  max-width: 100%;',
    '}',
    '.group-manager-fund-item.focused {',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '.group-manager-fund-main {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-width: 0;',
    '}',
    '.group-manager-fund-name {',
    '  flex: 1;',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  min-width: 0;',
    '}',
    '.group-manager-fund-code {',
    '  color: var(--vscode-descriptionForeground);',
    '  font-size: 12px;',
    '  flex-shrink: 0;',
    '}',
    '.group-manager-item.dragging,',
    '.group-manager-fund-item.dragging {',
    '  opacity: 0.5;',
    '}',
    '.group-manager-item.drag-over,',
    '.group-manager-fund-item.drag-over {',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '.group-manager-footer {',
    '  display: flex;',
    '  justify-content: flex-end;',
    '  gap: 10px;',
    '  padding: 10px 12px;',
    '  border-top: 1px solid var(--vscode-panel-border);',
    '}',
    '',
    '/* ==================== 拖拽排序 ==================== */',
    '.drag-handle-icon {',
    '  cursor: grab;',
    '  color: var(--vscode-descriptionForeground);',
    '  margin-right: 4px;',
    '  font-size: 12px;',
    '  opacity: 0.5;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  line-height: 1;',
    '}',
    '.drag-handle-icon:hover {',
    '  opacity: 1;',
    '}',
    '.drag-handle-icon:active {',
    '  cursor: grabbing;',
    '}',
    '.fund-table-body tr.draggable-item {',
    '  transition: transform 0.1s;',
    '}',
    '.fund-table-body tr.dragging {',
    '  opacity: 0.5;',
    '}',
    '.fund-table-body tr.drag-over {',
    '  border-top: 2px solid var(--vscode-focusBorder);',
    '}',
    '',
    '/* ==================== 分组管理自定义弹窗 ==================== */',
    '.gm-message-dialog,',
    '.gm-prompt-dialog,',
    '.gm-confirm-dialog {',
    '  position: fixed;',
    '  inset: 0;',
    '  z-index: 10001;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '.gm-message-overlay,',
    '.gm-prompt-overlay,',
    '.gm-confirm-overlay {',
    '  position: absolute;',
    '  inset: 0;',
    '  background: rgba(0, 0, 0, 0.5);',
    '}',
    '.gm-message-content,',
    '.gm-prompt-content,',
    '.gm-confirm-content {',
    '  position: relative;',
    '  z-index: 1;',
    '  background: var(--vscode-editor-background);',
    '  border: 1px solid var(--vscode-panel-border);',
    '  border-radius: 6px;',
    '  padding: 16px;',
    '  min-width: 300px;',
    '  max-width: 400px;',
    '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);',
    '}',
    '.gm-message-text,',
    '.gm-prompt-message,',
    '.gm-confirm-message {',
    '  margin-bottom: 12px;',
    '  font-size: 13px;',
    '  color: var(--vscode-foreground);',
    '}',
    '.gm-prompt-input {',
    '  width: 100%;',
    '  padding: 6px 8px;',
    '  margin-bottom: 12px;',
    '  background: var(--vscode-input-background);',
    '  color: var(--vscode-input-foreground);',
    '  border: 1px solid var(--vscode-input-border);',
    '  border-radius: 4px;',
    '  font-size: 13px;',
    '  outline: none;',
    '  box-sizing: border-box;',
    '}',
    '.gm-prompt-input:focus {',
    '  border-color: var(--vscode-focusBorder);',
    '}',
    '.gm-message-buttons,',
    '.gm-prompt-buttons,',
    '.gm-confirm-buttons {',
    '  display: flex;',
    '  justify-content: flex-end;',
    '  gap: 8px;',
    '}',
    '.gm-message-btn,',
    '.gm-prompt-btn,',
    '.gm-confirm-btn {',
    '  padding: 6px 14px;',
    '  border-radius: 4px;',
    '  font-size: 13px;',
    '  cursor: pointer;',
    '  border: none;',
    '  transition: all 0.2s;',
    '}',
    '.gm-prompt-btn-cancel,',
    '.gm-confirm-btn-cancel {',
    '  background: var(--vscode-button-secondaryBackground);',
    '  color: var(--vscode-button-secondaryForeground);',
    '}',
    '.gm-prompt-btn-cancel:hover,',
    '.gm-confirm-btn-cancel:hover {',
    '  background: var(--vscode-button-secondaryHoverBackground);',
    '}',
    '.gm-message-btn-ok,',
    '.gm-prompt-btn-ok,',
    '.gm-confirm-btn-ok {',
    '  background: var(--vscode-button-background);',
    '  color: var(--vscode-button-foreground);',
    '}',
    '.gm-message-btn-ok:hover,',
    '.gm-prompt-btn-ok:hover,',
    '.gm-confirm-btn-ok:hover {',
    '  background: var(--vscode-button-hoverBackground);',
    '}',
  ];
}
